### ISSUE TITLE
Ubuntu 14.04 docker image error: Failed to init API, possible an invalid tessdata path: /usr/local/share/

### ISSUE THREAD

**Issue by vatsal28** [sirfz/tesserocr#101]
I'm using tesseract-ocr (version 4.00 beta) with tesserocr (2.2.2) and the location of tessdata folder is: /usr/local/share/

But I'm still getting the invalid tessdata path error. I've tried the following to fix it:

1. Assigned the environment variable as TESSDATA_PREFIX ='/usr/local/share/'
2. Added path='/usr/local/share/' in PyTessBaseAPI() 

The location of the tessdata folder is correct but I'm still not able to use this.
Note: I'm using docker with ubuntu 14.04 image and tesserocr version is 2.2.2 and tesseract version is 4.00 beta

How do I resolve this issue?

**Comment by simonflueckiger** [comment]
can you give `PyTessBaseAPI(path='/usr/local/share/tessdata/')` a try?

**Comment by vatsal28** [comment]
Tried that, but that also did not work :/

**Comment by simonflueckiger** [comment]
Ok, there might be an issue with the handling of the tessdata path if you build tesserocr with a tesseract version past commit [dba13db](https://github.com/tesseract-ocr/tesseract/pull/1356/commits/dba13db00241510821bbad8f6875084ad34e473c) and I'm currently working on a pull request which should fix that. What build of tesseract are you using? Did you build it yourself or did you download the binaries from somewhere?

**Comment by vatsal28** [comment]
I've used the following commands to build Tesseract.
```

git clone https://github.com/tesseract-ocr/tesseract.git
cd tesseract
./autogen.sh
./configure --enable-debug
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make
sudo make install
sudo ldconfig
```


For building Tesserocr, I'm using the following commands:
```
git clone https://github.com/sirfz/tesserocr.git
cd tesserocr
pip install .
```


So since I'm not specifying any particular build version, it's taking the latest one I guess.
So is this issue happening because of the latest build version?

**Comment by simonflueckiger** [comment]
Exactly, `git clone https://github.com/tesseract-ocr/tesseract.git` will pull the most recent commit and this might be the issue here, not entirely sure though. 

Can you try the following:

```
pip uninstall tesserocr
git clone https://github.com/simonflueckiger/tesserocr.git
cd tesserocr
pip install .
```

now set TESSDATA_PREFIX to '/usr/local/share/tessdata/' and init _without_ the path argument set in PyTessBaseAPI()

**Comment by simonflueckiger** [comment]
let's chat https://tlk.io/697d91

**Comment by vatsal28** [comment]
Can we chat now ?

**Comment by simonflueckiger** [comment]
so it ended up (most likely) being a corrupted eng.traineddata file which was fixed by redownloading it:

`wget -O /usr/local/share/tessdata/eng.traineddata https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata`

**Comment by vatsal28** [comment]
Thanks a lot!!
