### ISSUE TITLE
Reusing tesseract api fails on second call and gets weird after that (!?)

### ISSUE THREAD

**Issue by lorenzob** [sirfz/tesserocr#106]
I'm trying to reuse a single instance of PyTessBaseAPI to quickly recognize multiple images. I hope this is correct, creating a new PyTessBaseAPI every time is quite slow.

So I wrote a small test program but the results are very strange: the first call to GetUTF8Text is correct with a reasonable confidence of 78. I'm using a very simple image. The second one, on the same image, inserts an extra character(?) and the confidence is 5. From the third call, confidence is 95 and there are no more mistakes, even on different images.

It looks like it needs a couple of calls to warm up :)

But it gets weirder! If I start with another image, almost identical, the sequence is ok(74), small error(7), and from now on it's messed up, always small error(7), even if I later use the good image I used before :(

If a create a new PyTessBaseAPI every time, it works fine.

[tess_bind.py.zip](https://github.com/sirfz/tesserocr/files/1925533/tess_bind.py.zip)

Please see the attached images and script.

It makes no difference if I use PIL, SetImageBytes or use the filename.

$ tesseract --version
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.0

(I could not find a ppa for the 3.0.5.01, I'll try to build it tomorrow, but maybe it is not a tesseract problem).

$ uname -a
Linux 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

tesserocr              2.2.2      

BTW, is one instance of PyTessBaseAPI thread safe?

**Comment by lorenzob** [comment]
Hi sirfz, thanks for you answer. I'm building leptonica right now. 
Just one question, does the example works for you?

**Comment by lorenzob** [comment]
In the meantime I found a clue. I rebuilt everything and I have the same problem but I noticed that if I call:

api.Init(lang="eng")

before any call to GetUTF8Text then the problem is fixed. If I do this only once per instance I have this strange problem. I also have to call SetPageSegMode everytime or the setting is ignored.

This works, it is fast, so for me is a good workaround.

**Comment by sirfz** [comment]
I ran your script (slightly edited as I don't have cv2):

```python
import tesserocr
from tesserocr import PyTessBaseAPI

NUMBERS_LIST = "0123456789"
LETTERS_LIST = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
ALL_LIST = NUMBERS_LIST + LETTERS_LIST

api = None


def ocr_image(filename, is_number=False):

    global api

    if api is None:
        print("Load tesserocr bindings")
        api = PyTessBaseAPI(lang='eng+ita')

    white_list = NUMBERS_LIST if is_number else LETTERS_LIST
    api.SetVariable("tessedit_char_whitelist", white_list)
    api.SetImageFile(filename)

    # I need to set this every time or is ignored
    api.SetPageSegMode(tesserocr.PSM.SINGLE_WORD)

    text = api.GetUTF8Text()
    conf = api.AllWordConfidences()

    # api.End()
    # api.Clear()

    return text, conf


if __name__ == '__main__':
    import sys
    # import cv2

    filename = sys.argv[1]
    for i in range(10):
        print(ocr_image(filename, is_number=True))
    print('----------------------')
    filename = sys.argv[2]
    for i in range(10):
        print(ocr_image(filename, is_number=True))
```
And got consistent output throughout:

```bash
$ python tess_bind.py numbers-ok.png numbers-err.png
Load tesserocr bindings
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
----------------------
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
(u'6491330\n', [94])
```

Using Python 2 with Tesseract 4.0 with Tessdata 4.0 (latest tesserocr from master):

```python
>>> print tesserocr.tesseract_version()
tesseract 4.00.00alpha
 leptonica-1.74.4
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.1) : libpng 1.6.34 : libtiff 4.0.8 : zlib 1.2.11 : libwebp 0.6.0 : libopenjp2 2.2.0
```

**Comment by lorenzob** [comment]
Thanks. I'll try with 4.0 too and report back. You also get a much higher score than I do with my workaround (74). And the fact that you do not need my workaround means that something is probably still broken in my install.

My version now:

tesseract 3.05.01
 leptonica-1.75.3
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.6.20 : zlib 1.2

**Comment by sirfz** [comment]
I'm pretty sure that shouldn't happen with 3.05.01 as well (at least I never had that problem).

**Comment by lorenzob** [comment]
Can I ask you one more favor (even if this is quite likely a tesseract problem)?

I added these two lines to my script:

  th = api.GetThresholdedImage()
  th.save('th_tess_bind.png')

just before the api.GetUTF8Text() line. The saved output is this:

![th_tess_bind](https://user-images.githubusercontent.com/85481/39129750-8ff06d44-470b-11e8-8138-64fe4374cb73.png)

This does not look perfect to me, there is some small noise around the letters. It looks like jpeg artifacts but I'm sending in a pure binary PNG image.

Can you please check what kind of output you get when running this code?

Maybe tesseract does some compression in the GetThresholdedImage call but I find it unlikely.
