### ISSUE TITLE
linux compatibility ?

### ISSUE THREAD

**Issue by sandys** [sirfz/tesserocr#108]
hi guys,
I notice that the conda builds are only windows and the wheel releases on the github page are also windows only.

Is the linux support being deprioritized ? we typically depend on conda channels to make software available on our servers, and are concerned on why linux is being left to build-from-source for end users.
thanks!

**Comment by sirfz** [comment]
Not at all, Windows builds were created by efforts from people who need to use tesserocr on Windows.

I welcome contributions to create Linux wheels as well, which hasn't happened yet given how easy it is to install tesserocr on Linux (who are probably also the larger segment of tesserocr users).

**Comment by sandys** [comment]
@sirfz hope you dont mind me asking - which is the other way to install tesserocr on linux ? because compiling from source became too complex for me :(

should we use the build script as mentioned here ? https://travis-ci.org/sirfz/tesserocr/jobs/369765314

**Comment by Belval** [comment]
`pip install tesserocr` usually works for me

**Comment by sirfz** [comment]
What distribution are you using? All recent dists have at least 3.04 available in the package manager and a simple `pip install tesserocr` is enough to get you going (preferably with pkg-config installed to make it easier for the setup script to locate include and lib paths).

If you don't have 3.04+ available with your packager then following the [travis install steps](https://github.com/sirfz/tesserocr/blob/master/.travis.yml) should set you up.

**Comment by sandys** [comment]
Actually we package our applications inside docker. Usually if it is a
package that needs building then I need to make sure I install all the
dependencies beforehand ...Otherwise it will not find them because everyone
uses minimal images.

Even worse if we use Alpine images (which are the highest performance ).
Which is why I requested if it was possible to have wheels .

If not, I will have to replicate the Travis recipe in its entirety.

I'm unqualified to do it - but want to again mention : it would be a
godsend to have binary wheels.

**Comment by sirfz** [comment]
Checkout the new [travis pipeline](https://github.com/sirfz/tesserocr/blob/d3f1dc89e88be1b77f283281aa63dd51060f73d2/.travis.yml). It now downloads pre-built binaries of tesseract before installing tesserocr. You can do the same.
