### ISSUE TITLE
tesserocr.image_to_text(image) error

### ISSUE THREAD

**Issue by cdlwhm1217096231** [sirfz/tesserocr#111]
when I run 
image = Image.open('image.png')
print(tesserocr.image_to_text(image))
the following error will be find:
 print(tesserocr.image_to_text(image))
  File "tesserocr.pyx", line 2400, in tesserocr._tesserocr.image_to_text
RuntimeError: Failed to init API, possibly an invalid tessdata path: E:\Anaconda3.5\

please help me ,thank you!

**Comment by simonflueckiger** [comment]
Which version of tesseract did you install and on which os are you running it on? Did you download the according files from https://github.com/tesseract-ocr/tessdata and if yes, did you set your TESSDATA_PREFIX environment variable to the appropriate path (the location where your tessdata files are stored)?

**Comment by cdlwhm1217096231** [comment]
@simonflueckiger 
I install the version of tesseract  tesseract-ocr-setup-3.05.01.exe,tessdata is online download ,when I install tesseract. My computer is win7 64bits

**Comment by cdlwhm1217096231** [comment]
How to setting TESSDATA_PREFIX environment variable?,I can not find it.

**Comment by cdlwhm1217096231** [comment]
C:\Users\Administrator>tesseract -v
tesseract 3.05.01
 leptonica-1.74.1
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : li
.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0

**Comment by flip111** [comment]
> How to setting TESSDATA_PREFIX environment variable?

google for: how to set environment variables in windows

**Comment by cdlwhm1217096231** [comment]
I have finished tesserocr setting. thank you!

**Comment by flip111** [comment]
Can you close the issue ?

**Comment by cdlwhm1217096231** [comment]
close #111
