### ISSUE TITLE
SetVariable() has no effect

### ISSUE THREAD

**Issue by wolterlw** [sirfz/tesserocr#114]
trying to set load_freq_dawg and load_system_dawg to false
my exact code:
```python
api = PyTessBaseAPI(lang='ukr',psm=tesserocr.PSM.SINGLE_LINE)
api.SetVariable("load_system_dawg","0")
>>>True
api.SetVariable("load_freq_dawg","0")
>>>True
api.GetBoolVariable("load_system_dawg")
>>>True
api.GetBoolVariable("load_freq_dawg")
>>>True
```
tesseract version: 4.0.0-beta.1 built from repo clone
system: Debian 9

**Comment by sirfz** [comment]
I tried your code and faced the same issue, however when I try it with a different variable (i.e. `"classify_bln_numeric_mode"`), it worked as expected.

You might want to bring this up with the Tesseract devs as it has nothing to do with tesserocr.

**Comment by ing200086** [comment]
@wolterlw have you been able to solve this? I am running into the same issue, but coming up short. I also tried to load a config file, but this also seemed ineffective.

**Comment by mtrsk** [comment]
Can confirm, this is happening with `tesseract 4.0.0` on a debian container. I'm going to verify if `tesserocr` on the new `4.1` has the same issue.

**Comment by mlorenzo-alice** [comment]
Same issue here with `tesseract 4.1.1` and `tesserocr 2.5.1`

**Comment by mlorenzo-alice** [comment]
I have found in [tesseract doc](https://github.com/tesseract-ocr/tessdoc/blob/master/ControlParams.md) that `load_freq_dawg` and `load_system_dawg` are init only variables. This means they can not be set through TessBaseAPI::SetVariable.

This can only be done [through config files](https://stackoverflow.com/questions/50204628/tesseract-api-with-load-system-dawg-and-load-freq-dawg/50210308). 

Is there are planning for PyTessBaseAPI class to support init-only variables via config files or arguments? @sirfz 

As said in [tesseract doc](https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html#dictionaries-word-lists-and-patterns), disabling the dictionaries Tesseract uses should increase recognition and speed if most of your text isn't dictionary words.
