### ISSUE TITLE
Python 3.7 version

### ISSUE THREAD

**Issue by Link009** [sirfz/tesserocr#118]
I installed Python 3.7 and there is no version of tesserocr compatible with it. It would be awesome to have the wrapper available also with last Python version.

**Comment by sirfz** [comment]
Python 3.7 is still in development version and has not been released. You should be able to manually install tesserocr from source though.

**Comment by simonflueckiger** [comment]
@Link009 are we talking about windows or linux?

**Comment by Link009** [comment]
Hi
about Windows
