### ISSUE TITLE
build fails on osx

### ISSUE THREAD

**Issue by reubano** [sirfz/tesserocr#12]
```bash
$ pip install ./tesserocr --upgrade
Processing ./tesserocr
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/folders/1f/8hp6xg6j5wn8pzb94y56x4f00000gn/T/pip-kjLPF8-build/setup.py", line 6, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/1f/8hp6xg6j5wn8pzb94y56x4f00000gn/T/pip-kjLPF8-build/
```

`git bisect`

```bash
ff1c3c764269864c731c305a59e1d03a9a6ac821 is the first bad commit
commit ff1c3c764269864c731c305a59e1d03a9a6ac821
Author: FZ <iamfayez@gmail.com>
Date:   Sat May 21 20:10:04 2016 +0300

    setup now requires Cython and passes tesseract version as cython_compile_time_env

:100644 100644 3edde89bbaec3781147180d476778fb51ff15f6f 1153e1d0f3f30149cb0c98a419a4355e0b15e10a M	setup.py
:000000 100644 0000000000000000000000000000000000000000 0ffc837bfff77266e17c0f48bb0fe52bb1733df7 A	tesseractversion.pyx
:100644 000000 32375e79fcba5805a9654f036f32f0b224cdded6 0000000000000000000000000000000000000000 D	tesserocr.cpp
```

**Comment by sirfz** [comment]
I understand installing Cython is not an option in your case? Cython is required to generate the C++ file and based on the currently installed tesseract version, different source code is generated (to maintain compatibility with 3.04.00 while supporting new features in >= 3.04.01).

I can still bypass the Cython requirement (if it's not installed) by keeping different versions of the generated C++ source code and compiling the right one for your setup. I'll work on it and let you know.

**Comment by reubano** [comment]
The weird thing is I **have** `cython`

```bash
$ cython --version
Cython version 0.23.5
```

**Comment by sirfz** [comment]
Could [this](http://stackoverflow.com/questions/11108461/python-importerror-cython-distutils) be your problem?

**Comment by reubano** [comment]
Indeed! I installed `cython` via macports, but `python` is in the virtualenv and doesn't see it. `/opt/local/bin/python2 -c 'import Cython.Distutils'` works as expected.

**Comment by sirfz** [comment]
I guess initializing your virtualenv with `--system-site-packages` or installing Cython in your virtualenv should do the trick.
