### ISSUE TITLE
How to deal with tesseract LC_ALL=C limitation :(

### ISSUE THREAD

**Issue by lorenzob** [sirfz/tesserocr#122]
I just discovered that tesseract 4 currently works only with LC_ALL set to C.

https://github.com/tesseract-ocr/tesseract/wiki/4.0x-Common-Errors-and-Resolutions

If you don't do this you' get a segmentation fault as soon as you import tesserocr.

The problem is this: if I set this variable in this way I can no longer print utf-8 text on the console or I get this:

UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 0: ordinal not in range(128)

How do you deal with this problem when using tesserocr? Of course I can write my output to a file and other tricks to avoid this problem, but I'm looking for a clean solution, if any.

I realize this is not a tesserocr bug but it is a problem affecting any tesserocr user so maybe we can see if someone has a good solution for this.

**Comment by kyle-pena-nlp** [comment]
Not a solution to your problem per se, but if you include this line in a bash script prior to invoking Python:
LANG="C"

Then that LANG setting dissapears when the process opened by the bash script (and its child Python process) finishes.

In terms of fixing your specific problem with broken UnicdeoEncodeError, maybe do at the top of your Python script?

import locale
locale.setlocale(locale.LC_ALL, '')

**Comment by letmerecall** [comment]
Did you get any work around? I am facing the same issue.
What you meant by "I can write my output to a file"? Here I want to get a tsv output.

**Comment by lorenzob** [comment]
The only workaround I've found is to "sanitize" my text using 

`text = unidecode.unidecode(text)`

This works, but you lose any non-ascii character (replaced by the ascii equivalent).

Initially I thought the problem was related to console output, where the console, with this LC_ALL setting, was not able to display the symbol. But it seems it's a general problem as soon as you "touch" the string. You can access the raw bytes tough, so a base64 encoding should be an option.

**Comment by letmerecall** [comment]
Actually, I need to get the bounding boxes of those words and tsv seems the only option. The moment I call tsv ( api.GetTSVText(0) ) it gives me the error you mentioned. Do you have any solution for this type of problem?
Appreciate your views!

**Comment by lorenzob** [comment]
Use r.BoundingBox(RIL.SYMBOL) to get the box directly. See the iterator example on the main page of this project.

**Comment by amitbsconcept** [comment]
Well, even i was experimenting around with same scenario - i found a simpler solution some place - 
`export PYTHONIOENCODING="UTF-8"`

This did the trick for me - it started printing actual symbols instead of  UTF-8 chars.
Hope it works out for you too.

**Comment by lorenzob** [comment]
It works!! Thank you very much for taking the time for posting this :) 

I'm closing this, I think this is a perfectly reasonable solution.

**Comment by lorenzob** [comment]
It works!! Thank you very much for taking the time for posting this :) 

I'm closing this, I think this is a perfectly reasonable solution.
