### ISSUE TITLE
when image path to SetImageFile() contains Chinese characters, RuntimeError: Error reading image

### ISSUE THREAD

**Issue by redstoneleo** [sirfz/tesserocr#126]
when image path passing to `SetImageFile()` contains Chinese characters, just through 
`RuntimeError: Error reading image`

**Comment by sirfz** [comment]
Reading an image has nothing to do with the language of text within that image. Closing for insufficient info.

**Comment by redstoneleo** [comment]
Sorry, I mean image path containing Chinese characters, like `D:\BaiduYunDownload\编程\Python\Project\EngkuDict\ocr img\112.jpg` would cause the problem
