### ISSUE TITLE
Set value for config variables using helper functions

### ISSUE THREAD

**Issue by engineerk** [sirfz/tesserocr#128]
I am currently using one of help functions, image_to_text(), with threading. It gave me to reduce the time for processing greatly. Thanks!

For setting config variables, I found an API function. However, I couldn't find a way for help functions. Can you tell me how to set config variables with using image_to_text()? e.g. tessedit_char_whitelist = '...'

**Comment by sirfz** [comment]
You can use the API directly instead:

```python
with PyTessBaseAPI(...) as api:
    api.SetVariable(....)
    api.SetImage(...)
    text = api.GetUTF8Text()
```

**Comment by engineerk** [comment]
Thank you!
