### ISSUE TITLE
Python versions supported

### ISSUE THREAD

**Issue by amitdo** [sirfz/tesserocr#13]
It seems that only Python 2.7 is supported
https://pypi.python.org/pypi/tesserocr/2.0.0

Any plan to support Python 3.x in the near future?

I suggest you to add a paragraph to the README that declares which Python versions are supported.

**Comment by sirfz** [comment]
The supported Python version (2.7) is specified in the setup classifiers which also appear on pypi under categories.

Python 3.x support should be fairly simple as I don't use any py2-specific semantics (as far as I'm concerned). Only thing that might need be to be addressed is string handling. Did you try it with Python 3? If not, it's worth giving it a shot to see how that goes.

I'll also work on it when I have time and make the necessary changes to support Python 3.

**Comment by amitdo** [comment]
OK. Thanks!

I didn't try it yet. I have other priorities right now. Maybe in a few months from now...
Just wanted to know about the Python 3 support status.

**Comment by amitdo** [comment]
BTW, I added 'tesserocr' to the Tesseract [AddOns](https://github.com/tesseract-ocr/tesseract/wiki/AddOns#tesseract-wrappers) wiki page, after @reubano mentioned it in https://github.com/tesseract-ocr/tesseract/issues/326 a few days ago.

**Comment by sirfz** [comment]
Awesome thanks for that! I'll let you know once it's been tested and working with Python 3 :+1:

**Comment by sirfz** [comment]
Just as an update, Python 3 is now supported and the latest version [2.1.1](https://pypi.python.org/pypi/tesserocr/2.1.1) has been published on pypi :)

**Comment by amitdo** [comment]
Great! Thanks.
:-)
