### ISSUE TITLE
How to iterate inside an iterator level

### ISSUE THREAD

**Issue by shreyansh26** [sirfz/tesserocr#134]
I have some problems with the following code snippet. I am extracting text from the PARA level, but then since I want to identify superscripts as well, I am going into word level for that PARA. However the loop breaks after the first PARA itself. How to go about it?
```
api.SetImage(resized_patch)
api.Recognize()
# The level on which extraction is to be done. Choices - BLOCK, TEXTLINE, WORD, SYMBOL
level = RIL.PARA
# Get the iterator
iterator = api.GetIterator()
word_attr = []
for r in iterate_level(iterator, level):
	try:
		# Get text and font attributes of the current patch
		text = r.GetUTF8Text(level)
		font_attr = r.WordFontAttributes()

		for s in iterate_level(r, RIL.SYMBOL):
			print("SYMBOL: ", s.GetUTF8Text(RIL.SYMBOL))
			print("IsSuperscript: ", s.SymbolIsSuperscript())
		
		# print(font_attr)
	except:
		text = None
		font_attr = None
```

**Comment by sirfz** [comment]
Take a look at PageIterator's [IsAtFinalElement](https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx#L496) API method. You can try iterating manually while checking this condition, something like:

```python
while not r.IsAtFinalElement(RIL.PARA, RIL.SYMBOL):
    r.Next(RIL.SYMBOL)
```
Just an idea. You may also find `IsAtBeginningOf` useful.

**Comment by prizmatic** [comment]
The issue is somewhat related, but is it possible to copy PyResultInterator instance (ResultIterator class is copy constructable in the original)? I check for words' confidence (word level) and then want to go to character level in separate iterator in case confidence is not sufficient. Or probably there is an efficient alternative?

**Comment by bertsky** [comment]
> I check for words' confidence (word level) and then want to go to character level in separate iterator in case confidence is not sufficient.

You don't have to. You can use the same result iterator at the lower level, too. It will advance the `RIL.WORD` level when you have called `Next(RIL.SYMOL)` on all its constituent characters. That works across all levels (except ChoiceIterator), even multiple at once.
