### ISSUE TITLE
Can't Import tesserocr after installing tesseract 4.0.0-beta.3 MacOS

### ISSUE THREAD

**Issue by raudipra** [sirfz/tesserocr#135]
Hi there I have a problem here, I've been using tesserocr with tesseract 3.0.5 for last 2 weeks and it worked fine. Then I upgrade my tesseract into 4.0.0 beta because the result is far better than 3.0.5, but the consequence is I can't use it with tesserocr.

Here is my error message everytime I try to import tesserocr
<img width="564" alt="screen shot 2018-07-18 at 19 16 27" src="https://user-images.githubusercontent.com/19368538/42880640-26bab80a-8abf-11e8-9a5a-5e47b7c32ffd.png">

I install tesseract 4.0.0 using brew and uninstall the previous version (3.0.5)
I install tesserocr using pip install tesserocr
I am using python 2.7.13
I am using MacOS High Sierra

I am very thankful to you because your library is very helpful to me, hopefully you can help me with my issue

Thank you :)

**Comment by chandangm** [comment]
I have the same issue, I tried downloading libtesseract.3.dylib and copied it to the path where it was searching. this is the error I'm getting now. any help is appreciated. 


```
ImportError: dlopen(/Users/chandangm/anaconda3/lib/python3.6/site-packages/tesserocr.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/libgif.7.dylib
  Referenced from: /usr/local/opt/tesseract/lib/libtesseract.3.dylib
  Reason: image not found
```
