### ISSUE TITLE
pip install error (x86_64-linux-gnu-gcc) on ubuntu16.04

### ISSUE THREAD

**Issue by kkurni** [sirfz/tesserocr#150]
I am getting error when "Pip3 install tesserocr" on my ubuntu16.04 machine/

> pip3 install tesseractocr
> Collecting tesseractocr
>   Could not find a version that satisfies the requirement tesseractocr (from versions: )
> No matching distribution found for tesseractocr
> root@70d41ee0a519:/tmp# pip3 install tesserocr
> Collecting tesserocr
>   Downloading https://files.pythonhosted.org/packages/f8/6d/4e81e041f33a4419e59edcb1dbdf3c56e9393f60f5ef531381bd67a1339b/tesserocr-2.3.1.tar.gz (54kB)
>     100% |################################| 61kB 3.7MB/s
> Building wheels for collected packages: tesserocr
>   Running setup.py bdist_wheel for tesserocr ... error
>   Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ocheer6s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3he8anm_ --python-tag cp34:
>   Supporting tesseract v3.04.01
>   Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'include_dirs': ['/usr/include'], 'cython_compile_time_env': {'TESSERACT_VERSION': 197633}}
>   running bdist_wheel
>   running build
>   running build_ext
>   building 'tesserocr' extension
>   creating build
>   creating build/temp.linux-x86_64-3.4
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.4m -c tesserocr.cpp -o build/temp.linux-x86_64-3.4/tesserocr.o
>   cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
>   tesserocr.cpp:38:20: fatal error: Python.h: No such file or directory
>   compilation terminated.
>   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
>   ----------------------------------------
>   Failed building wheel for tesserocr
>   Running setup.py clean for tesserocr
> Failed to build tesserocr
> Installing collected packages: tesserocr
>   Running setup.py install for tesserocr ... error
>     Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ocheer6s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-avohldt9/install-record.txt --single-version-externally-managed --compile:
>     Supporting tesseract v3.04.01
>     Configs from pkg-config: {'cython_compile_time_env': {'TESSERACT_VERSION': 197633}, 'libraries': ['tesseract', 'lept'], 'include_dirs': ['/usr/include']}
>     running install
>     running build
>     running build_ext
>     building 'tesserocr' extension
>     creating build
>     creating build/temp.linux-x86_64-3.4
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.4m -c tesserocr.cpp -o build/temp.linux-x86_64-3.4/tesserocr.o
>     cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
>     tesserocr.cpp:38:20: fatal error: Python.h: No such file or directory
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
>     ----------------------------------------
> Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ocheer6s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-avohldt9/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ocheer6s/tesserocr/

Here is my tesseract version

> tesseract 3.04.01
>  leptonica-1.73
>   libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2

Any hints?

Thanks

**Comment by sirfz** [comment]
> tesserocr.cpp:38:20: fatal error: Python.h: No such file or directory

Did you install python-dev?

**Comment by kkurni** [comment]
Yes, the python dev is the issue.

Thanks

**Comment by Sandeepdezno** [comment]
It worked For me:
`sudo apt-get install tesseract-ocr`
