### ISSUE TITLE
Segmentation fault with tessdata_fast data

### ISSUE THREAD

**Issue by suyog250592** [sirfz/tesserocr#151]
Hi,
If I use tesserocr along with tesseract_best data (LSTM) it works fine, but if I try to use the same with tessdata_fast model, it gives Segmentation fault. Do these models not supported?
tesseract 4.0.0-beta.1
leptonica-1.74.4
Pillow -  5.2.0

**Comment by sirfz** [comment]
That's a tesseract-related question rather than tesserocr.
