### ISSUE TITLE
'NoneType' object is not iterable issue when iterate bounding box 

### ISSUE THREAD

**Issue by kkurni** [sirfz/tesserocr#152]
**Environment**
Tesseract Version: 3.5.0 and 4.0
Platform: mac & ubuntu 18.04
**Current Behavior:**
I am iterating over recognize api as suggested here. "Result iterator example"
https://github.com/tesseract-ocr/tesseract/wiki/APIExample

it seems we do before calling next. If I am calling next first, it will skip over the first detections.

Unfortunately when I get this error,
'NoneType' object is not iterable issue
When there is no detection.

Here is the code in python-tesserocr
if (iterator != None):
next = True
while (next):
x,y,right,bottom = iterator.BoundingBox(level)

        next = iterator.Next(level)
it throws an error on iterator.BoundingBox saying that the iterator is empty.

If I call "next = iterator.Next(level)" first, it avoids that error, but it also skip over the first detection

**Expected Behavior:**
It should not throw an exception, or I can call HasNext API

Is there any HasNext API that I can call?

Here attach the image that I use, to reproduce. 
Just whitespace
![white-space](https://user-images.githubusercontent.com/698547/45849852-8c796280-bce8-11e8-9b06-196d8909d297.png)

Thanks

**Comment by sirfz** [comment]
You can use the `iterate_level` helper function for that. Check the [classifier choices iterator example](https://github.com/sirfz/tesserocr#iterator-over-the-classifier-choices-for-a-single-symbol).

`iterate_level` is basically a generator function:

```python
def iterate_level(iterator, PageIteratorLevel level):
    """Helper generator function to iterate a :class:`PyPageIterator`
    level.

    Args:
        iterator: Instance of :class:`PyPageIterator`
        level: Page iterator level :class:`RIL`
    """
    yield iterator
    while iterator.Next(level):
        yield iterator
```

**Comment by kkurni** [comment]
I get the different issue with using iterator_level
RuntimeError: No text returned

Here is the error
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-b1f028f65b31> in <module>()
     37     level = RIL.WORD
     38     for r in iterate_level(ri, level):
---> 39         symbol = r.GetUTF8Text(level)  # r == ri
     40         conf = r.Confidence(level)
     41 

tesserocr.pyx in tesserocr.PyLTRResultIterator.GetUTF8Text()

RuntimeError: No text returned
`

Here is the code
`
with PyTessBaseAPI() as api:
    api.SetImageFile(file_name)
    api.SetRectangle(0, 0, width, height)
    api.Recognize(0)

    ri = api.GetIterator()
    level = RIL.WORD
    for r in iterate_level(ri, level):
        symbol = r.GetUTF8Text(level)  # r == ri
        conf = r.Confidence(level)
        
        x, y, right, bottom = r.BoundingBox(level)
        
        if symbol:
            print (u'symbol "{}", conf: {}, bb {}'.format(symbol, conf, x))
        
        print ('---------------------------------------------')

`

**Comment by kkurni** [comment]
Here is the image, If I just put an empty whitespace.
![white-space](https://user-images.githubusercontent.com/698547/45849852-8c796280-bce8-11e8-9b06-196d8909d297.png)

**Comment by sirfz** [comment]
The documentation states that the method raises `RuntimeError` when no text is returned by the tesseract API.
