### ISSUE TITLE
Segmentation fault on GetUTF8Text()

### ISSUE THREAD

**Issue by openedhardware** [sirfz/tesserocr#16]
Hi.
Thanks for your previous messages.

I have just tested with your image file again.

Unfortunately, it says "Segmentation fault(core dumped)" after finding 12 textlines.
Error occured in `ocrResult = api.GetUTF8Text()` line.

Seems like I have not installed tesserocr properly.

I am eager to hear from you soon.
Thanks.

**Comment by sirfz** [comment]
What's the version of tesseract you installed?

```python
import tesserocr

print tesserocr.tesseract_version()
```

**Comment by openedhardware** [comment]
tesseract 3.05.00dev
leptonica-1.73
libjpeg 8d(libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8


Thanks.

**Comment by sirfz** [comment]
Can you try installing a stable version of tesseract (i.e. 3.04.00 or 3.04.01)?

**Comment by openedhardware** [comment]
OK
Let me try now.

**Comment by openedhardware** [comment]
Well, they say "The latest stable version is 3.04.01, released in February 2016"
Where can I find it?

**Comment by sirfz** [comment]
At tesseract-ocr's Github releases page: https://github.com/tesseract-ocr/tesseract/releases

**Comment by openedhardware** [comment]
Sorry, just found and installing now...

**Comment by openedhardware** [comment]
Hi.
I have tried to install 3.04.00 and 3.04.01 with leptonica 1.73 and 1.72
And failed to compile tesseract every time.
Have seen the same issue on the tesseract repo but there is no way of fixing it.
https://github.com/tesseract-ocr/tesseract/issues/41

Do you have any experience with it?
Thanks.

**Comment by sirfz** [comment]
Actually I'm using tesseract v3.04.00 with leptonica 1.72

```
tesseract 3.04.00
 leptonica-1.72
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.51 : libtiff 4.0.3 : zlib 1.2.8
```

As far as I'm concerned there shouldn't be any problem compiling it or v3.04.01 following this guide: https://github.com/tesseract-ocr/tesseract/wiki/Compiling#linux--other-unices

**Comment by sirfz** [comment]
Try completely removing tesseract and leptonica then re-compile.
