### ISSUE TITLE
Preserve interword spaces

### ISSUE THREAD

**Issue by lopes05** [sirfz/tesserocr#163]
Hi, is there a way to use the preserve_interword_spaces with PyTessBaseAPI? If so, how can I do it?

**Comment by abhishek-27** [comment]
Yes you can use it like this:

            

```
with PyTessBaseAPI(lang='eng', oem=OEM.LSTM_ONLY, psm=PSM.SINGLE_BLOCK,
                path=os.environ["TESSDATA_PREFIX"]) as api:
                api.SetVariable('preserve_interword_spaces', '1')
```

**Comment by erotavlas** [comment]
I'm getting the error 

> "error": "name 'OEM' is not defined",

it cannot find OEM or PSM

Is there another way to set these parameters? Maybe in setVariable function?
