### ISSUE TITLE
GetChoiceIterator function is providing only a single character as output

### ISSUE THREAD

**Issue by charchika19** [sirfz/tesserocr#166]
![screenshot from 2018-12-06 01-05-57](https://user-images.githubusercontent.com/29430181/49538381-5f098180-f8f3-11e8-885f-e58c116eef9e.png)
![screenshot from 2018-12-06 01-08-04](https://user-images.githubusercontent.com/29430181/49538404-6cbf0700-f8f3-11e8-9f06-d46a17829b79.png)
![frame413_anvaya2](https://user-images.githubusercontent.com/29430181/49538423-79435f80-f8f3-11e8-8ce2-419976d589d6.jpg)
The screenshot of code and output is attached, i am trying to print all choices for each character that tesseract is able to detect, but I am getting a single possibility for each position as output.

**Comment by bertsky** [comment]
Yes, this only gives the first (best) choice with LSTM models. If you load a language/model from Tesseract 3, this will yield all alternatives, though. 

@noahmetzger told me, the old choice iterator would soon be populated with data from the LSTM beam search, too.

Meanwhile, you can try `GetBestLSTMSymbolChoices` with `lstm_choice_mode` set to 2, also [introduced](https://github.com/tesseract-ocr/tesseract/pull/1998) with 4.0, and for LSTMs specifically.

**Comment by Shaunlipy** [comment]
Hi, I'm wondering where do I set the `lstm_choice_mode` in the code?

I tried `with PyTessBaseAPI(oem=1, lstm_choice_mode=2) as api:` but failed.

**Comment by bertsky** [comment]
> where do I set the `lstm_choice_mode` in the code?

It's one of many parameters you can set in Tesseract (see `tesseract --print-parameters`). In Tesseract CLI you use `-c lstm_choice_mode=2`, in the Python API you do `tessapi.SetVariable('lstm_choice_mode', '2')`

**Comment by Shaunlipy** [comment]
Hi, Thanks for your prompt reply. 

I tried `tessapi.SetVariable('lstm_choice_mode', '2') `, but the result is still the same as **charchika19** shows, only the top1 choice. 

However, if I use the c++ example code provided in tesseract example, it shows multiple choices. Is there anything else I need to modify for it to work?

**Comment by bertsky** [comment]
@Shaunlipy I don't know which example you refer to, but writing a Python analogue for C++ code most API usage should work just the same.

BTW https://tesseract-ocr.github.io/tessdoc/APIExample.html#example-of-iterator-over-the-classifier-choices-for-a-single-symbol uses the wrong parameter (it's should be `lstm_choice_mode`), and https://tesseract-ocr.github.io/tessdoc/APIExample.html#example-to-get-confidence-for-alternative-symbol-choices-per-character-for-lstm uses a different API which does not work in general. Feel free to open an issue about that.

Also, there's a second related parameter, `lstm_choice_iterations` which you can set higher if you want to squeeze out more alternatives. Not sure whether probabilites will still be useful, though.

**Comment by Shaunlipy** [comment]
I'm using your code like`
from __future__ import print_function

from tesserocr import PyTessBaseAPI, RIL, iterate_level

with PyTessBaseAPI(path='./trained_data/.', lang='eng+chi_sim',
                       psm=13, oem=1) as api:
    api.SetImageFile('../5.png')
    api.SetVariable("lstm_choice_mode", "2")
    api.SetVariable("save_blob_choices", "T")
    api.SetVariable("lstm_choice_iterations", "10")
    # api.SetRectangle(10, 10, 200, 200)
    api.Recognize()

    ri = api.GetIterator()
    level = RIL.SYMBOL
    for r in iterate_level(ri, level):
        symbol = r.GetUTF8Text(level)  # r == ri
        conf = r.Confidence(level)
        if symbol:
            print(u'symbol {}, conf: {}'.format(symbol, conf), end='')
        indent = False
        ci = r.GetChoiceIterator()
        for c in ci:
            if indent:
                print('\t\t ', end='')
            print('\t- ', end='')
            choice = c.GetUTF8Text()  # c == ci
            print(u'{} conf: {}'.format(choice, c.Confidence()))
            indent = True
        print('---------------------------------------------')
`

But the output is still single prediction.

Btw, yeah the c++ example I was referring to was > Example to get confidence for alternative symbol choices per character for LSTM

**Comment by bertsky** [comment]
Well if `ChoiceIterator` _still_ does not yield alternatives, but `GetBestLSTMSymbolChoices` does, then that's a bug (in Tesseract itself).

Please:
- check that tesserocr uses the same version you used to run the C++ example (by querying `tesserocr.tesseract_version()`)
- build the other C++ example as well (just replacing `save_blob_choices=T` with `lstm_choice_mode=2`), run it and check that it does (not) show any alternative choices.

**Comment by Shaunlipy** [comment]
`tesseract 4.1.1-rc2-21-gf4ef
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1`

I tested the other c++ example. Yeah, the `ChoiceIterator` only gives the top1 prediction. 

Another problem I encounter with the `GetBestLSTMSymbolChoices` example is: it won't yield any results if I put multiple languages `lang='eng+chi_sim'` in `init`. However, if I init with just one language, both `eng` and `chi_sim` works.

**Comment by Mar2ck** [comment]
I was also having this problem of `ChoiceIterator` only returning one value with Tesseract 4.1.1. `GetBestLSTMSymbolChoices` would give multiple results but none of them were even remotely close to being accurate so it was practically useless.

I can confirm though that after manually compiling Tesseract 5.0.0-rc1 and reinstalling tesserocr, `ChoiceIterator` now outputs multiple options for each symbol and those alternate options are actually close to what the symbol looks look. `GetBestLSTMSymbolChoices` also works properly now and gives the same results as `ChoiceIterator`
