### ISSUE TITLE
DetectOrientationScript method is not working

### ISSUE THREAD

**Issue by Parthiv20** [sirfz/tesserocr#171]
I am trying to get orientation, orientation confidence, script and script confidence of an image. To get these values i used api.DetectOrientationScript() method. But it always gives Segmentation fault (core dumped) error. I followed the script specified on tesserocr readme (https://github.com/sirfz/tesserocr). 

My system configs:
tesseract 4.0.0-beta.1
tesserocr==2.3.1
Ubuntu 18.04.1 LTS

**Comment by bertsky** [comment]
Maybe your Tesseract installation does not include `osd.traineddata` in tessdata path. Do you have the system package `tesseract-ocr-osd` installed?

**Comment by grandkarabas** [comment]
Actually have the same system configs except `tesserocr==2.5.1` and the same problem. @Parthiv20 did you find the solution? I have `tesseract-ocr-osd` installed.

**Comment by grandkarabas** [comment]
With [release-4.1.1](https://github.com/tesseract-ocr/tesseract/releases/tag/4.1.1) version this problem disappeared.

**Comment by davidb1** [comment]
On **v5.0.0-alpha.20200328** only `AnalyseLayout()` seems to work, `DetectOS` and `DetectOrientationScript` return `None`

**Comment by sirfz** [comment]
Yes both functions set the image to process.

**Comment by davidb1** [comment]
But do they only work with `SetImageFile`?

**Comment by sirfz** [comment]
`SetImage` and `SetImageFile` serve exactly the same purpose (loading an image into the tesseract API instance) and have no relation to the functionality of other API methods. v5 is still in alpha which might be the reason why some API aren't working yet.
