### ISSUE TITLE
How can I set tessedit_char_whitelist

### ISSUE THREAD

**Issue by everlose** [sirfz/tesserocr#174]
I only hope to recognize digit from an image。I write follow code without much effect

```
import tesserocr
api = tesserocr.PyTessBaseAPI()
api.SetVariable("tessedit_char_whitelist", "0123456789");
```

**Comment by sirfz** [comment]
This is more of a tesseract-specific question, you'd have to refer to tesseract's API documentation on how this works.

**Comment by mzeimet** [comment]
if you're using tesseract v4 (like me), i'll save you some time: whitelists are not supported (yet) https://github.com/tesseract-ocr/tesseract/issues/751

**Comment by aspenlin** [comment]
tesseract whitelist is supported now if you build from the source. It works for me. But I'm also wondering how to set that through tesserocr.

**Comment by aspenlin** [comment]
I guess you were having problem because at that time the whitelist was not supported by tesseract 4. I just tried it now works with tesserocr too using your command above.

**Comment by sanitha-studio** [comment]
I am using tesseract 4.1.0 and whitelist works for me with pytesseract:

**custom_config = r'-c tessedit_char_whitelist=abcd --psm 6'
print(pytesseract.image_to_string(img, config=custom_config))**

But it is NOT working with tesserocr:

**with PyTessBaseAPI(psm=PSM.SINGLE_COLUMN, oem=OEM.LSTM_ONLY) as api:
    api.SetImage(img)
    api.SetVariable("tessedit_char_whitelist", "abcd");
    api.Recognize()
    print(api.GetUTF8Text())**

Even I have tried with config file.Still not working with tesserocr
