### ISSUE TITLE
Not supporting Python 3?

### ISSUE THREAD

**Issue by hspoon52** [sirfz/tesserocr#18]
i got error when i run the code

from tesserocr import PyTessBaseAPI

print(tesserocr.tesseract_version())  # print tesseract-ocr version
print(tesserocr.get_languages() )

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-117-10544beafd4f> in <module>()
----> 1 from tesserocr import PyTessBaseAPI
      2 
      3 
      4 print(tesserocr.tesseract_version())  # print tesseract-ocr version

/home/parallels/tesserocr/tesserocr/tesserocr.pyx in init tesserocr (tesserocr.cpp:22946)()
     42 cdef unicode _abs_path = abspath(join(_api.GetDatapath(), os.pardir)) + os.sep
     43 cdef unicode _lang_s = _api.GetInitLanguagesAsString()
---> 44 cdef cchar_t *_DEFAULT_PATH = _abs_path
     45 cdef cchar_t *_DEFAULT_LANG = _lang_s
     46 _api.End()

TypeError: expected bytes, str found

**Comment by sirfz** [comment]
Looks like you're using an outdated version of tesserocr, please update to the latest stable v2.1.2 and report back if you still have problems or not.

**Comment by hspoon52** [comment]
Good! no problem after i update it :+1:  Thanks
