### ISSUE TITLE
how to get .tsv result

### ISSUE THREAD

**Issue by aspenlin** [sirfz/tesserocr#183]
With tesseract command line, we can get .pdf or .hocr or .tsv file apart from .txt result by passing in a config file, can we get these results in tesserocr?

**Comment by sirfz** [comment]
You should be able to use the same APIs that the tesseract cli uses. I'm not sure what you want exactly but you can look at the `ReadConfigFile`, `SetVariable`, `GetHOCRText`, `GetTSVText`, `ProcessPages` methods.

**Comment by aspenlin** [comment]
Thanks for your reply. What I want is for tesserocr to output and save a
.tsv file. This can be done if I run tesseract from the terminal and use
the configuration file tsv. The result is different from GetTSVText. Using
ProcessPages I did get .pdf file, but it seems it couldn't render a .tsv
file. Anyways thanks for your help.

**Comment by bertsky** [comment]
> The result is different from GetTSVText

That's true, but the difference is small: it's just the document "preamble" that's missing:
```C++
"level\tpage_num\tblock_num\tpar_num\tline_num\tword_"
"num\tleft\ttop\twidth\theight\tconf\ttext\n"
```

You should be able to get the typical CLI behaviour of rendering to output files by using `ProcessPage` / `ProcessPages` after calling `ReadConfigFile('tsv')` and `ReadConfigFile('pdf')` etc. (These refer to filenames under `/usr/local/share/tessdata/configs` or similar.)

**Comment by mineshmathew** [comment]
`with PyTessBaseAPI(psm=PSM.AUTO, oem=OEM.LSTM_ONLY, lang="eng") as api:

    api.SetImageFile(image_name)
    api.Recognize()

    print (api.GetTSVText(0)) # for first page`
