### ISSUE TITLE
error while importing  "from tesserocr import pytessbaseAPI"

### ISSUE THREAD

**Issue by Yuhannakapali** [sirfz/tesserocr#186]
when I try to  " from tesserocr import PyTessBaseAPI, RIL"

I receive an error saying 
ImportError: libtesseract.so.3: cannot open shared object file: No such file or directory

any help would be helpfull

**Comment by bertsky** [comment]
You have been building/installing tesserocr against an outdated libtesseract, which is not installed anymore/properly. It should pull in libtesseract.so.4 (stable) or libtesseract.so.5 (development). Try removing/uninstalling your libtesseract-dev (or do `make uninstall` in your Tesseract source tree), then installing it again.
