### ISSUE TITLE
error trying to use GetBestLSTMSymbolChoices

### ISSUE THREAD

**Issue by arturcuringa** [sirfz/tesserocr#187]
I'm trying to use GetBestLSTMSymbolChoices and getting this error:
`AttributeError: 'tesserocr.PyResultIterator' object has no attribute 'GetBestLSTMSymbolChoices'`

I'm using Ubuntu 18.04.2 LTS and tried to install tesseract 4.1, update leptonica, without solving this issue.
 I need to find a way to get the rank of characters confidence for each symbol in the predicted word and these seems the only way to do it.

**Comment by sirfz** [comment]
It looks like you're not compiled against tesseract v4+, you can check by calling `tesserocr.tesseract_version()`. You'll have to re-install tesserocr after updating tesseract.

**Comment by arturcuringa** [comment]
Indeed the Tesseract version pointed by the `tesserocr.tesseract_version()` is different, here I got :
```
tesserocr.tesseract_version()
'tesseract 4.0.0-beta.1\n leptonica-1.75.3\n  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.5.2 : libopenjp2 2.3.0\n'
```

but running `tesseract - v ` I get a different result: 
```
tesseract 4.1.0
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
```

Also, can I make `tesserocr` point to a different tesseract path?

**Comment by sirfz** [comment]
You have to recompile tesserocr against the desired version of tesseract. Check the [installation giude](https://github.com/sirfz/tesserocr#installation) for examples of overriding compilation parameters.
