### ISSUE TITLE
How to do Threading Properly?

### ISSUE THREAD

**Issue by jon-sch** [sirfz/tesserocr#191]
Hi @sirfz,

could you share an example how to properly use multithreading? For me sequentially calling the tesseract API from the main thread is consistently the fastest, but I am not sure if I am missing something. Below you can find my "benchmark". I get, for instance:

> [SEQUENTIAL] ocr for 4 images took 1.512s
> [THREADED] ocr for 4 images took 1.574s
> [THREADED2] ocr for 4 images took 1.663s

I was not expecting a linear speed up, but some speedup...

```python
# -*- coding: utf-8 -*-

import locale
import time
import threading
import os

locale.setlocale(locale.LC_ALL, "C")

import cv2 as cv
import numpy as np
from PIL import Image as PIL_Image
from tesserocr import PyTessBaseAPI, PSM, image_to_text


class TesseractInstance(object):

    PSM_OSD_ONLY = PSM.OSD_ONLY
    PSM_AUTO_OSD = PSM.AUTO_OSD
    PSM_AUTO_ONLY = PSM.AUTO_ONLY
    PSM_AUTO = PSM.AUTO
    PSM_SINGLE_COLUMN = PSM.SINGLE_COLUMN
    PSM_SINGLE_BLOCK_VERT_TEXT = PSM.SINGLE_BLOCK_VERT_TEXT
    PSM_SINGLE_BLOCK = PSM.SINGLE_BLOCK
    PSM_SINGLE_LINE = PSM.SINGLE_LINE
    PSM_SINGLE_WORD = PSM.SINGLE_WORD
    PSM_CIRCLE_WORD = PSM.CIRCLE_WORD
    PSM_SINGLE_CHAR = PSM.SINGLE_CHAR
    PSM_SPARSE_TEXT = PSM.SPARSE_TEXT
    PSM_SPARSE_TEXT_OSD = PSM.SPARSE_TEXT_OSD
    PSM_RAW_LINE = PSM.RAW_LINE
    PSM_COUNT = PSM.COUNT

    def __init__(self, lang="eng"):
        if "TESSDATA_PREFIX" not in os.environ:
            raise RuntimeError("TESSDATA_PREFIX not set")
        self.api = PyTessBaseAPI(lang=lang)

    def __del__(self):
        self.api.End()

    def image_to_text(self, im: np.ndarray, psm=PSM_AUTO):
        if len(im.shape) != 2:
            raise RuntimeError("Expected grayscale image")
        if im.dtype != np.uint8:
            raise RuntimeError("Image must be of type np.uint8")

        self.api.SetPageSegMode(psm)
        self.api.SetImage(PIL_Image.fromarray(im))
        return self.api.GetUTF8Text()


def random_images(width, height, count):
    return [(255 * np.random.uniform(size=[height, width]) > 100).astype(np.uint8) for _ in range(count)]


def test_sequential(ims):
    instance = TesseractInstance()

    t0 = time.time()
    for im in ims:
        instance.image_to_text(im, TesseractInstance.PSM_SINGLE_BLOCK)
    dt = time.time() - t0

    print(f"[SEQUENTIAL] ocr for {len(ims)} images took {dt:.3f}s")


def test_threaded(ims):
    threads = []

    for im in ims:
        instance = TesseractInstance()
        threads.append(threading.Thread(
            target=instance.image_to_text,
            kwargs={"im": im, "psm": TesseractInstance.PSM_SINGLE_BLOCK})
        )

    t0 = time.time()
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    dt = time.time() - t0

    print(f"[THREADED] ocr for {len(ims)} images took {dt:.3f}s")


def test_threaded2(ims):
    threads = []

    for im in ims:
        threads.append(threading.Thread(
            target=image_to_text,
            kwargs={"image": PIL_Image.fromarray(im), "psm": TesseractInstance.PSM_SINGLE_BLOCK})
        )

    t0 = time.time()
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    dt = time.time() - t0

    print(f"[THREADED2] ocr for {len(ims)} images took {dt:.3f}s")


if __name__ == "__main__":
    np.random.seed(123)
    ims = random_images(400, 200, 4)

    test_sequential(ims)
    test_threaded(ims)
    test_threaded2(ims)

    # cv.imshow("waddup?", ims[0])
    # cv.waitKey()

```

**Comment by DeliciousHair** [comment]
Have you compiled Tesseract to run on a single thread? If you're using the default build, then wrapping the threading via python will have no impact; from [the tesseract-ocr wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation):

> 
>## Release Builds for Mass Production
>
>The default build creates a Tesseract executable which is fine for processing of single images. Tesseract then uses 4 CPU cores to get an OCR result as fast as possible.
>
>For mass production with hundreds or thousands of images that default is bad because the multi threaded execution has a very large overhead. It is better to run single threaded instances of Tesseract, so that every available CPU core will process a different image.
>
>This is a proven build sequence:
> ```
>    cd tesseract
>    ./autogen.sh
>    mkdir -p bin/release
>    cd bin/release
>    ../../configure --disable-openmp --disable-shared 'CXXFLAGS=-g -O2 -fno-math-errno -Wall -Wextra -Wpedantic'
>    # Build tesseract and training tools. Run `make` if you don't need the training tools.
>    make training
>    cd ../..
>```
>This disabled OpenMP (multi threading), does not use a shared Tesseract library (that makes it possible to run tesseract without installation), enables compiler optimizations, disables setting of errno for mathematical functions (faster execution!) and enables lots of compiler warnings.

**Comment by jon-sch** [comment]
> Have you compiled Tesseract to run on a single thread? If you're using the default build, then wrapping the threading via python will have no impact; from [the tesseract-ocr wiki](https://github.com/tesseract-ocr/tesseract/wiki/Compiling-%E2%80%93-GitInstallation):
> (...)

Thanks for pointing it out. I used only the default build commands. I built docker images with normal and mass production (without `--disable-shared` because tesserocr does not build otherwise) configuration. Did not change the situation:

mass production build:
> [SEQUENTIAL] ocr for 4 images took 2.501s (mean over 10 runs)
> [THREADED] ocr for 4 images took 1.536s (mean over 10 runs)
> [THREADED2] ocr for 4 images took 2.034s (mean over 10 runs)

normal build:
> [SEQUENTIAL] ocr for 4 images took 1.154s (mean over 10 runs)
> [THREADED] ocr for 4 images took 1.380s (mean over 10 runs)
> [THREADED2] ocr for 4 images took 1.556s (mean over 10 runs)

**Comment by jon-sch** [comment]
Probably this is a tesseract issue rather than a tesserocr issue:
https://github.com/tesseract-ocr/tesseract/issues/2611

**Comment by sirfz** [comment]
I think both tests you've done are identical since `image_to_text` basically initializes a new instance of the tesseract API under the hood, which is pretty much what you're doing in your first threaded test (but in Python). A better approach would be to create a pool of threads with each thread having its own `PyTessBaseAPI` instance and reuse them for processing multiple images concurrently.

**Comment by jon-sch** [comment]
Yes, that is how I though about it as well. I "simulated" this in `test_threaded`, I do the creation of the `PyTessBaseAPI` outside timing code and only use each thread once. In the final version, I would reuse threads and api objects. For my use case I need the speedup per request in a web service.
