### ISSUE TITLE
Missing PyLTRResultIterator method RowAttributes

### ISSUE THREAD

**Issue by hnesk** [sirfz/tesserocr#192]
tesserocr has no method `PyLTRResultIterator.RowAttributes()
`For tesseract it is defined here:
https://github.com/tesseract-ocr/tesseract/blob/master/src/ccmain/ltrresultiterator.cpp#L145

It would be quite useful to determine the fontsize for the row if no other font information is availabe(with lstm).

Another possibility would be adapt the check here: 
https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx#L834

The pointsize is set, even if there is no other font information (see https://github.com/tesseract-ocr/tesseract/blob/master/src/ccmain/ltrresultiterator.cpp#L174)

**Comment by sirfz** [comment]
Please try the latest master branch. Example:

```python
with PyTessBaseAPI() as api:
    api.SetImageFile('/path/to/file.jpg')
    api.Recognize()
    it = api.GetIterator()
    print(it.RowAttributes())
```

**Comment by hnesk** [comment]
Great! Thank you. Works as expected!
