### ISSUE TITLE
How to create PDFs?

### ISSUE THREAD

**Issue by AlfredoCubitos** [sirfz/tesserocr#193]
Hi,
I'm trying to create a pdf file from various images with this code:

```
from tesserocr import PyTessBaseAPI

tessapi = PyTessBaseAPI(lang='deu')
try:
    tessapi.SetVariable('tessedit_create_pdf', 'True')
    
    tessapi.ProcessPage("TestOcr","files.tes",None,0)
finally:
    tessapi.End()
```

Where files.tes is a text file with the images path.
running this, I got this error:
```
tessapi.ProcessPage("TestOcr","files.tes",None,0)
  File "tesserocr.pyx", line 2066, in tesserocr.PyTessBaseAPI.ProcessPage
TypeError: an integer is required
```
Btw, is this the correct way to set the `tessedit_create_pdf` variable?

**Comment by florianbussmann** [comment]
Hi @AlfredoCubitos, seems like you mixed up the arguments. The third parameter is page_index and should not be None.
Also note that ProcessPage needs a PIL.Image, i.e.
```
# TODO read image filename from files.tes
image_filename = 'yourImage.jpg'
from PIL import Image
tessapi.ProcessPage(outputbase = 'TestOcr', image = Image.open(image_filename), page_index = 0, filename = image_filename)
```

The usage of SetVariable seems correct

**Comment by AlfredoCubitos** [comment]
Hi @florianbussmann,

thank you for your answer.
I was a little bit confused, because I thought that the file name handling that you described is automatically handled by setting the variable  `tessedit_create_pdf`

So, the question is, is reading images from a file list supported?

I'm using tesseract 4.1.0, on command line tesseract supports this feature.

**Comment by florianbussmann** [comment]
Hi @AlfredoCubitos,
use `ProcessPages` instead which supports file lists

> filename (str): Can point to a single image, a multi-page TIFF, or **a plain text list of image filenames**.

Try this one: `tessapi.ProcessPages(outputbase = 'TestOcr', filename = 'files.tes')`
