### ISSUE TITLE
Crash in WordFontAttributes

### ISSUE THREAD

**Issue by lachs0r** [sirfz/tesserocr#20]
`WordFontAttributes` can return a NULL pointer. This crashes the Python string conversion.

**Comment by sirfz** [comment]
Thanks @lachs0r for reporting this issue. Could you please try the version from the [bugfix](https://github.com/sirfz/tesserocr/tree/bugfix) branch, it should now return `None` when `WordFontAttributes` returns `NULL`.

**Comment by lachs0r** [comment]
That’s the same thing I did locally when I reported the issue. Works.
