### ISSUE TITLE
'numpy.ndarray' object has no attribute 'save'

### ISSUE THREAD

**Issue by giegiey** [sirfz/tesserocr#208]
I get this error 

>   File "live.py", line 19, in <module>
>     print(tesserocr.image_to_text(frame))
>   File "tesserocr.pyx", line 2431, in tesserocr._tesserocr.imag
>   File "tesserocr.pyx", line 325, in tesserocr._tesserocr._imag
>   File "tesserocr.pyx", line 326, in tesserocr._tesserocr._imag
> AttributeError: 'numpy.ndarray' object has no attribute 'save'

this is example code

```
import cv2
import tesserocr
import imutils

IM_WIDTH = 600
IM_HEIGHT = 400

camera = cv2.VideoCapture(0)

print(tesserocr.tesseract_version())  # print tesseract-ocr version
print(tesserocr.get_languages())  # prints tessdata path and list of available languages

while True:
    ret, frame = camera.read()
    frame = imutils.resize(frame, width=IM_WIDTH)
    key = cv2.waitKey(1) & 0xFF

    print(tesserocr.image_to_text(frame))
    cv2.imshow("Frame", frame)
    cv2.waitKey(0)

    if key == ord("q"):
        break

cv2.destroyAllWindows()
```

**Comment by sirfz** [comment]
`image_to_text` function expects a `PIL.Image` object while you're passing a numpy array.

**Comment by nex0ma** [comment]
so, from SO (stackoverflow :+1: )

```
    img = Image.fromarray(frame)

    print(tesserocr.image_to_text(img))

    np_img = np.array(img)
    cv2.imshow('plate',  np_img)
```

**Comment by chenruhai** [comment]
I need your help. My problem is the same as your error report. Below are my code and error report information. Could you help me think about it and solve it?I look forward to your answer.

Here's my code:
`import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
import tesserocr

img = cv.imread("201909200541/20190920054185.jpg",1)
res = cv.resize(img,None,fx=0.3,fy=0.3,interpolation=cv.INTER_CUBIC)
cv.rectangle(res,(int((x+50)*0.5),int((y+50)*1.1)),(int(w*0.9),int(h*0.91)),(245,245,245),-1)
GrayImage=cv.cvtColor(res,cv2.COLOR_BGR2GRAY)
print(GrayImage.shape)

# Otsu
ret3,th3 = cv.threshold(GrayImage,0,255,cv.THRESH_BINARY+cv.THRESH_OTSU)
# cv.imshow("ret",th3)
# cv.waitKey(0)
# cv.destroyAllWindows()

def CVImageToPIL(img_Opencv):
    # OpenCV image to PIL image
    img2 = Image.fromarray(img_Opencv)
    return img2



img = CVImageToPIL(GrayImage)
result = tesserocr.image_to_text(GrayImage)
print(result)`

Here's my error:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-94-bf1ed1734506> in <module>
     25 
     26 img = CVImageToPIL(GrayImage)
---> 27 result = tesserocr.image_to_text(GrayImage)
     28 print(result)

tesserocr.pyx in tesserocr._tesserocr.image_to_text()

tesserocr.pyx in tesserocr._tesserocr._image_buffer()

tesserocr.pyx in tesserocr._tesserocr._image_buffer()

AttributeError: 'numpy.ndarray' object has no attribute 'save'`

**Comment by chenruhai** [comment]
> I need your help. My problem is the same as your error report. Below are my code and error report information. Could you help me think about it and solve it?I look forward to your answer.
> 
> # Here's my code:
> `import cv2 as cv
> import matplotlib.pyplot as plt
> import numpy as np
> from PIL import Image
> import tesserocr
> 
> img = cv.imread("201909200541/20190920054185.jpg",1)
> res = cv.resize(img,None,fx=0.3,fy=0.3,interpolation=cv.INTER_CUBIC)
> cv.rectangle(res,(int((x+50)_0.5),int((y+50)_1.1)),(int(w_0.9),int(h_0.91)),(245,245,245),-1)
> GrayImage=cv.cvtColor(res,cv2.COLOR_BGR2GRAY)
> print(GrayImage.shape)
> 
> '''Otsu'''
> ret3,th3 = cv.threshold(GrayImage,0,255,cv.THRESH_BINARY+cv.THRESH_OTSU)
> '''
> cv.imshow("ret",th3)
> cv.waitKey(0)
> cv.destroyAllWindows()
> '''
> def CVImageToPIL(img_Opencv):
> '''OpenCV image to PIL image'''
> img2 = Image.fromarray(img_Opencv)
> return img2
> 
> img = CVImageToPIL(GrayImage)
> result = tesserocr.image_to_text(GrayImage)
> print(result)`
> 
> # Here's my error:
> `---------------------------------------------------------------------------
> AttributeError Traceback (most recent call last)
> in
> 25
> 26 img = CVImageToPIL(GrayImage)
> ---> 27 result = tesserocr.image_to_text(GrayImage)
> 28 print(result)
> 
> tesserocr.pyx in tesserocr._tesserocr.image_to_text()
> 
> tesserocr.pyx in tesserocr._tesserocr._image_buffer()
> 
> tesserocr.pyx in tesserocr._tesserocr._image_buffer()
> 
> AttributeError: 'numpy.ndarray' object has no attribute 'save'`
I solved it. Thank you!
