### ISSUE TITLE
How to set two lang

### ISSUE THREAD

**Issue by Yangxiaojun1230** [sirfz/tesserocr#209]
In tesseract could use "-l eng+chi_sim" ,how to realize that in tesserocr ?

**Comment by Yangxiaojun1230** [comment]
I found out could use PyTessBaseAPI(lang='chi_sim'+''eng') 
Another question, could the api return the confidence of each character?

**Comment by sirfz** [comment]
You can specify multiple languages separating them with literal `+`: `PytessBaseAPI(lang='chi_sim+eng')`.

You can check the [classifier choices iteration example](https://github.com/sirfz/tesserocr#iterator-over-the-classifier-choices-for-a-single-symbol) for iterating characters and getting their confidence.
