### ISSUE TITLE
Please provide tesserocr Windows build guide

### ISSUE THREAD

**Issue by redstoneleo** [sirfz/tesserocr#217]
Please provide tesserocr Windows build guide, the the wheel files provided by  [simonflueckiger/tesserocr-windows_build/releases](https://github.com/simonflueckiger/tesserocr-windows_build/releases)  is one year outdated, I need  build guide to create up-to-date wheels , Thanks !

**Comment by sirfz** [comment]
Recommended Windows installation method is via Conda as explained in the [README](https://github.com/sirfz/tesserocr#conda)

**Comment by redstoneleo** [comment]
but there is no 32bit version in Conda

**Comment by DeliciousHair** [comment]
Or, just use docker and avoid all the headaches.

**Comment by zdenop** [comment]
have a look at this: https://github.com/sirfz/tesserocr/blob/master/Windows.build.md
You will need to adjust it for 32, e.g. to call VS:
call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
