### ISSUE TITLE
Error during setup ‘class tesseract::ResultIterator’ has no member named ‘GetBestLSTMSymbolChoices’

### ISSUE THREAD

**Issue by bhargavaurala** [sirfz/tesserocr#218]
Hello, 

Thanks for the repository. I have used it before and I liked the fact that we can set it up as as API to do batch calls and get confidence values. It is very useful.

I am trying to set it up for a newer version of Tesseract and having some difficulty overriding the default settings of setup.py.

Currently `which tesseract` on my Ubuntu 16.04 points to the desired version of Tesseract (4.1.1). However pkg_config is not being updated. Therefore I even tried manually changing the config dictionary in setup.py by providing the correct library and include directories. But the installation still seems to getting an error. Could you please provide more explanation (than in the readme) for custom tesseract installs?

The build command is `python3 setup.py build_ext -I/usr/include`
Output looks like this:
```
config from pkg_config {'library_dirs': ['/usr/local/lib', '/usr/local/lib'], 'include_dirs': ['/usr/local/include', '/usr/local/include', '/usr/local/include'], 'libraries': ['tesseract', 'lept']}
overrriding
Supporting tesseract v4.1.1-rc2-21-gf4ef
Configs from pkg-config: {'library_dirs': ['/usr/lib/x86_64-linux-gnu', '/usr/lib/x86_64-linux-gnu'], 'include_dirs': ['/usr/include', '/usr/include', '/usr/include'], 'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67174656}}
running build_ext
building 'tesserocr' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include/python3.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_16PyResultIterator_8GetBestLSTMSymbolChoices(__pyx_obj_9tesserocr_PyResultIterator*)’:
tesserocr.cpp:12338:43: error: ‘class tesseract::ResultIterator’ has no member named ‘GetBestLSTMSymbolChoices’
   __pyx_v_output = (__pyx_v_self->_riter->GetBestLSTMSymbolChoices()[0]);
```
I have also made sure that the correct library folder is present in `LD_LIBRARY_PATH`. It seems like the earlier version of Tesseract 4.0.0dev did not have the GetBestLSTMSymbolChoices() method in class tesseract::ResultIterator however the current version (4.1.1) does and I have confirmed this. The -I folders `/usr/include` contains the current version of Tesseract.

Please advise.

Thanks

**Comment by sirfz** [comment]
It seems like your include dir (/usr/local/include/tesseract) point to header files of an older tesseract version, worth checking out.

**Comment by bhargavaurala** [comment]
Hello,

Thanks for the quick response. Even after manually changing the include dir, the build commands were still looking at the old include dir.

I was able to build by manually removing all files related to older version of tesseract. Everything works fine now!
