### ISSUE TITLE
Support for ALTO (XML) output

### ISSUE THREAD

**Issue by EndingEta** [sirfz/tesserocr#220]
Hi there, I am currently using this API and trying to get an ALTO output with the function: **"ProcessPages"** and the variable **"tessedit_create_alto"** set to 1.
However, the terminal suggests that no renderer is enabled, and I found out in the tesserocr.pyx there is no ALTORender solution.

Or it might be my problem dont know how to do it. Could you please help me with this?Thanks!

**Comment by sirfz** [comment]
Not sure what you mean  by "the terminal suggests that no renderer is enabled", can you share more info about it? Could be that this renderer doesn't exist in your tesseract build

**Comment by EndingEta** [comment]
> Not sure what you mean by "the terminal suggests that no renderer is enabled", can you share more info about it? Could be that this renderer doesn't exist in your tesseract build

Thanks for your reply, what I meant was that the "console/terminal" supervising the process of programs gave a warning with that statement, the "no renderer is enabled", and terminated the process itself when I was asking for the ALTO output.
I am currently using "tesserocr" instead of tesseract developmental build, but I didn't see the renderer is existing in it, however, on top of that, I did see the tessedit_create_alto variable within.

**Comment by bertsky** [comment]
> no renderer is enabled

That exception was raised by tesserocr's `ProcessPages` (see API documentation). Its documentation currently does not list the ALTO renderer as being supported, and in fact it relies on `_get_renderer`, which does not yet implement the case for `tessedit_create_alto`. Please try #258

**Comment by zdenop** [comment]
IMO this could be closed
