### ISSUE TITLE
GetRegions return zip issue

### ISSUE THREAD

**Issue by jonathan-s-norris** [sirfz/tesserocr#222]
Hello,
I've run into an issue with GetRegions returing a zip instead of a list. It's possible this has everything to do with my memory limitations as the program crashes and I get a popup with 'Python has stopped working .... '. I checked the event logs and am getting error code 0XC0000005.

I've been unable to convert the zip to a list or access items in the zip without the program crashing. I included some sample code of what's going on below. Thank you.

```python
import os
import tesserocr
from PIL import Image as PILImage

def zipOutput(regions):
    #the following should work as a zip but it doesnt
    try:
        images, boxes = zip(*regions)
    except Exception as e:
        print(e)

def listOutput(regions):
    try:
        for image, boxes in regions:
            print(image, boxes)
    except Exception as e:
        print(e)

#set tesseract pil image
image = PILImage.open('converted.tiff', mode='r')
path = os.getcwd() + '\\tessdata'
api = tesserocr.PyTessBaseAPI(path=path, lang='eng', \
    psm=tesserocr.PSM.AUTO_OSD, init=True, oem=tesserocr.OEM.DEFAULT)
api.SetImage(image)

regions = api.GetRegions()
print(regions) 
#OUTPUT--- <zip object at 0x0000005F98D99908>
#what should work if a list was returned
listOutput(regions)
#what should work if can unpack zip as Image, boxes tuples
zipOutput(regions)
```

**Comment by jonathan-s-norris** [comment]
WordTruthUTF8Text()

**Comment by jonathan-s-norris** [comment]
If it helps at all to find the source of python crashing I found another method that crashes python when using PyResultIterator.WordTruthUTF8Text(). The fault had the same exception code 0xc0000005. I included the event log details below.

Faulting application name: python.exe, version: 3.7.7150.1013, time stamp: 0x5e676f16
Faulting module name: _tesserocr.cp37-win_amd64.pyd, version: 0.0.0.0, time stamp: 0x5c34a76e
Exception code: 0xc0000005
Fault offset: 0x00000000000301f3
Faulting process id: 0xff34
Faulting application start time: 0x01d618ee68c4a50b
Faulting application path: C:\Users\User\AppData\Local\Programs\Python\Python37\python.exe
Faulting module path: C:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\tesserocr\_tesserocr.cp37-win_amd64.pyd
Report Id: a8c89dfe-84e1-11ea-8272-3863bb917b95
Faulting package full name: 
Faulting package-relative application ID:

**Comment by sirfz** [comment]
What version of tesserocr are you using? This issue has been fixed since version [2.4.1](https://github.com/sirfz/tesserocr/releases/tag/v2.4.1)

**Comment by jonathan-s-norris** [comment]
Thanks for the reply. I'm using 2.4.0 on Windows because that's the last one with a whl file I've been able to find for pip install.

**Comment by sirfz** [comment]
you can install the latest version via Conda on Windows as described in the [README](https://github.com/sirfz/tesserocr#conda)
