### ISSUE TITLE
Failed building wheel for tesserocr with tesserocr.cpp:19759:20: error: redeclaration of 'PyGILState_STATE __pyx_gilstate_save'

### ISSUE THREAD

**Issue by raghu5291** [sirfz/tesserocr#223]
When doing pip install tesserocr:
`
Running setup.py bdist_wheel for tesserocr: started
  Running setup.py bdist_wheel for tesserocr: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xy8seksk/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\
n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpbspmupnkpip-wheel- --python-tag cp36:
  Supporting tesseract v4.1.1-rc2-21-gf4ef
  Configs from pkg-config: {'library_dirs': [], 'include_dirs': ['/usr/include', '/usr/include'], 'libraries': ['tesseract', 'archive', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 67174656}}
  /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_ext
  building 'tesserocr' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include -I/usr/include/python3
.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
  tesserocr.cpp: In function 'int __pyx_f_9tesserocr_13PyTessBaseAPI__init_api(__pyx_obj_9tesserocr_PyTessBaseAPI*, __pyx_t_9tesseract_cchar_t*, __pyx_t_9tesseract_cchar_t*, tesseract::OcrEngineMode, char**, int,
const GenericVector<STRING>*, const GenericVector<STRING>*, bool, tesseract::PageSegMode)':
  tesserocr.cpp:19759:20: error: redeclaration of 'PyGILState_STATE __pyx_gilstate_save'
     PyGILState_STATE __pyx_gilstate_save = __Pyx_PyGILState_Ensure();
                      ^~~~~~~~~~~~~~~~~~~
  tesserocr.cpp:19756:20: note: 'PyGILState_STATE __pyx_gilstate_save' previously declared here
     PyGILState_STATE __pyx_gilstate_save;
                      ^~~~~~~~~~~~~~~~~~~
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for tesserocr

`

**Comment by sirfz** [comment]
Possibly an issue with Cython, if you don't have the latest version maybe updating it is worth a try.

**Comment by raghu5291** [comment]
I am using it in docker, this is the dockerfile
```
FROM ubuntu:18.04

RUN apt-get update && apt-get -y install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config

RUN mkdir /home/work
WORKDIR /home/work

RUN apt-get update && apt-get install -y python3-dev \
        python3-pip \
        libleptonica-dev \
        libtesseract-dev

RUN apt-get install -y libsm6 libxext6 libxrender-dev

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1

WORKDIR / 
COPY requirements.txt ./
RUN  python3 -m pip install -r requirements.txt
RUN rm requirements.txt 

WORKDIR /usr/src/app
COPY . /usr/src/app

ENTRYPOINT ["./start-worker.sh"]
```

**Comment by raghu5291** [comment]
> Possibly an issue with Cython, if you don't have the latest version maybe updating it is worth a try.

Thank you for your reply :) however I dont explicitly use Cython, it is not part of my requirements, also it the build was working yesterday, today trying to build this from last 6 hours

**Comment by WarwickMasson** [comment]
I was experiencing the same issue today. For what it's worth, when I install Cython before tesserocr, it builds OK. I tested it with your Dockerfile and it works. That said, I'm also not sure what changed in the build / dependencies that made this necessary. This works:
```
FROM ubuntu:18.04

RUN apt-get update && apt-get -y install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config

RUN mkdir /home/work
WORKDIR /home/work

RUN apt-get update && apt-get install -y python3-dev \
        python3-pip \
        libleptonica-dev \
        libtesseract-dev

RUN apt-get install -y libsm6 libxext6 libxrender-dev

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1

WORKDIR / 
COPY requirements.txt ./
RUN python3 -m pip install Cython                                                                                                                                          
RUN  python3 -m pip install -r requirements.txt
RUN rm requirements.txt 

WORKDIR /usr/src/app
COPY . /usr/src/app

ENTRYPOINT ["./start-worker.sh"]

```

**Comment by raghu5291** [comment]
Thanks @WarwickMasson , i will try your change as well, whereas i tried using ubuntu:20.04 the build was successful.

**Comment by raghu5291** [comment]
@WarwickMasson thank you for ix it worked like charm....closing the ticket.

**Comment by sirfz** [comment]
Weird, maybe you need to update setuptools before installing tesserocr (I wonder what version of Cython was used by the setup in your first case).
