### ISSUE TITLE
Python tesserocr image_to_text Runtime Error:failed to read picture

### ISSUE THREAD

**Issue by YueXiaolong** [sirfz/tesserocr#23]
platform:Ubuntu 15.1/Python 2.7 This is a demo which I used,from `https://github.com/sirfz/tesserocr`

```
import tesserocr
from PIL import Image

print tesserocr.tesseract_version()  # print tesseract-ocr version
print tesserocr.get_languages()  # prints tessdata path and list of available languages

image = Image.open('03.jpg')  # I verify the file and directory is right
print tesserocr.image_to_text(image)  # print ocr text from image
# or
print tesserocr.file_to_text('03.jpg')
```
And above get these output:

```
tesseract 3.04.00
 leptonica-1.73
  zlib 1.2.8

(u'/usr/share/tesseract-ocr/tessdata/', [u'eng', u'osd', u'equ'])
Traceback (most recent call last):
  File "testImage.py", line 8, in <module>
    print tesserocr.image_to_text(image)  # print ocr text from image
  File "tesserocr.pyx", line 2281, in tesserocr.image_to_text (tesserocr.cpp:20529)
RuntimeError: Failed to read picture
```

**Comment by sirfz** [comment]
You don't have `libjpeg` installed (based on the output of `tesseract.tesseract_version()`). Install `libjpeg-dev` and try again.

You might also want to install other image libs such as `libpng` and `libtiff` if you wish to process other image types.

**Comment by YueXiaolong** [comment]
Thank you for you reply!  As you said, I checked  my `libjpeg` install(actually, it has been installed, also as png, tiff ):
```
yxl@yxl-VirtualBox:~$ sudo apt-get install libjpeg8-dev
[sudo] password for yxl: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjpeg8-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

 And then I tried it again, but the problem appear again. (the output is same as before, no output like "libjpeg" ). I wonder is there some **setting or config** wrong I made? Hum… I used `$ apt-get install tesseract-ocr libtesseract-dev libleptonica-dev` and `pip install tesserocr` to install.

**Comment by sirfz** [comment]
I suggest you re-install (or re-compile) tesseract because your current installation doesn't recognize any image libraries as you can see in the `tesseract_version()` output.
