### ISSUE TITLE
Allow to set init-only variables in PyTessBaseAPI

### ISSUE THREAD

**Issue by miguel-lorenzo** [sirfz/tesserocr#231]
Hi!

I have found in [tesseract doc](https://github.com/tesseract-ocr/tessdoc/blob/master/ControlParams.md) that `load_freq_dawg` and `load_system_dawg` are init only variables. This means they can not be set through `TessBaseAPI::SetVariable`.

This can only be done  [through config files](https://stackoverflow.com/questions/50204628/tesseract-api-with-load-system-dawg-and-load-freq-dawg/50210308). 

Is there are planning for `PyTessBaseAPI` class to support init-only variables via config files or arguments?

As said in [tesseract doc](https://tesseract-ocr.github.io/tessdoc/ImproveQuality.html#dictionaries-word-lists-and-patterns), disabling the dictionaries Tesseract uses should increase recognition and speed if most of your text isn't dictionary words.

Thank your in advance.

**Comment by ohk2kt3t4** [comment]
>  Page Segmentation Mode is set to :attr:`PSM.AUTO` after initialization by default.

Is there any reason why the `InitFull` constructor shouldn't be changed to allow 'psm' as an argument?

So we can do this:

```python
tess_api = tesserocr.PyTessBaseAPI(init=False)
tess_api.InitFull(
    lang=lang,
    psm=PSM.RAW_LINE,
    variables={"load_system_dawg": "F",
               "load_freq_dawg": "F"}
)
```

Instead of currently doing this:
```python
tess_api = tesserocr.PyTessBaseAPI(init=False)
tess_api.InitFull(
    lang=lang,
    variables={"load_system_dawg": "F",
               "load_freq_dawg": "F"}
)
tess_api.SetPageSegMode(PSM.RAW_LINE)
```
