### ISSUE TITLE
Impossible to install through pip.

### ISSUE THREAD

**Issue by plysytsya** [sirfz/tesserocr#235]
Since a few days ago we have problems to install tesserocr through pip. I think the error is somehow related to a recent deprecation introduced in pip. Although downgrading pip did not help. Even using old images where tesserocr was installable now throughs these errors shown below. Does anyone have an idea where this comes from and how to fix it? After digging it my guess is that it's somehow related to setup.py. We recently started to face similar issues with other pip packages like `editdistance`. This one we get when installing on the python:3.8-buster base image. Maybe it is a hint for someone:

`DEPRECATION: Could not build wheels for tesserocr which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.`

➜  pip install tesserocr
Collecting tesserocr
  Downloading tesserocr-2.5.1.tar.gz (54 kB)
     |████████████████████████████████| 54 kB 798 kB/s 
Building wheels for collected packages: tesserocr
  Building wheel for tesserocr (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py'"'"'; __file__='"'"'/private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-wheel-1egm4ux1
       cwd: /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/
  Complete output (19 lines):
  /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py:72: SyntaxWarning: "is not" with a literal. Did you mean "!="?
    if subversion is not None and subversion is not "":
  /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py:135: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    _LOGGER.warn('Failed to extract tesseract version from executable: {}'.format(e))
  Failed to extract tesseract version from executable: [Errno 2] No such file or directory: 'tesseract'
  Supporting tesseract v3.04.00
  Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 50593792}}
  running bdist_wheel
  running build
  running build_ext
  building 'tesserocr' extension
  creating build
  creating build/temp.macosx-10.9-x86_64-3.8
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c tesserocr.cpp -o build/temp.macosx-10.9-x86_64-3.8/tesserocr.o
  tesserocr.cpp:837:10: fatal error: 'leptonica/allheaders.h' file not found
  #include "leptonica/allheaders.h"
           ^~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for tesserocr
  Running setup.py clean for tesserocr
Failed to build tesserocr
Installing collected packages: tesserocr
    Running setup.py install for tesserocr ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py'"'"'; __file__='"'"'/private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-record-osob8ocr/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/tesserocr
         cwd: /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/
    Complete output (19 lines):
    /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py:72: SyntaxWarning: "is not" with a literal. Did you mean "!="?
      if subversion is not None and subversion is not "":
    /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py:135: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
      _LOGGER.warn('Failed to extract tesseract version from executable: {}'.format(e))
    Failed to extract tesseract version from executable: [Errno 2] No such file or directory: 'tesseract'
    Supporting tesseract v3.04.00
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 50593792}}
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.macosx-10.9-x86_64-3.8
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c tesserocr.cpp -o build/temp.macosx-10.9-x86_64-3.8/tesserocr.o
    tesserocr.cpp:837:10: fatal error: 'leptonica/allheaders.h' file not found
    #include "leptonica/allheaders.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py'"'"'; __file__='"'"'/private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-install-ktk4ug6j/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/35/_hjx99kj2n321h_55jv3swq00000gn/T/pip-record-osob8ocr/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.8/include/python3.8/tesserocr Check the logs for full command output.

**Comment by ApurvaDani** [comment]
Facing similar issue

**Comment by kba** [comment]
Looks like tesseract and/or leptonica are not installed

```
sudo apt install libleptonica-dev libtesseract-dev tesseract-ocr{,-eng,-osd}
```

Or compile/link/install a recent checkout of tesseract manually.

**Comment by ApurvaDani** [comment]
I am using python 3.8 and windows, Is there any support for tesserocr for this configuration?

**Comment by kba** [comment]
> I am using python 3.8 and windows, Is there any support for tesserocr for this configuration?

@ApurvaDani Please don't highjack other people's issues, your issue is very different. Yes, it is possible to run tesserocr in Windows, see the [README](https://github.com/sirfz/tesserocr/blob/master/README.rst#windows) or search the issues for past discussions. You will save yourself a lot of trouble by running in WSL or Docker IMHO.
