### ISSUE TITLE
How to detect bold or italic text. 

### ISSUE THREAD

**Issue by Kunal2341** [sirfz/tesserocr#236]
So I have a document full of text. Is there any way that I can detect bold or special kinds of text. Maybe detect colors, or size of the text. Could someone help me with how to do this? Anything will help. Thanks

**Comment by sirfz** [comment]
You're better off asking on StackOverflow as this is a tesseract api-related question. Try reading tesseract's documentation for a method to extract word attributes (such as bold, color, etc) and you should be able to call them via tesserocr (if not then feel free to open an issue).
