### ISSUE TITLE
Change tesseract version to 5.0.0

### ISSUE THREAD

**Issue by C-monC** [sirfz/tesserocr#239]
Hi,

I'm trying to change the tesseract version to 5.0.0. I've set the LD_LIBRARY_PATH to /usr/bin/tesseract which is tesseract 5. Printing the version still returns 4.1.1. Has anyone managed to get this right?

Thanks,
Simon

**Comment by sirfz** [comment]
tesserocr relies on pkg-config to detect the installed libtesseract and libleptonica versions during setup. You can specify your own paths during setup as shown in the [README example](https://github.com/sirfz/tesserocr#linux-and-bsdmacos).

**Comment by Amitiwari2609** [comment]
Facing same issue. Tried setting LD_LIBRARY_PATH. Only have one tesseract installed in system. i.e 5.0.0. alph. 
Still when i am trying tesserocr.tesseract_version(), its pointing to tesseract 4.

Thanks in advance for help
Amitabh

**Comment by sirfz** [comment]
The environment variable is used during setup to build tesserocr against the available tesseract version. If you're using a binary version then you get the tesseract version it's been pre-built with.

**Comment by waylandc** [comment]
> 
> 
> The environment variable is used during setup to build tesserocr against the available tesseract version. If you're using a binary version then you get the tesseract version it's been pre-built with.

Is it possible to install a pre-built binary of tesseract 5.x
Then use conda (or hopefully poetry) to install tesserocr?

**Comment by nikitasmiramedix** [comment]
Has anyone been able to successfully use tesserocr with tesseract 5.0? I seem to be able to get pip to compile it against tesseract 5.0, however `import tesserocr` yields `ImportError: /path/to/my/venv/lib/python3.8/site-packages/tesserocr.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK6STRING5c_strEv`
