### ISSUE TITLE
How to get hOCR without going via filesystem

### ISSUE THREAD

**Issue by EdwardJB** [sirfz/tesserocr#245]
Hi,

I need to process an image to hOCR in a way that lets me do some further manipulation on the output. The best I can do is the code below. This works, but requires that I write the file out then read it back in, so is a bit ugly. Plus the function will be used for batch processing where efficiency is an issue, so I want to avoid the overhead.

Is there a way I can just return the hOCR as a string without going via the filesystem?

Thanks.

```python
    with PyTessBaseAPI() as api:
        input='fixtures/image_in.png'
        output='image_out'

        api.SetVariable("tessedit_create_hocr", "T")
        pp=api.ProcessPages(output,input)
        
        # Unnecessary filesystem write/read
        path_hocr=Path(output).with_suffix('.hocr')
        hocr=path_hocr.read_text()
        path_hocr.unlink()
        
        # Need to modify hOCR here.
        hocr
```

**Comment by sirfz** [comment]
The tesseract `ProcessPages` API works that way (i.e. output results into a file), tesserocr simple wraps that method. Not sure if there's a different way to get what you need, maybe asking on StackOverflow can help.

**Comment by a7ul** [comment]
```py
        # Perform OCR and get hOCR output
        with tesserocr.PyTessBaseAPI() as api:  # type: ignore
            api.SetImage(Image.fromarray(image))  # type: ignore
            hocr_output = api.GetHOCRText(0)  # type: ignore
            return hocr_output  # type: ignore

```
This works now
