### ISSUE TITLE
Any plans for supporting Python 3.8?

### ISSUE THREAD

**Issue by jlintusaari** [sirfz/tesserocr#246]
Hi,

Would there be plans to support Python 3.8?

**Comment by sirfz** [comment]
Python 3.8 is already supported

**Comment by jlintusaari** [comment]
Thanks, it wasn't visible on the badge, so I though it was not supported: 
![image](https://user-images.githubusercontent.com/22339859/107748433-b56b7980-6d21-11eb-8a98-319e0ddaeff5.png)
