### ISSUE TITLE
How to recognize single character

### ISSUE THREAD

**Issue by deqiu** [sirfz/tesserocr#25]
If i use a image with several characters, it works. How ever it does't work if i want to recognize single character. What should I do?
Thanks!

**Comment by sirfz** [comment]
This is not a tesserocr issue exactly since it's directly related to tesseract (you probably are better off asking this on StackOverflow).

I suggest you try playing with the Page Segmentation Mode, try using `tesserocr.PSM.SINGLE_CHAR` and see if that helps.

**Comment by antiax** [comment]
Despite this is not an issue, I had the same problem, and this solution works for me. I think it can help somebody else.

from tesserocr import PyTessBaseAPI, PSM
from PIL import Image

with PyTessBaseAPI(psm=PSM.SINGLE_CHAR) as api:
    image = Image.open('onechar.jpg')
    api.SetImage(image)
    print api.GetUTF8Text()

**Comment by sirfz** [comment]
Great, glad it worked for you @antiax. Thanks for sharing :)
