### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by Goghzki** [sirfz/tesserocr#253]
I found if i use the same version of tesseract and different version of tesserocr, I might get different result from same picture. Besides, the result of tesserocr is slightly different from original result from tesseract. 
How to explan this?

**Comment by sirfz** [comment]
You will have to provide full details in order to reproduce the bug. Tesserocr and Tesseract versions + test image and sample code.

**Comment by chamoulox** [comment]
Hello, this is an issue I also encountered  while upgrading to 2.5.1
I found the reason: https://github.com/sirfz/tesserocr/commit/600ab000a676140c73db402d998f2ff60df08e0b

I lost format due to image manipulation, and using a different image format produces different output from tesseract.

**Comment by zdenop** [comment]
image format with lossless compression should produce the same result.  therefore jpeg is not correct format for OCR (tesseract especially)

**Comment by Goghzki** [comment]
my tesseract version is
tesseract 4.0.0
 leptonica-1.75.3
  libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libopenjp2 2.1.2
 Found AVX2
 Found AVX
 Found SSE

I found in Tesserocr==2.4.0, the result is different with original tesseract result if I use opencv to read img, but if I use pillow to read img, the result is the same.
When i upgrade Tesserocr to 2.5.1, this problem disappeared.

**Comment by Goghzki** [comment]
sample of test code:
`from tesserocr import PyTessBaseAPI, PSM, OEM, RIL`
`from PIL import Image`
`import cv2`
`tesserDataPath="tessdata"`
`lang = "seqv7_int"`
`tesserAPI = PyTessBaseAPI(psm=PSM.SINGLE_BLOCK, lang=lang, path=tesserDataPath, oem=OEM.LSTM_ONLY)`
`tesserAPI.SetVariable("load_system_dawg", "F")`
`tesserAPI.SetVariable("load_freq_dawg", "F")`
`tesserAPI.SetVariable("tessedit_enable_doc_dict", "0")`
`#img = Image.open("WO2021061990A1_14.png")`
`img = Image.fromarray(cv2.imread("WO2021061990A1_14.png"))`
`tesserAPI.SetImage(img)`
`a=tesserAPI.GetUTF8Text()`
`print (a)`

**Comment by zdenop** [comment]
If the lastest version is ok, but old has problem: so what is your real problem?

**Comment by Goghzki** [comment]
Sry, I use tesserocr==2.4.0 in the beginning, and found the result is different. Now problem fixed, thanks anyway.
