### ISSUE TITLE
Python 3.8 does not seem to be supported

### ISSUE THREAD

**Issue by jonathan-s-norris** [sirfz/tesserocr#254]
Hello,
The post below states "Python 3.8 is already supported". I wanted to see if there was something I'm missing for tesseract 4.0 with python 3.8 on windows 64. The latest wheel I'm seeing is tesserocr-2.4.0-cp37-cp37m-win_amd64.whl which is not supported for install on python 3.8. Thank you.

_Originally posted by @sirfz in https://github.com/sirfz/tesserocr/issues/246#issuecomment-777499857_

It seems like following instructions here https://github.com/sirfz/tesserocr/blob/master/Windows.build.md are the only options for this?

**Comment by zdenop** [comment]
https://bucket401.blogspot.com/2021/03/building-tesserocr-on-ms-windows-64bit.html

**Comment by jonathan-s-norris** [comment]
> https://bucket401.blogspot.com/2021/03/building-tesserocr-on-ms-windows-64bit.html

Yes, those are same instructions I posted. So there is no wheel file already created for this.

**Comment by zdenop** [comment]
Creating wheel should be easy, but as my [PR is not merged](https://github.com/sirfz/tesserocr/pull/252) I did not finished it:
https://github.com/zdenop/tesserocr/actions/runs/691324430
