### ISSUE TITLE
How to get result similar to Pytesseract's image_to_data

### ISSUE THREAD

**Issue by ichenjia** [sirfz/tesserocr#267]
Hi, 

i need the detailed TSV data as output including the following info:

1) Text
2) width, height, x, y of each word
3) Confidence of each word
4) Level of each word

Historically, I have been using Pytesseract's image_to_data. Does this library have a similar API?

Thanks!

**Comment by rsnitsch** [comment]
The code for this was already provided in another issue by [stefan6419846](https://github.com/stefan6419846): https://github.com/sirfz/tesserocr/issues/300#issuecomment-1143322864
