### ISSUE TITLE
Installation error (error:command 'x86_64-linux-gnu-gcc' failed with exit status 1)

### ISSUE THREAD

**Issue by Vladkryvoruchko** [sirfz/tesserocr#27]
Hi there. After installing all the needed stuff for tesserocr, i have met problems installing your wrapper. 
Actually the versions are
![image](https://cloud.githubusercontent.com/assets/18577874/21883000/9f9c7bfe-d8b5-11e6-8a09-f7353defe6bc.png)

Everything seems fine, but after i `pip install tesserocr`
I get the following errors, im not good at C++
![image](https://cloud.githubusercontent.com/assets/18577874/21883121/378b5868-d8b6-11e6-960d-ed2473a0ea92.png)

**Comment by Vladkryvoruchko** [comment]
What actually helped - was:
![image](https://cloud.githubusercontent.com/assets/18577874/21889353/2ef3677a-d8d1-11e6-93c8-1bd961ff366d.png)

from similar issue topic:
_pip install tesserocr in CentOS_ 
[https://github.com/sirfz/tesserocr/issues/24](url)

Closing.

**Comment by sirfz** [comment]
Hello @Vladkryvoruchko,

tesseract 4.0 requires compilation with c++11 support, the latest beta version in the [tesseract4 branch](https://github.com/sirfz/tesserocr/tree/tesseract4) handles this automatically and also supports tesseract 4's new features (see details [here](https://github.com/sirfz/tesserocr/issues/26#issuecomment-270000500)).

Would appreciate it if you can give feedback about it as well :)

**Comment by wrznr** [comment]
Setting `CPPFLAGS=-DUSE_STD_NAMESPACE` solves this problem (cf. #90).
