### ISSUE TITLE
Specifying tessdata path for available helper functions (e.g. tesserocr.get_languages())

### ISSUE THREAD

**Issue by zivkovic-msz** [sirfz/tesserocr#28]
I compiled tesseract from source so my tessdata path is not "/usr/local/share/tessdata". How could I change the tessdata path so that a function like tesserocr.get_languages() will look in the right place?

**Comment by zivkovic-msz** [comment]
Never mind, I realized the problem was I did not permanently set my TESSDATA_PREFIX environment variable, so I ran into this error after I rebooted my system. For anyone beginning with linux, you need to add this line to your .bashrc file:

export TESSDATA_PREFIX=/some/path/to/tessdata

**Comment by sirfz** [comment]
The tessdata path can be passed to the helper functions:

```python
print tesserocr.get_languages('/some/path/to/tessdata')
```
Same applies to `image_to_text` and `file_to_text` functions (using the `path` argument).

You can also initialize the API with the required path:

```python
with tesserocr.PyTessBaseAPI(path='/some/path/to/tessdata') as api:
    print api.GetAvailableLanguages()
```

**Comment by zivkovic-msz** [comment]
That also works, and thank you for providing this code!
