### ISSUE TITLE
tesserocr import issue

### ISSUE THREAD

**Issue by haideralipf** [sirfz/tesserocr#283]
i installed tesseract 5 on my linux machine but i wanted to install tesseract 4 so i uninstalled tesseract 5 and installed tesseract 4 but since then i cannot import tesserocr into my python code

If i reinstall tesseract5 into my machine tesserocr import just works fine. but if i uninstall tesseract5 and reinstall tesseract4 it wont import i get this following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libtesseract.so.5: cannot open shared object file: No such file or directory
```

**inshort**: after downgrading from tesseract 5 i start gettint this error.

any help?

**Comment by haideralipf** [comment]
here is output of tesserocr
**command:**
`pip install tesserocr`
**output:**
```
Collecting tesserocr
Installing collected packages: tesserocr
Successfully installed tesserocr-2.5.2
```

**Comment by al2h36o30s3** [comment]
yes, i uninstalled tesseract5, tesserocr-2.5.2, and installed tesseract-4..1.3 and tesserocr-2.5.1
