### ISSUE TITLE
RuntimeError: Tesseract library not found in LIBPATH: []

### ISSUE THREAD

**Issue by joseavegaa** [sirfz/tesserocr#287]
I'm trying to install tesserocr 2.5.2 from pip, but I get the following error:

`ERROR: Command errored out with exit status 1:`
`  Traceback (most recent call last):`
`    File "<string>", line 1, in <module>`
`    File "C:\Users\user\AppData\Local\Temp\pip-install-5v2rj3qx\tesserocr_6a01a3c0ee4b4dc6bd1dc39e457777d0\setup.py", line 327, in <module>`
`      ext_modules=[make_extension()],`
`    File "C:\Users\user\AppData\Local\Temp\pip-install-5v2rj3qx\tesserocr_6a01a3c0ee4b4dc6bd1dc39e457777d0\setup.py", line 260, in make_extension`
`      build_args = get_build_args()`
`    File "C:\Users\user\AppData\Local\Temp\pip-install-5v2rj3qx\tesserocr_6a01a3c0ee4b4dc6bd1dc39e457777d0\setup.py", line 252, in get_build_args`
`      build_args = get_tesseract_version()`
`    File "C:\Users\user\AppData\Local\Temp\pip-install-5v2rj3qx\tesserocr_6a01a3c0ee4b4dc6bd1dc39e457777d0\setup.py", line 216, in get_tesseract_version`
`      raise RuntimeError(error)`
`  RuntimeError: Tesseract library not found in LIBPATH: []`
`  ----------------------------------------`
`WARNING: Discarding ``https://files.pythonhosted.org/packages/66/01/05cdb20f2842993d134a1a52a34f45bfa40cc4b8480cce2cb654e2eff5ed/tesserocr-2.5.2.tar.gz#sha256=9371dd3f6fe3238039c73bfe15bcaf21389f7e75f62bd530a30110149f39b2ae (from https://pypi.org/simple/tesserocr/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I do have Tesseract (installed from conda-forge) on the same env, and I have added the bin folder of the env to PATH in Windows. I am however able to install tesserocr 2.5.1 using `conda install tesserocr`. 

What exactly should I do to install tesserocr from pip? Or can the conda package be updated?

----
python = 3.9
conda environment
Windows 10 64x

---
## Update
Just created a new env with python 3.10 and it is unable to install tesserocr with conda, and same error with pip.

**Comment by zdenop** [comment]
Did you follow instruction for building tesserocr on windows?

**Comment by joseavegaa** [comment]
No, I did not. The recommended way to install tesserocr on Windows is through conda; however the package version there is outdated, being 2.5.1, and it isn't compatible with Python 3.10. I also tried to install it on an environment with Python 3.9 and it works with conda, but only for version 2.5.1. The installation through pip fails with the above error for Python 3.9 or 3.10. 

Is it possible to update the package at [conda-forge](https://anaconda.org/conda-forge/tesserocr) to the latest version for easy installation? Or to update the wheel on pip?

**Comment by zdenop** [comment]
Tesserocr wheel on windows is not supported for several years already : https://github.com/simonflueckiger/tesserocr-windows_build/releases

I see https://anaconda.org/conda-forge/tesserocr/files there is support for python 3.9, but when I check it there are no tesseract DLLs, so IMO it won't work.

So the only way is to follow https://github.com/sirfz/tesserocr/blob/master/Windows.build.md

**Comment by joseavegaa** [comment]
As using `conda install tesserocr` is no longer the recommended method to install tesserocr on Windows 10/11, and it doesn't work with python >= 3.10.0, [README.rst](https://github.com/sirfz/tesserocr/blob/master/README.rst) should be change to indicate that the only way to get it working is through a built from source. 

Otherwise, it would be awesome to update [tesserocr](https://github.com/conda-forge/tesserocr-feedstock) in the conda-forge to the latest version and keep the README file as is, still recommending to install the package through conda.

**Comment by izahn** [comment]
I'm working on updating the conda-forge build in https://github.com/conda-forge/tesserocr-feedstock/pull/16 and having problems with the windows build. If someone can help fix the windows build there that would be awesome! Otherwise I'm going to try to drop the windows version from conda-forge so we can update to the latest release on other platforms.

**Comment by sirfz** [comment]
> I'm working on updating the conda-forge build in [conda-forge/tesserocr-feedstock#16](https://github.com/conda-forge/tesserocr-feedstock/pull/16) and having problems with the windows build. If someone can help fix the windows build there that would be awesome! Otherwise I'm going to try to drop the windows version from conda-forge so we can update to the latest release on other platforms.

@zdenop it seems the new Windows build procedure you introduced broke the [conda-forge tesserocr build](https://github.com/conda-forge/tesserocr-feedstock). Original tesserocr-feedstock maintainer doesn't seem to be active anymore so maybe you have a few pointers for @izahn to make his life easier?

**Comment by zdenop** [comment]
@sirfz : I am not sure what do you mean with my procedure broke the conda-forge tesserocr build.... Python3.9 changed behavior on Windows and I just make the procedure for tesserocr on windows (e.g. build receipts for python3.8 and below will not work with python 3.9 and above on windows in case of wrapping dll). 

I do not see any log report with an exact error message (https://github.com/conda-forge/tesserocr-feedstock/pull/16/checks?check_run_id=6216185267 is OK and [actions ](https://github.com/conda-forge/tesserocr-feedstock/actions) are ok too...), so I can not help (I am not conda user).

**Comment by izahn** [comment]
I think I fixed the conda-forge windows build, hopefully we are all set there. Thanks for your help!

**Comment by sirfz** [comment]
Thank you @izahn for your effort, we're back on conda-forge!

@zdenop I just saw the issue started when the Windows-related changes were introduced (it only affected conda windows build). I'm not a conda user either so I'm glad izahn stepped in to help us out.
