### ISSUE TITLE
Cant install tesseocr with pip -r

### ISSUE THREAD

**Issue by xkrt** [sirfz/tesserocr#29]
Hi, I want to install tess with `pip insatll -r requirements.txt` (in running tests with tox actually), but this scenario doesnt work. See:

```
$ virtualenv test
$ cd test/
$ source bin/activate
(test) $ echo Cython >> requirements.txt
(test) $ echo tesserocr >> requirements.txt
(test) $ pip install -r requirements.txt
```

I got error:
```
Collecting Cython (from -r requirements.txt (line 1))
  Using cached Cython-0.25.2-cp35-cp35m-manylinux1_x86_64.whl
Collecting tesserocr (from -r requirements.txt (line 2))
  Using cached tesserocr-2.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ag5vqu0y/tesserocr/setup.py", line 11, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ag5vqu0y/tesserocr/
```

I'm Python newbie, but I think this issue maybe due to lack of `setup_requires` or `install_requires` in https://github.com/sirfz/tesserocr/blob/master/setup.py?

**Comment by sirfz** [comment]
`pip install -r` does not guarantee the order of modules installation. In your case, it's trying to install tesserocr before installing Cython. You can try one of the workarounds suggested [here](http://stackoverflow.com/questions/5394356/how-to-specify-install-order-for-python-pip).

**Comment by xkrt** [comment]
@sirfz sorry, can you please read this issue https://github.com/pypa/pip/issues/2478, especially this comment https://github.com/pypa/pip/issues/2478#issuecomment-78932106 with answer
my issue not on the same topic?

**Comment by sirfz** [comment]
Yes, those are exactly what's happening in your case as far as I understand. You must install Cython before installing tesserocr.

Cython is a setup-requirement, not a runtime-requirement, so `pip install tesserocr` will not install Cython for you.

**Comment by xkrt** [comment]
As far I understand this comment https://github.com/pypa/pip/issues/2478#issuecomment-85767024 tesserocr should setup_requires Cython with "some lazy-import glue", because it impossible run setup.py without Cython

**Comment by sirfz** [comment]
I've already implemented this in the [tesseract4](https://github.com/sirfz/tesserocr/tree/tesseract4) branch. Not sure how well pip plays with `setup_requires` though.

You can try it out by switching to that branch and `pip install .` from the repo's root directory.

**Comment by xkrt** [comment]
Yes, this works for me:
```
$ virtualenv test
$ cd test/
$ source bin/activate
$ echo Cython >> requirements.txt
$ echo -egit+https://github.com/sirfz/tesserocr/@tesseract4#egg=tesseocr >> requirements.txt
$ pip install -r requirements.txt
```
Thanks!

**Comment by xkrt** [comment]
@sirfz is it possible backport your setup.py from tesseract4 branch to master? or publish current version of tesseract4 branch to pypi?
