### ISSUE TITLE
Plans for Python 3.10

### ISSUE THREAD

**Issue by mobvarun** [sirfz/tesserocr#291]
Is there any plan to release a new build for Python >= 3.10 for tesserocr, as the current build is not supported in Python 3.10.

**facing exception while installing through pip.**
**Python Version # 3.10.1**

**Comment by sirfz** [comment]
I don't see any reason why it wouldn't build with v3.10. Can you share the exception you're getting?

**Comment by joseavegaa** [comment]
Had problems installing with pip as well, so I had to build from source. Here's the steps I followed:

1. Install Visual Studio 2022 with C++ ([available here](https://visualstudio.microsoft.com/vs/features/cplusplus/))
2. Install CMake ([available here](https://cmake.org/download/))
3. Install Git ([available here](https://git-scm.com/downloads))
4. Install Miniforge. You can also use miniconda or Anaconda. 
5. Create a new empty conda env -> `conda create --name test_tesserocr`
6. Activate the new env -> `conda activate test_tesserocr`
6. Install Python 3.10 -> `conda install python`
7. Install Tesseract -> `conda install tesseract`
8. Check that Tesseract is working with -> `tesseract -v`, which should return the version of tesseract you installed.
9. Once that's done, I followed some of the steps on the Windows build guide [here](https://github.com/sirfz/tesserocr/blob/master/Windows.build.md). Firstly, create a temp new dir with `mkdir C:\temp`
10. Run -> `cd C:\temp`
10. Run `set INSTALL_DIR=C:\temp`
11. Run `set PATH=%PATH%;%INSTALL_DIR%\bin;PATH_TO_YOUR_CONDA_INSTALLATION\envs\test_tesserocr\Library\bin`
12. Initialise a Visual Studio environment with: `call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" x64`
13. Then run: `git clone https://github.com/sirfz/tesserocr.git`
14. `cd tesserocr`
15. `SET VS90COMNTOOLS=%VS140COMNTOOLS%`
16. `SET INCLUDE=%INCLUDE%;%INSTALL_DIR%\include;PATH_TO_YOUR_CONDA_INSTALLATION\envs\test_tesserocr\Library\include`
17. `SET LIBPATH=%LIBPATH%;%INSTALL_DIR%\lib;PATH_TO_YOUR_CONDA_INSTALLATION\envs\test_tesserocr\Library\lib`
18. `pip install -r requirements-dev.txt`
19. `python setup.py build`
20. `python setup.py bdist_wheel`
21. `pip install dist\tesserocr-2.5.2-cp310-cp310-win_amd64.whl`


I have attached a ZIP file with the Wheel I've created for the latest commit of tesserocr on Windows 10 21H2 x64, Python 3.10.2. The process described above simplifies the standard installation proposed on the Windows Build of this repo, and also adds the possibility to work with JPEG and TIFF files, without having to build all of the dependencies. Hope this works for you! 


[tesserocr-2.5.2-cp310-cp310-win_amd64.zip](https://github.com/sirfz/tesserocr/files/7921617/tesserocr-2.5.2-cp310-cp310-win_amd64.zip)

**Comment by arturaugusto** [comment]
Thanks. For which version of tesseract it was compiled?

**Comment by arturaugusto** [comment]
Unfortunately the wheel did not worked for me. It gives dll not found error. I compiled for WinPython 3.10, tesseract 4.1.2 on a Windows 10 following instructions from this repository and now it works.

Sharing my build:

[tesserocr-2.5.2-cp310-cp310-win_amd64.zip](https://github.com/sirfz/tesserocr/files/8015068/tesserocr-2.5.2-cp310-cp310-win_amd64.zip)

**Comment by livezingy** [comment]
I compiled for Python 3.10 + tesseract5.0.1  on  Windows 10  x64 following instructions from this repository.
Sharing my build of tesserocr-2.5.2-cp310-cp310-win_amd64.whl/leptonica-1.83.0.dll/libpng16.dll/tesseract50.dll/zlib.dll.
[tesserocr-2.5.2-cp310-cp310-win_amd64.whl](https://github.com/livezingy/tesserocr_python310)
