### ISSUE TITLE
Installation error - error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by yHalumi** [sirfz/tesserocr#3]
Cython installed via conda.
My compiler version - 
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

The full error message:
running install
running bdist_egg
running egg_info
creating tesserocr.egg-info
writing tesserocr.egg-info/PKG-INFO
writing top-level names to tesserocr.egg-info/top_level.txt
writing dependency_links to tesserocr.egg-info/dependency_links.txt
writing manifest file 'tesserocr.egg-info/SOURCES.txt'
reading manifest file 'tesserocr.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'tesserocr.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
skipping 'tesserocr.cpp' Cython extension (up-to-date)
building 'tesserocr' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/yonatan/anaconda/envs/scraper/include/python2.7 -c tesserocr.cpp -o build/temp.linux-x86_64-2.7/tesserocr.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_14PyPageIterator_20SetBoundingBoxComponents(__pyx_obj_9tesserocr_PyPageIterator*, bool, bool)’:
tesserocr.cpp:3933:25: error: ‘class tesseract::PageIterator’ has no member named ‘SetBoundingBoxComponents’
   __pyx_v_self->_piter->SetBoundingBoxComponents(__pyx_v_include_upper_dots, __pyx_v_include_lower_dots);
                         ^
tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_14PyPageIterator_34GetImage(__pyx_obj_9tesserocr_PyPageIterator*, tesseract::PageIteratorLevel, int, PyObject*)’:
tesserocr.cpp:5195:125: error: no matching function for call to ‘tesseract::PageIterator::GetImage(tesseract::PageIteratorLevel&, int&, Pix*&, int*, int*)’
   __pyx_v_pix = __pyx_v_self->_piter->GetImage(__pyx_v_level, __pyx_v_padding, __pyx_v_opix, (&__pyx_v_left), (&__pyx_v_top));
                                                                                                                             ^
tesserocr.cpp:5195:125: note: candidate is:
In file included from tesserocr.cpp:258:0:
/usr/include/tesseract/pageiterator.h:239:8: note: Pix* tesseract::PageIterator::GetImage(tesseract::PageIteratorLevel, int, int*, int*) const
   Pix* GetImage(PageIteratorLevel level, int padding,
        ^
/usr/include/tesseract/pageiterator.h:239:8: note:   candidate expects 4 arguments, 5 provided
tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_13PyTessBaseAPI_74AnalyseLayout(__pyx_obj_9tesserocr_PyTessBaseAPI*, bool)’:
tesserocr.cpp:15239:83: error: no matching function for call to ‘tesseract::TessBaseAPI::AnalyseLayout(bool&)’
   __pyx_v_piter = __pyx_v_self->_baseapi.AnalyseLayout(__pyx_v_merge_similar_words);
                                                                                   ^
tesserocr.cpp:15239:83: note: candidate is:
In file included from tesserocr.cpp:262:0:
/usr/include/tesseract/baseapi.h:489:17: note: tesseract::PageIterator* tesseract::TessBaseAPI::AnalyseLayout()
   PageIterator* AnalyseLayout();
                 ^
/usr/include/tesseract/baseapi.h:489:17: note:   candidate expects 0 arguments, 1 provided
tesserocr.cpp: In function ‘tesseract::TessResultRenderer* __pyx_f_9tesserocr_13PyTessBaseAPI__get_renderer(__pyx_obj_9tesserocr_PyTessBaseAPI*, __pyx_t_9tesseract_cchar_t*)’:
tesserocr.cpp:15592:88: error: no matching function for call to ‘tesseract::TessHOcrRenderer::TessHOcrRenderer(__pyx_t_9tesseract_cchar_t*&, bool&)’
       __pyx_t_2 = new tesseract::TessHOcrRenderer(__pyx_v_outputbase, __pyx_v_font_info);
                                                                                        ^
tesserocr.cpp:15592:88: note: candidates are:
In file included from tesserocr.cpp:261:0:
/usr/include/tesseract/renderer.h:175:3: note: tesseract::TessHOcrRenderer::TessHOcrRenderer()
   TessHOcrRenderer();
   ^
/usr/include/tesseract/renderer.h:175:3: note:   candidate expects 0 arguments, 2 provided
/usr/include/tesseract/renderer.h:173:16: note: tesseract::TessHOcrRenderer::TessHOcrRenderer(const tesseract::TessHOcrRenderer&)
 class TESS_API TessHOcrRenderer : public TessResultRenderer {
                ^
/usr/include/tesseract/renderer.h:173:16: note:   candidate expects 1 argument, 2 provided
tesserocr.cpp:15635:106: error: no matching function for call to ‘tesseract::TessPDFRenderer::TessPDFRenderer(__pyx_t_9tesseract_cchar_t*&, const char*)’
       __pyx_t_3 = new tesseract::TessPDFRenderer(__pyx_v_outputbase, __pyx_v_self->_baseapi.GetDatapath());
                                                                                                          ^
tesserocr.cpp:15635:106: note: candidates are:
In file included from tesserocr.cpp:261:0:
/usr/include/tesseract/renderer.h:188:3: note: tesseract::TessPDFRenderer::TessPDFRenderer(const char*)
   TessPDFRenderer(const char *datadir);
   ^
/usr/include/tesseract/renderer.h:188:3: note:   candidate expects 1 argument, 2 provided
/usr/include/tesseract/renderer.h:186:16: note: tesseract::TessPDFRenderer::TessPDFRenderer(const tesseract::TessPDFRenderer&)
 class TESS_API TessPDFRenderer : public TessResultRenderer {
                ^
/usr/include/tesseract/renderer.h:186:16: note:   candidate expects 1 argument, 2 provided
tesserocr.cpp:15719:69: error: no matching function for call to ‘tesseract::TessUnlvRenderer::TessUnlvRenderer(__pyx_t_9tesseract_cchar_t*&)’
       __pyx_t_4 = new tesseract::TessUnlvRenderer(__pyx_v_outputbase);
                                                                     ^
tesserocr.cpp:15719:69: note: candidates are:
In file included from tesserocr.cpp:261:0:
/usr/include/tesseract/renderer.h:227:3: note: tesseract::TessUnlvRenderer::TessUnlvRenderer()
   TessUnlvRenderer();
   ^
/usr/include/tesseract/renderer.h:227:3: note:   candidate expects 0 arguments, 1 provided
/usr/include/tesseract/renderer.h:225:16: note: tesseract::TessUnlvRenderer::TessUnlvRenderer(const tesseract::TessUnlvRenderer&)
 class TESS_API TessUnlvRenderer : public TessResultRenderer {
                ^
/usr/include/tesseract/renderer.h:225:16: note:   no known conversion for argument 1 from ‘__pyx_t_9tesseract_cchar_t* {aka const char*}’ to ‘const tesseract::TessUnlvRenderer&’
tesserocr.cpp:15803:72: error: no matching function for call to ‘tesseract::TessBoxTextRenderer::TessBoxTextRenderer(__pyx_t_9tesseract_cchar_t*&)’
       __pyx_t_5 = new tesseract::TessBoxTextRenderer(__pyx_v_outputbase);
                                                                        ^
tesserocr.cpp:15803:72: note: candidates are:
In file included from tesserocr.cpp:261:0:
/usr/include/tesseract/renderer.h:238:3: note: tesseract::TessBoxTextRenderer::TessBoxTextRenderer()
   TessBoxTextRenderer();
   ^
/usr/include/tesseract/renderer.h:238:3: note:   candidate expects 0 arguments, 1 provided
/usr/include/tesseract/renderer.h:236:16: note: tesseract::TessBoxTextRenderer::TessBoxTextRenderer(const tesseract::TessBoxTextRenderer&)
 class TESS_API TessBoxTextRenderer : public TessResultRenderer {
                ^
/usr/include/tesseract/renderer.h:236:16: note:   no known conversion for argument 1 from ‘__pyx_t_9tesseract_cchar_t* {aka const char*}’ to ‘const tesseract::TessBoxTextRenderer&’
tesserocr.cpp:15887:69: error: no matching function for call to ‘tesseract::TessTextRenderer::TessTextRenderer(__pyx_t_9tesseract_cchar_t*&)’
       __pyx_t_6 = new tesseract::TessTextRenderer(__pyx_v_outputbase);
                                                                     ^
tesserocr.cpp:15887:69: note: candidates are:
In file included from tesserocr.cpp:261:0:
/usr/include/tesseract/renderer.h:164:3: note: tesseract::TessTextRenderer::TessTextRenderer()
   TessTextRenderer();
   ^
/usr/include/tesseract/renderer.h:164:3: note:   candidate expects 0 arguments, 1 provided
/usr/include/tesseract/renderer.h:162:16: note: tesseract::TessTextRenderer::TessTextRenderer(const tesseract::TessTextRenderer&)
 class TESS_API TessTextRenderer : public TessResultRenderer {
                ^
/usr/include/tesseract/renderer.h:162:16: note:   no known conversion for argument 1 from ‘__pyx_t_9tesseract_cchar_t* {aka const char*}’ to ‘const tesseract::TessTextRenderer&’
tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_13PyTessBaseAPI_106IsValidCharacter(__pyx_obj_9tesserocr_PyTessBaseAPI*, __pyx_t_9tesseract_cchar_t*)’:
tesserocr.cpp:18170:60: error: ‘class tesseract::TessBaseAPI’ has no member named ‘IsValidCharacter’
   __pyx_t_1 = __Pyx_PyBool_FromLong(__pyx_v_self->_baseapi.IsValidCharacter(__pyx_v_character)); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 2045; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                            ^
tesserocr.cpp:365:36: note: in definition of macro ‘__Pyx_PyBool_FromLong’
 #define __Pyx_PyBool_FromLong(b) ((b) ? __Pyx_NewRef(Py_True) : __Pyx_NewRef(Py_False))
                                    ^
tesserocr.cpp: In function ‘void inittesserocr()’:
tesserocr.cpp:23205:67: error: ‘PSM_RAW_LINE’ is not a member of ‘tesseract’
   __pyx_t_2 = __Pyx_PyInt_From_enum__tesseract_3a__3a_PageSegMode(tesseract::PSM_RAW_LINE); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                   ^
error: command 'gcc' failed with exit status 1

**Comment by sirfz** [comment]
> tesserocr.cpp:3933:25: error: ‘class tesseract::PageIterator’ has no member named ‘SetBoundingBoxComponents’

Looks like a compatibility issue from the looks of it. Are you sure you have tesseract >= 3.02 installed?

**Comment by yHalumi** [comment]
3.03 as much as I understand: 
✗ tesseract -v
tesseract 3.03
 leptonica-1.70
  libgif 4.1.6(?) : libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8 : webp 0.4.0

I also have libtesseract3 installed in the virtualenv (also 3.03).

**Comment by sirfz** [comment]
Alright, just checked [tesseract's git history](https://github.com/tesseract-ocr/tesseract/commit/0e868ef377103c448cfe58d873957f966a53ce28#diff-26210119271f8601904de1dedfc790fa). Looks like `SetBoundingBoxComponents` was added in the most recent commit. Basically, you need to install the latest version (3.04). I'll have to update the README to state it as a requirement (my bad).

Let me know if this works for you.

**Comment by llazzaro** [comment]
I got the same error and it was fixed with tesseract 3.04
