### ISSUE TITLE
ImportError symbol not found in flat namespace '__ZN9tesseract11TessBaseAPID1Ev'

### ISSUE THREAD

**Issue by lokkasl** [sirfz/tesserocr#302]
Hi guys! I have an error in using tesseract, I tried to install it on mac with m1, and the installation is complete successful (screen 1), after that, I built my project which uses tesserorc version 2.5.2, and, after I start the project I have that error, maybe someone solves it — or maybe met it? Thank you in advance.

Tesseract version:

![1](https://user-images.githubusercontent.com/105995531/170358494-4301317c-6795-416c-aa60-7957cdce8f48.png)

Error:

![2](https://user-images.githubusercontent.com/105995531/170358535-201af692-1d54-4b65-85b3-83903bd2a391.png)

Tesserocr version poetry:

![3](https://user-images.githubusercontent.com/105995531/170358585-df826922-a459-4f6d-880d-e11c855dcb2f.png)

**Comment by zdenop** [comment]
That indicate that you Tesserocr  instalation was build against another version of tesseract => you need rebuild Tesserocr.

**Comment by ankurt** [comment]
Thanks for the response here, but how does one "rebuild" tesserocr, a python library?

The best I could think of was:
```
poetry remove tesserocr
poetry add tesserocr
```

Which removes and then reinstalls `tesserocr` however the same error remains. Did you mean rebuild tesseract? In which case we have tried this already as well via `brew reinstall tesseract`. We have found that it works fine on intel chip Macs, and that is the only difference we can find so far. Appreciate any further suggestions!

**Comment by zdenop** [comment]
I would strongly suggest following [instruction](https://github.com/sirfz/tesserocr#installation) (poetry is not listed there).
Also, make sure that you have installed only one version of the tesseract library.

**Comment by isaackatayev** [comment]
I'm having the same issue.

**Comment by isaackatayev** [comment]
Also using M1 Mac.
My solution was to change my interpreter to the system default, as I think `dlopen` had some conflicts with the `virtualenv`.

If you spent more time than me I bet it's possible to solve this by making sure all scripts are using the right interpreter/env. Hope this helped.

**Comment by jsergelen** [comment]
I had the same issue with tesseract 5.3.2. I have installed tesseract with brew install tesseract.

Downgrading tesserocr from 2.6.1 to 2.6.0 solved it for now

**Comment by sirfz** [comment]
Refer to #323, seems like the macosx binary wheels aren't compatible with some folk's systems so you have to build from source.

**Comment by seawind0506** [comment]
> Hi guys! I have an error in using tesseract, I tried to install it on mac with m1, and the installation is complete successful (screen 1), after that, I built my project which uses tesserorc version 2.5.2, and, after I start the project I have that error, maybe someone solves it — or maybe met it? Thank you in advance.
> 
> Tesseract version:
> 
> ![1](https://user-images.githubusercontent.com/105995531/170358494-4301317c-6795-416c-aa60-7957cdce8f48.png)
> 
> Error:
> 
> ![2](https://user-images.githubusercontent.com/105995531/170358535-201af692-1d54-4b65-85b3-83903bd2a391.png)
> 
> Tesserocr version poetry:
> 
> ![3](https://user-images.githubusercontent.com/105995531/170358585-df826922-a459-4f6d-880d-e11c855dcb2f.png)

Also using M1 Mac.
My solution was execute the commands.
Here are the commands I used:
```
# step 1
pip uninstall tesserocr
# step 2
pip install --no-binary :all: tesserocr
```
