### ISSUE TITLE
Pointsize should be returned even if fontname doesn't exist

### ISSUE THREAD

**Issue by rmast** [sirfz/tesserocr#308]
With the LSTM-recognizer only fontsize is made available: https://github.com/tesseract-ocr/tesseract/issues/1074, no fontname is available.

So 
https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx line 897
```
if font_name == NULL:
            return None
```
should be changed to make retrieval of pointsize possible.

**Comment by sirfz** [comment]
Hi @rmast, this looks like a simple change but what would be the effect with non-LSTM recognizers?

**Comment by rmast** [comment]
The change in the PR proposes to always return the wordfontinfo. I have no experience with CUBE, but OEM0 usually gives wordfontinfo. I don't know whether CUBE returns pointsize. Does anyone use CUBE nowadays?
