### ISSUE TITLE
Error while executing Python as a script

### ISSUE THREAD

**Issue by chrizandr** [sirfz/tesserocr#31]
Hi guys, 
I was just expermimenting around with the API and found something that I think is an issue.
Instead of executing a script, the API brings out a weird cursor(something shaped like a plus symbol) and freezes
**Screenshot:**
https://s13.postimg.org/ennhe0e1j/IMG_20170213_113348.jpg

**Steps to replicate:**
This is the script I wrote http://pastebin.com/JbFR7MaG
Instead of doing the normal _**python script.py**_ to execute the script, I first made the script executable by doing **_chmod +x script.py_** .
I then executed the script by doing **_./script.py image.png_**
The script doesn't execute after the import statement and stops with the + shaped cursor.

Is this an issue? Or am I doing something wrong?

Thanks,

**Comment by sirfz** [comment]
You're executing the script as an sh/bash (shell) script instead of python. You need to add an appropriate shebang at the top of your script:

```bash
#!/usr/bin/env python
```

This will run the script in your environment's default python interpreter.

**Comment by chrizandr** [comment]
Sorry, my bad. Closing
