### ISSUE TITLE
tesserocr for tesseract built without OpenMP

### ISSUE THREAD

**Issue by icp-lab-admin** [sirfz/tesserocr#310]
Hello,

I managed to compile tesseract without OpenMP support on a linux box by following the instructions mentioned on this [link](https://tesseract-ocr.github.io/tessdoc/Compiling-%E2%80%93-GitInstallation.html#release-builds-for-mass-production).

Now, I am able to run tesseract from the terminal and also use `pytesseract`. But unfortunately tesserocr is having some issues:

```
Python 3.7.10 (default, Jun  3 2021, 00:02:01)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-13)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tesserocr import PyTessBaseAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libtesseract.so.5: cannot open shared object file: No such file or directory
```

It does say on the tesseract documentations page that one of the effects of disabling OpenMP is: 
> does not use a shared Tesseract library (that makes it possible to run tesseract without installation)

I checked my `release `directory and indeed, there is no file called `libtesseract.so.5`

Does this mean that it's not possible to use tesserocr when tesseract is built without OpenMP support?

This is my output from `tesseract -v` :

```
tesseract 5.1.0
 leptonica-1.82.0
  libjpeg 6b (libjpeg-turbo 2.0.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE4.1
```

**Comment by zdenop** [comment]
You can you tesserocr also without using OpenMP. Problem is that tutorial you followed create static tesseract build by explicitly disabling creating shared library.  Skipped that setting and everything should work as expected.

**Comment by icp-lab-admin** [comment]
so I just need to compile without specifying the `--disable-shared` option?

**Comment by zdenop** [comment]
yes

**Comment by icp-lab-admin** [comment]
perfect, that fixed it. thanks so much for your help!
