### ISSUE TITLE
Segfault when tessdata are missing

### ISSUE THREAD

**Issue by nijel** [sirfz/tesserocr#32]
If you do not have installed tessdata or TESSDATA_PREFIX is wrong, Python with tesserocr segfaults. I think it should rather fail with some error.

The command line tesseract handles this gracefully with error:

```
Error opening data file /invalid/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```

To reproduce this, just set environment variable TESSDATA_PREFIX to non existing directory.

**Comment by sirfz** [comment]
Thank you for reporting this issue. The API would raise a `RuntimeError` when initialized using the `Init*` methods but not when initialized via the class' `__cinit__`. I've pushed a fix to the [tesseract4](https://github.com/sirfz/tesserocr/tree/tesseract4) branch which aligns the behavior with the `Init*` methods (i.e. raise `RuntimeError`).

**Comment by nijel** [comment]
Thanks for fixing this. I'm using PyTessBaseAPI, code is listed here: https://github.com/WeblateOrg/weblate/issues/1356#issuecomment-278393056

**Comment by sirfz** [comment]
Glad you find it useful!
