### ISSUE TITLE
symbol not found in flat namespace

### ISSUE THREAD

**Issue by dickreuter** [sirfz/tesserocr#323]
Unable to import tesserocr on mac m2:

```
Exception has occurred: ImportError
dlopen(/Users/dickr/dev/Poker/.conda/lib/python3.11/site-packages/tesserocr.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN9tesseract11TessBaseAPID1Ev'
  File "/Users/dickr/dev/Poker/poker/tools/screen_operations.py", line 11, in <module>
    from tesserocr import PyTessBaseAPI, PSM, OEM
  File "/Users/dickr/dev/Poker/poker/restapi_local.py", line 8, in <module>
    from poker.tools.screen_operations import take_screenshot
  File "/Users/dickr/dev/Poker/poker/main.py", line 14, in <module>
    from poker.restapi_local import local_restapi
ImportError: dlopen(/Users/dickr/dev/Poker/.conda/lib/python3.11/site-packages/tesserocr.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN9tesseract11TessBaseAPID1Ev'
```

I have the following tesseract installed
```

(base) dickr@NICOLASs-MacBook-Pro ~ % tesseract --version
tesseract 5.3.2
 leptonica-1.83.1
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 3.0.0) : libpng 1.6.40 : libtiff 4.5.1 : zlib 1.2.11 : libwebp 1.3.1 : libopenjp2 2.5.0
 Found NEON
 Found libarchive 3.7.1 zlib/1.2.11 liblzma/5.4.4 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.5
 Found libcurl/8.1.2 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.51.0
(base) dickr@NICOLASs-MacBook-Pro ~ % 


```

**Comment by jebikoh** [comment]
I'm also having this issue. Unfortunately none of the other solutions in other threads seem to be working for me.

Are you also running this on an M1?

**Comment by dickreuter** [comment]
Yes, I'm running it on an M2. It used to work until around a month ago, then suddenly stopped working. Also couldn't get it to work with downgrading.

**Comment by LeeAaronHarris** [comment]
I have been trying to get tessocr working for a few days, but with no luck.

M2 Pro here

**Comment by LeeAaronHarris** [comment]
The above command did not work for me, the relevant information:

clang: error: no such file or directory: 'pip' 
clang: error: no such file or directory: 'install'
clang: error: no such file or directory: 'tesserocr'

and these resulted in a failure to build a wheel

**Comment by dickreuter** [comment]
It worked for me. All good. Problem solved.

**Comment by jebikoh** [comment]
In case anyone runs into this issue in the future and is also using poetry, try this: 

`poetry config --local installer.no-binary tesserocr`

Then just reinstall tesserocr.
