### ISSUE TITLE
Segfault in pixa_to_list

### ISSUE THREAD

**Issue by oswjk** [sirfz/tesserocr#33]
Hi, I've encountered a segfault in `pixa_to_list` and I can reproduce it consistently. I don't have any idea how to fix this though.

This image here will always make tesserocr segfault:
![fail](https://cloud.githubusercontent.com/assets/808235/23068472/7cbc77e0-f52c-11e6-91e1-d77458262d76.png)

This image on the other hand works fine:
<img width="489" alt="success" src="https://cloud.githubusercontent.com/assets/808235/23068473/7cc83a94-f52c-11e6-9328-c33e6715c0a0.png">

The code I'm using for testing is simple:

```python
import tesserocr
from PIL import Image
import sys

print(tesserocr.tesseract_version())
print(tesserocr.get_languages())

png = Image.open(sys.argv[1]).convert('L')

# print(tesserocr.image_to_text(png))

with tesserocr.PyTessBaseAPI() as api:
    api.SetImage(png)
    boxes = api.GetComponentImages(tesserocr.RIL.WORD, True)
    for _, box, _, _ in boxes:
        pad = box['h'] * 0.2
        api.SetRectangle(box['x']-pad, box['y']-pad, box['w']+pad, box['h']+pad)
        text = api.GetUTF8Text().strip()
        confidence=api.MeanTextConf()
        print(text, confidence)

```

Here is a crash report from OS X:  [crashreport.txt](https://github.com/sirfz/tesserocr/files/783398/crashreport.txt)

Here is the output from a succesful run (including version numbers and so on): [success.txt](https://github.com/sirfz/tesserocr/files/783400/success.txt)

I'm using tesseract 3.05.00 which I compiled myself as I had this problem with the 3.04 also and I thought maybe the new version would fix the issue.

Here are the relevant environment variables I used when I executed `python setup.py install` for tesserocr:

```
declare -x CFLAGS="-g -fno-omit-frame-pointer  -UNDEBUG -O0"
declare -x CPPFLAGS="-I/Users/otimpe/dev/tesseract-3.05.00/dist/include"
declare -x DYLD_LIBRARY_PATH="/Users/otimpe/dev/tesseract-3.05.00/dist/lib"
declare -x LDFLAGS="-L/Users/otimpe/dev/tesseract-3.05.00/dist/lib -g"
declare -x TESSDATA_PREFIX="/usr/local/share"
```

**Comment by sirfz** [comment]
Hi, this happened because `GetComponentImages` is returning a `NULL` boxa for this image. I wasn't validating this which caused `pixa_to_list` to run against an invalid pointer. I've added a check for this in all instances where `pixa_to_list` is used to ensure an empty list is returned instead of segfaulting. Thanks for the catch :)

You can test this using the [tesseract4](https://github.com/sirfz/tesserocr/tree/tesseract4) branch.

**Comment by oswjk** [comment]
Hi,

the fixes you made seem to work nicely with tesseract 3.04. :-) Thank you!
