### ISSUE TITLE
No definition found for "tesserocr"

### ISSUE THREAD

**Issue by Ali-Raza12** [sirfz/tesserocr#339]
I have installed tesserocr using pip package but I am not able to see the definitions in VS Code. How can I see the definitions and exlpore the methods available?

**Comment by Alexandros444** [comment]
Same for me, I installed it via the conda command in windows.
I would like to have a documentation anywhere?
Regards Alex

**Comment by Alexandros444** [comment]
Found the Solution in other thread.
https://github.com/sirfz/tesserocr/issues/312
Just download the init.pyi and put it next to the init.py of your tesserocr lib location. Worked perfectly for me. :)
