### ISSUE TITLE
user patterns are not considered

### ISSUE THREAD

**Issue by roman-deep** [sirfz/tesserocr#340]
Hi all, hi @sirfz, 

I am currently try to use user-patterns on the PyTessBaseAPI.

What I've done is to initialize the API with:

```python
with PyTessBaseAPI(path='/usr/share/tesseract-ocr/4.00/tessdata',
                   lang=LANGUAGE,
                   psm=int(psm),
                   oem=int(TOEM)) as api:
```

setting the user patterns file with:

```python
api.SetVariable('user_patterns_file',
                '/home/roman/Dev_d/playground/user_patterns/deu.patterns')
```

Where the user patterns file contains a pattern, e.g.:

```
\A\A\A
```

(which means three characters in capital letters.)

The result, independently ,whether I use the user_patterns_file argument or not, are the same. This brings me to the question if tesserocr supports user (and word) patterns?

My versions:

```
tesserocr 2.6.2
tesseract 5.3.3
 leptonica-1.83.1
  libpng 1.6.34 : zlib 1.2.11
```

An example snippet, the code and the user-pattern file is attached to this message.

Thanks a lot for your help and best wishes,
Roman

```python
import numpy as np
from PIL import Image
import json
import tesserocr
from tesserocr import PyTessBaseAPI, RIL, PSM, OEM
from pathlib import Path


def read_image(input_image):
    image = np.asarray(Image.open(input_image).convert('RGB')) 
    return image


def detect_text(image, psm, whitelist):

    # convert list to PIL.image for reading by tesseract
    img_arr = np.array(image, dtype=np.uint8)
    new_image = Image.fromarray(img_arr)
    
    DPI = '300'
    CONF = 0.5
    LANGUAGE = 'deu'
    TOEM = 0

    box_list = []
    #                                    11                       0
    # with PyTessBaseAPI(lang='deu', psm=PSM.SPARSE_TEXT, oem=OEM.TESSERACT_ONLY) as api:
    with PyTessBaseAPI(path='/usr/share/tesseract-ocr/4.00/tessdata', lang=LANGUAGE, psm=int(psm), oem=int(TOEM)) as api:
        #api.SetImageBytes(image.tobytes(), image.shape[1], image.shape[0], 1, image.shape[1])
        api.SetImage(new_image)
        api.SetVariable("tessedit_char_whitelist", str(whitelist))
        api.SetVariable("user_defined_dpi", DPI)
        # user patterns
        # api.SetVariable('user_patterns_file', '/home/roman/Dev_d/playground/user_patterns/deu.patterns')
        
        boxes = api.GetComponentImages(RIL.WORD, True)
        #print('Found {} textline image components.'.format(len(boxes)))
        for i, (im, box, _, _) in enumerate(boxes):
            # im is a PIL image object
            # box is a dict with x, y, w and h keys
            api.SetRectangle(box['x'], box['y'], box['w'], box['h'])
            text = api.GetUTF8Text()
            text = text.replace("\n", "")
            conf = api.MeanTextConf()
            # beautify data
            data = {
                'text': text,
                'x': box['x'], 
                'y': box['y'],
                'w': box['w'], 
                'h': box['h'],
                'c': conf}
            if conf >= CONF:
                print(u"Box[{0}]: x={x}, y={y}, w={w}, h={h}, "
                "confidence: {1}, text: {2}".format(i, conf, text, **box))
                box_list.append(data)
    
    return box_list


def main():

    print(tesserocr.tesseract_version())
    print(tesserocr.get_languages())


    input_image = '/home/roman/Dev_d/playground/user_patterns/betriebsstaette.png'
    image = read_image(input_image)
    #box_list = detect_text(image, 8, "abcdefghijklmnopqrstuvwxyzäöüABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜß0123456789,.;- ")
    box_list = detect_text(image, 8, "ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜß0123456789")


    #print(f"box list: {box_list}")

if __name__ == "__main__":
    main()
```
![betriebsstaette](https://github.com/sirfz/tesserocr/assets/102257660/d6c35303-0eba-4383-85f3-aa3deb1bcbee)

**Comment by zdenop** [comment]
Your report is quite strange:
1. You states in your report:
> Where the user patterns file contains a pattern, e.g.:
> \A\A\A
> 
> (which means three characters in capital letters.)

but you provide an image that does not fit this pattern. What is the point of this?

2. Your code reads the image as PIL.Image and return is as numpy array (`read_image` function). Then in function `detect_text` you convert numpy array back to PIL.Image.  What is the point of this back-and-forth conversion? How is this related to user patterns file problem?
3. I tested your example image and it is recognized without problem with default settings:
![image](https://github.com/sirfz/tesserocr/assets/574156/98cef371-e137-44d5-b418-094e58c47fb8)

Can you just post the minimum code for reproducing the problem including the image?

**Comment by zdenop** [comment]
Based on [APIExample-user_patterns.html](https://tesseract-ocr.github.io/tessdoc/APIExample-user_patterns.html) I tried to create relevant code (in jupyter notebook to easier show diff in html):

```py
import difflib
import os
import pathlib

tessdata = r"f:\Projects\Community\tessdata"
os.environ["TESSDATA_PREFIX"] = tessdata
import tesserocr

from IPython.display import HTML, display
from PIL import Image

patterns_path = r"f:\Projects\Community\tesseract.test\my.patterns"
image = Image.open("Arial.png")

with tesserocr.PyTessBaseAPI(oem=tesserocr.OEM.LSTM_ONLY) as api: 
    api.SetImage(image)
    api.SetVariable('debug_file', 'tesserocr.debug1.log')
    ret = api.SetVariable("user_patterns_file", pathlib.Path(patterns_path).as_posix())
    print(ret)
    fist_result = api.GetUTF8Text()

with tesserocr.PyTessBaseAPI(oem=tesserocr.OEM.LSTM_ONLY) as api:
    api.SetImage(image)
    api.SetVariable('debug_file', 'tesserocr.debug2.log')
    ret = api.SetVariable("user_patterns_file", pathlib.Path(patterns_path).as_posix())
    print(ret)
    second_result = api.GetUTF8Text()

comparison = difflib.HtmlDiff().make_file(
    fist_result.splitlines(), second_result.splitlines()
)
display(HTML(comparison.replace("Courier", "Consolas")))
display(image)
```

Even the `user_patterns_file` variable is set, it is ignored:

![image](https://github.com/sirfz/tesserocr/assets/574156/f121ee00-4dcc-49f6-ab1f-ac15d62e85e9)

The difference between my Python code and C++API code is that the `user_patterns_file` variable is set during tesseract initialization. I do not see such option in tesserocr.
Is it supported to set config variables at API init?

**Comment by sirfz** [comment]
It's not currently supported (currently `NULL` is passed for `configs` by default in `Init`) but this shouldn't be too complicated to support, will look into it when I have some time (unless someone wants to take this up)

**Comment by sirfz** [comment]
@zdenop I took some time today to work on this and it turns out passing variables/configs via the Init method is actually already supported. You have to pass `init=False` to `PyTessBaseAPI` and then call the `InitFull` method to initialize the tesseract API:

```python
patterns_path = r"f:\Projects\Community\tesseract.test\my.patterns"
image = Image.open("Arial.png")

with tesserocr.PyTessBaseAPI(init=False) as api:
    api.InitFull(oem=tesserocr.OEM.LSTM_ONLY, variables={"user_patterns_file": pathlib.Path(patterns_path).as_posix()})
    api.SetImage(image)
    fist_result = api.GetUTF8Text()
```

Indeed the output is different in my test.

I'm about to push a PR which allows passing configs/variables directly to the initializer so this could be possible:

```python
patterns_path = r"f:\Projects\Community\tesseract.test\my.patterns"
image = Image.open("Arial.png")

with tesserocr.PyTessBaseAPI(oem=tesserocr.OEM.LSTM_ONLY, variables={"user_patterns_file": pathlib.Path(patterns_path).as_posix()}) as api:
    api.SetImage(image)
    fist_result = api.GetUTF8Text()
```
