### ISSUE TITLE
Allow to show tesseract and leptonica messages (easily)

### ISSUE THREAD

**Issue by zdenop** [sirfz/tesserocr#348]
Be default messages from leptonica and tesseract are [silenced ](https://github.com/sirfz/tesserocr/blob/259922cd5e3f7892daf2a6ad3b4241820fd506b1/tesserocr.pyx#L53-L55).

However, when things do not work, it is useful to turn them on. 
Is there a way to set custom Leptonica message severity?

For tesseract I can use `api.SetVariable('debug_file', 'tessocr.log')`, but there is some strange behavior. E.g:

```py
import tesserocr
from PIL import Image

image = Image.open('Arial.png')

with tesserocr.PyTessBaseAPI(oem=tesserocr.OEM.TESSERACT_ONLY) as api:
    api.SetImage(image)
    api.SetVariable('debug_file', 'tesserocr.debug1.log')
    fist_result = api.GetUTF8Text()
    print(fist_result)

with tesserocr.PyTessBaseAPI(oem=tesserocr.OEM.LSTM_ONLY) as api:
    api.SetImage(image)
    api.SetVariable('debug_file', 'tesserocr.debug2.log')
    second_result = api.GetUTF8Text()
    print(second_result)
```

Following code will create only `tesserocr.debug1.log`, but puts there 2 times the same information (Estimating resolution as 487)

**Comment by sirfz** [comment]
Just pushed the changes that expose a new function `set_leptonica_log_level` which allows setting Leptonica's message severity level.

I also did some tests setting the `debug_file` variable and noticed the same issue you described. Once the variable is set on the initial API, it won't be changed with subsequent initialized API instances. In addition, the file itself won't be populated until I exit my ipython session and the buffer is flushed (which I would expect to happen on `api.End()` instead).

Frankly, I tried to experiment with possible changes to see if it would affect this behavior but nothing worked. This looks like an issue with tesseract's API and not the way we're wrapping it. Any thoughts?

**Comment by asottile** [comment]
can we change the default back to silenced?  this was quite a surprised to see a lot of (noisy) output when upgrading `tesserocr` that I was not seeing before!

**Comment by asottile** [comment]
the tesseract cli doesn't spew output either so I don't see your point

**Comment by asottile** [comment]
I cannot imagine anyone that would want the behavior you've changed it to to be the default.  I would expect the api to have a sensible default (like it did).  now every user of your library needs to add two more lines to restore the old desirable behavior.

I think the defaults that the tesseract cli should be a strong indicator that this change is undesirable.  nobody wants an API that sends a bunch of junk output by default

**Comment by sirfz** [comment]
User's of the C++ API would have to do exactly that. However, I agree that in the typical Python dev's use-case it's probably preferable to not have all this output (reminiscent of all the annoying messages spewed by torch/tensorflow for example). I'm not opposed to going back to disabling it, you're the first person to complain tho so I'm not sure people are as bothered. Perhaps you can open a separate issue about it and see if more people are interested
