### ISSUE TITLE
suggested improvement on api.SetRectangle input

### ISSUE THREAD

**Issue by herrxyz** [sirfz/tesserocr#352]
suggestion: api method SetRectangle take tuple as alternative input

crop = (1,2,3,4)
(left, top, width, height) = crop
works:
api.SetRectangle(left, top, width, height)
breaks:
api.SetRectangle(crop)

using current version 2.5.2 from conda-forge

**Comment by sirfz** [comment]
You can `api.SetRectangle(*crop)`
