### ISSUE TITLE
tesserocr 2.7.0 is much noisier than previous versions

### ISSUE THREAD

**Issue by asottile** [sirfz/tesserocr#353]
discussed a bit in #348 -- here's the separate issue

some minimal code to reproduce the problem:

```python
import numpy
import tessdata
import tesserocr

img = numpy.zeros((20, 20))

tessapi = tesserocr.PyTessBaseAPI(
    tessdata.data_path(),
    'eng',
    psm=tesserocr.PSM.SINGLE_LINE,
)

tessapi.SetImageBytes(
    img.tobytes(),
    width=img.shape[1],
    height=img.shape[0],
    bytes_per_pixel=1,
    bytes_per_line=img.shape[0],
)
tessapi.GetUTF8Text()
```

prior to 2.7.0 I get no output, but after 2.7.0 I get some pretty annoying terminal spam by default:

```console
$ python3 t.py
Bottom=0, top=20, base=0, x=0

Total count=0
Min=0.00 Really=0
Lower quartile=0.00
Median=0.00, ile(0.5)=0.00
Upper quartile=0.00
Max=0.00 Really=0
Range=1
Mean= 0.00
SD= 0.00
```

I also get this ~sometimes on shutdown for a different program -- but I haven't been able to make a minimal reproduction of that:

```console
ObjectCache(0x7f12443ae1e0)::~ObjectCache(): WARNING! LEAK! object 0x5634c6dbf0e0 still has count 1 (id .../venv/share/tessdata/eng.traineddatalstm-punc-dawg)
ObjectCache(0x7f12443ae1e0)::~ObjectCache(): WARNING! LEAK! object 0x5634c6e35e40 still has count 1 (id .../venv/share/tessdata/eng.traineddatalstm-word-dawg)
ObjectCache(0x7f12443ae1e0)::~ObjectCache(): WARNING! LEAK! object 0x5634c6e579d0 still has count 1 (id .../venv/share/tessdata/eng.traineddatalstm-number-dawg)
```

I don't think either of these outputs should be shown by default, I prefer the 2.6.3 behaviour

there is a workaround [here](https://github.com/sirfz/tesserocr/issues/348#issuecomment-2145455375) though ideally I wouldn't need to add this to every program using `tesserocr` to silence some *debug*-level messages

I tried using `set_leptonica_log_level` to silence this but as far as I can tell it's not possible to use this function?

```pycon
>>> import tesserocr                
>>> tesserocr.set_leptonica_log_level(tesserocr.LeptLogLevel.ERROR)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Argument 'level' has incorrect type (expected tesserocr.tesserocr.LeptLogLevel, got int)
```

and even with that function working I would then have to require my users to upgrade `tesserocr` to >=2.7.0

**Comment by goto-loop** [comment]
I agree, tesserocr seems to be unnecessarily verbose. I'm a new user and when calling `tesserocr.image_to_text()` with an image, I get `Estimating resolution as 193`, which as far as I can tell is completely irrelevant for me. I would prefer to see this message only when I explicitly enable debug messages.

**Comment by BBC-Esq** [comment]
I'm getting the same ```estimating resolution as...X``` for a thousand page PDF...This is firstly unhelpful, but secondly, interferes with the proper display of the TQDM progress bar I'm trying to implement as these spam messages are pushing the tqdm progress bar off screen...

**Comment by sirfz** [comment]
> Thanks, is a new pypi release coming so that I can pip install?

v2.7.1 is now up on pypi

**Comment by BBC-Esq** [comment]
> > Thanks, is a new pypi release coming so that I can pip install?
> 
> v2.7.1 is now up on pypi

Spent the last three hours trying to build a windows wheel to no avail...Followed your instructions and messaged the other guy at: https://github.com/simonflueckiger/tesserocr-windows_build/releases/tag/tesserocr-v2.7.0-tesseract-5.3.4

Unless/until he responds...Here are the files in his Windows wheel once installed into my ```site-packages``` library:

![image](https://github.com/user-attachments/assets/428f18c2-06c8-4f07-a4ed-b98ab1eba482)

Since the change was so miniscule, is it possible to take one of your wheels' files and replace one of these files?  For example, if your modification to ```tesserocr.pyx``` was a single line...could I replace ```tesseractg53.dll``` in the Windows wheel with one one of your wheels or are they not interchangeable?  Sorry I'm not that familiar with building...

**Comment by BBC-Esq** [comment]
Disregard my prior message.   The windows builds were just updated to support version 2.7.1!
