### ISSUE TITLE
integrations or community examples?

### ISSUE THREAD

**Issue by BBC-Esq** [sirfz/tesserocr#354]
Really impressed with your library.  Surpasses ```pytesseract``` IMHO and I can understand why you saw the need to make it.

Do you put community integrations/examples on your readme like I know some other repositories do?  If so, I just created this repo:

https://github.com/BBC-Esq/Fast-PyOCR

**Comment by sirfz** [comment]
Glad you like it, yes there are a few examples (ported from tesseract's own advanced API examples): https://github.com/sirfz/tesserocr?tab=readme-ov-file#advanced-api-examples

These may be outdated but all API methods should still be valid

**Comment by BBC-Esq** [comment]
I was specifically asking if you ever considered linking examples from other repositories using it like mine, but totally understand if it's not something you're interested in doing.  You do include a lot of examples in the readme, which a lot of repositories don't do actually...

**Comment by BBC-Esq** [comment]
Closed as maintainer not interested...  ;-)

**Comment by sirfz** [comment]
There's a long list of dependents that you can view at https://github.com/sirfz/tesserocr/network/dependents
