### ISSUE TITLE
PSM.OSD_ONLY causes std::out_of_range

### ISSUE THREAD

**Issue by RodrigoTMOLima** [sirfz/tesserocr#358]
Hello!

I'm trying to use Tesseract OCR's OSD functionality, but when using it as described in the repository's documentation, I get an `out_of_range` error.

```
from tesserocr import PyTessBaseAPI, PSM

with PyTessBaseAPI(psm=PSM.OSD_ONLY) as api:
    api.SetImageFile("image.png")
    os = api.DetectOS()
```

I also tried running it as such:

```
from tesserocr import PyTessBaseAPI, PSM, OEM

with PyTessBaseAPI(psm=PSM.OSD_ONLY, oem=OEM.LSTM_ONLY) as api:
    api.SetImageFile("image.png")
    os = api.DetectOrientationScript()
```

Both executions resulted in the following error message:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector<bool>::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 120)
Aborted (core dumped)
```

I'm running this code inside a Docker container with the following image: [jitesoft/tesseract-ocr:5.4.1](https://hub.docker.com/layers/jitesoft/tesseract-ocr/5.4.1/images/sha256-2f89d009a3980cb5eac6ca5fe7f7bc6799b2bc79b211b54c868a52b8e44adad0?context=explore)

The only additional configuration this container has is that I added three `.traineddata` files: por-best, por-fast , and por.

Strangely, the following snippet works exactly as expected without any errors:

```
from PIL import Image
from tesserocr import PyTessBaseAPI, PSM

with PyTessBaseAPI(psm=PSM.AUTO_OSD) as api:
    image = Image.open("image.png")
    api.SetImage(image)
    api.Recognize()

    it = api.AnalyseLayout()
    orientation, direction, order, deskew_angle = it.Orientation()
```

**Comment by sirfz** [comment]
Does `DetectOS` return anything? If it's `None` then I believe `DetectOrientationScript` won't work

**Comment by RodrigoTMOLima** [comment]
> Does `DetectOS` return anything? If it's `None` then I believe `DetectOrientationScript` won't work

Thanks for the quick reply. When executing `DetectOS`, the program crashes with the error message stated above.

**Comment by sirfz** [comment]
Does #136 answer your question?

**Comment by zdenop** [comment]
Please check which `tessdata` type you use (`fast `and `best` do not work for OSD => crash tesserocr). You need to use `traineddata` with legacy models.

**Comment by pavel-denisov-fraunhofer** [comment]
I had the same issue. It got solved with `PyTessBaseAPI(psm=PSM.OSD_ONLY, lang="osd")` in my case.
