### ISSUE TITLE
getUtf8text can not recognize number and Upper letter

### ISSUE THREAD

**Issue by xtt5480446** [sirfz/tesserocr#39]
when i pass a image with letters and numbers to tesserocr,the result show that number and upper letter can not be recognize.
how can i fix this problem?

**Comment by xtt5480446** [comment]
`with PyTessBaseAPI(psm=3) as api:
    api.SetImage(image)
    boxes = api.GetComponentImages(RIL.WORD, True)
    print 'Found {} textline image components.'.format(len(boxes))
    for i, (im, box, _, _) in enumerate(boxes):
        # im is a PIL image object
        # box is a dict with x, y, w and h keys
        api.SetRectangle(box['x'], box['y'], box['w'], box['h'])
        ocrResult = api.GetUTF8Text()
        #ocrResult = api.GetWords()
        conf = api.MeanTextConf()`
my code snap is as above.

**Comment by sirfz** [comment]
Try using the tesseract command-line tool, if you get the same results then it's not a tesserocr issue.
