### ISSUE TITLE
Failed to install Tesserocr 

### ISSUE THREAD

**Issue by ibr123** [sirfz/tesserocr#42]
Hi, i tried to install the Tesseract 4.0 on ubuntu as described on the [website](https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32)
all worked fine except for the the last command **pip install tesserocr** although i already have python 2.7 installed,
im attaching a snapshot of the error that i have when i run the above command
![python](https://cloud.githubusercontent.com/assets/26926171/24915032/b7b8f41e-1ede-11e7-8295-98683b0329b1.png)
Any ideas on how to solve this issue?
Thanks

**Comment by sirfz** [comment]
Hi @ibr123, for Tesseract 4 support you need to install the latest version from the [tesseract4](https://github.com/sirfz/tesserocr/tree/tesseract4) branch. To do so, just clone this repo then `git checkout tesseract4` then `pip install .` to install tesseract from the repo's root directory.

**Comment by ibr123** [comment]
Thanks for your response, when i make git pull to get the files for tesseract4 that you have mentioned 
**git pull https://github.com/sirfz/tesserocr/tree/tesseract4** that generates an error which is 
**fatal: repository 'https://github.com/sirfz/tesserocr/tree/tesseract4/' not found**
and i tried to download the contents of the site manually and copy it to the Bash path but it seems its not possible to copy from windows to Bash (im using windows 10 Bash), so it would save much of time if it was installed directly from the link that you have suggested to the bash, any ideas?
Thanks

**Comment by sirfz** [comment]
You need to clone first then switch branches:

```bash
git clone https://github.com/sirfz/tesserocr.git
cd tesserocr
git checkout tesseract4
pip install .
```

**Comment by ibr123** [comment]
Thanks a lot, that worked....
one question though, some binaries such as text2image, are they suppose to be installed after i finish installing tesseract and tesserocr?

**Comment by sirfz** [comment]
tesserocr only uses tesseract's API interface, no external tools needed.

**Comment by jollysean** [comment]
There is no branch of tesseract4.
Fails:  git checkout tesseract4

**Comment by ibr123** [comment]
@jollysean  yes recently when I install latest of Tesseract the command `git checkout tesseract4` fails, but what I do is that I just skip to the next command directly, which is `pip install .`
