### ISSUE TITLE
error：start >= 0 && start + num <= length_:Error:Assert failed:in file ratngs.cpp, line 321

### ISSUE THREAD

**Issue by xtt5480446** [sirfz/tesserocr#43]
here is my part code:
```python
import sys
from PIL import Image
from tesserocr import PyTessBaseAPI, RIL,iterate_level
import cv2
import numpy as np

def processText(image):
    image = cv2.imread(image)
    iimage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    kernel = np.ones((1, 1), np.uint8)
    #iimage = cv2.dilate(iimage, kernel, iterations=1)
    #iimage = cv2.erode(iimage, kernel, iterations=1)
    cv2.imwrite("7.png", iimage)
    img = cv2.adaptiveThreshold(iimage, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 11, 2)
    cv2.imwrite("8.png", img)
    image = Image.open('8.png')
    im1 = cv2.imread("midResult/init3.jpeg")

    wordList = []
    with PyTessBaseAPI(psm=1) as api:
        api.SetImage(image)
        api.Recognize()
        boxes = api.GetComponentImages(RIL.TEXTLINE, False)
        print 'Found {} textline image components.'.format(len(boxes))
        for i, (im, box, _, _) in enumerate(boxes):
            radioSize = 0.08
            api.SetRectangle(box['x'], box['y'], box['w'], box['h'])
            ocrResult = api.GetUTF8Text()
            conf = api.MeanTextConf()
            print(u"Box[{0}]:x={x},y={y},w={w},h={h},""confidence:{1},text:{2}").format(i, conf, ocrResult, **box)
            cv2.rectangle(im1, (box['x'], box['y']),
                          (box['x'] + box['w'],
                           box['y']+box['h']), (0, 255, 0), 2)
    cv2.imwrite("11.png", im1)

processText("midResult/init3.jpeg")
```

I have debugged that when running into **api.Recognize()**, the error in the title occured. But when i changed the pic paremeter into 3.jpeg, the error disappeared. But these two pictures are nearly the same.
what's wrong with this?
![3](https://cloud.githubusercontent.com/assets/15244749/25277081/db046414-26cf-11e7-91df-35ae5b8b04e7.jpeg)
![init3](https://cloud.githubusercontent.com/assets/15244749/25277080/dac9cf20-26cf-11e7-99a5-76b6746fa9e2.jpeg)

**Comment by sirfz** [comment]
Can you please provide the tesserocr (and tesseract) version you're using? If it's not the latest version from the [tesseract4](https://github.com/sirfz/tesserocr/tree/tesseract4) branch then please test it as well.

The error in the subject looks like an error in the tesseract API and not tesserocr itself, if that's the case then you should report your issue to them directly (with a reproducible example).

It would be much more helpful if you can provide a reproducible example without all the unrelated code, just provide an image file and simple code that triggers the error.

**Comment by xtt5480446** [comment]
i fix that problem by deleting code api.Recognize(),then everything is ok. I am busy with a project at present, so i will provide a reproducible example later.
