### ISSUE TITLE
crash on rotated image

### ISSUE THREAD

**Issue by reubano** [sirfz/tesserocr#5]
```
reubano@tokpro [~]⚡ convert eurotext.tif -rotate 3 +repage eurotext_ang.tif
reubano@tokpro [~]⚡ tesseract eurotext_ang.tif - -psm 0 
Orientation: 0
Orientation in degrees: 0
Orientation confidence: 20.66
Script: 1
Script confidence: 39.58
```

```python
image = Image.open('eurotext_ang.tif')

with PyTessBaseAPI(psm=PSM.AUTO_OSD) as api:
    api.SetImage(image)
    api.Recognize()
    it = api.AnalyseLayout()
    it.Orientation()
```

output
```python
AttributeError: 'NoneType' object has no attribute 'Orientation'
```

**Comment by sirfz** [comment]
[`AnalyseLayout`](https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx#L1736) returns:
> Page iterator or None on error or an empty page.

So you need to check if the returned value is not None before calling `Orientation`.

**Comment by reubano** [comment]
Right, `it` is `None`. But rotating an image 3 deg shouldn't cause that to happen correct?

**Comment by reubano** [comment]
Also, just tested via the `c-api` and it works fine. So not an issue with `tesseract` or `leptonica`.

**Comment by sirfz** [comment]
If you look at the source code linked in my previous comment, all it does is call the respective `AnalyseLayout` C function and if its value is `NULL` returns `None`. Is it possible that you're getting `None` due to the issue in #4?

**Comment by reubano** [comment]
See https://github.com/sirfz/tesserocr/issues/5#issuecomment-220117490

Here's part of the working code if it helps

```python
def get_native_orientation(tesseract, leptonica, api, path, mode=PAGE_MODE):
    tesseract.TessBaseAPISetPageSegMode(api, mode)
    pix = leptonica.pixRead(path)
    tesseract.TessBaseAPISetImage2(api, pix)

    if tesseract.TessBaseAPIRecognize(api, None):
        leptonica.pixDestroy(byref(pix))
        tesseract.TessBaseAPIDelete(api)
        raise Exception('Tesseract recognition failed')

    it = tesseract.TessBaseAPIAnalyseLayout(api)
    orientation, direction, line_order = c_int(), c_int(), c_int()
    skew = c_float()

    tesseract.TessPageIteratorOrientation(
        it, byref(orientation), byref(direction), byref(line_order),
        byref(skew))

    return orientation.value, direction.value, line_order.value, skew.value
```

**Comment by sirfz** [comment]
Alright, the problem seems to be with the usage of `PIL.Image`. If you use the `SetImageFile` method instead of `SetImage` it'll work. I'm going to debug this issue and apply the appropriate fix.

**Comment by sirfz** [comment]
Hey could you please test with the latest commit? It should now work as expected with PIL images.

**Comment by reubano** [comment]
it works, thanks!

**Comment by reubano** [comment]
Another issue tho. It works for 3deg and 4deg, but crashes when the image is rotated 5deg.

**Comment by sirfz** [comment]
With the 5 degrees tilt, tesseract fails to detect any text in the image (try `tesseract eurotext_ang.tiff -`) so this isn't related to the issue we fixed here.

Note that the `tesseract` executable applies a different logic to output the orientation when `-psm 0` is specified. In our case we're using `psm 1` and given that no text is detected, `AnalyseLayout` returns `None`.

Unfortunately, I didn't expose the `DetectOS` which is used in tesseract 3.04.00 to write the same logic in `tesserocr`. The nice thing is they made it much easier to do in tesseract 3.04.01 but implementing it will break compatibility with version 3.04.00 so I'm gonna see how to do it properly while maintaining backward compatibility (preferably with 3.02 as well).

**Comment by reubano** [comment]
So does that explain why running the script with psm=0 returns null
results? I wasnt aware of 'DetectOS' but it looks like it may be what i
need.

__________________________________________
Reuben Cummings
Founder & Managing Director, Nerevu Development
https://www.linkedin.com/company/nerevu

+255 756 477 319 (vodacom)
+255 789 477 319 (airtel)
+254 703 576 035 (safaricom)
+1 (234) 738-2266 (whatsapp)

**Comment by sirfz** [comment]
Yes certainly does, seems that `AnalyseLayout` always returns None when psm is 0. Orientation needs to be detected differently when psm is 0, I'm going to work on it with support for 3.04.00 and the newer 3.04.01 as well, will let you know once it's ready.

**Comment by reubano** [comment]
[Solved it](https://github.com/tesseract-ocr/tesseract/issues/326#issuecomment-220719577)!

**Comment by redstoneleo** [comment]
Hello, Anyone can help with my conversion ?
https://stackoverflow.com/questions/60166781/ctypesconvert-the-c-c-tesseract-ocr-code-to-python
