### ISSUE TITLE
'tesserocr.PyPageIterator' object has no attribute 'GetUTF8Text'

### ISSUE THREAD

**Issue by mm-manu** [sirfz/tesserocr#50]
Hello,
I'm iterating over RIL.BLOCK and want to get the text of each BLOCK.
In tesserocr.pyx line 390 the following is written:
```
        >>> for e in iterate_level(api.AnalyseLayout(), RIL.WORD):
            ...     word = e.GetUTF8Text()
```
Unfortunately this does not work. I get the following error:

> AttributeError: 'tesserocr.PyPageIterator' object has no attribute 'GetUTF8Text'

**Comment by sirfz** [comment]
This is a mistake in the documentation. You can get words using something similar to [this example](https://github.com/sirfz/tesserocr#iterator-over-the-classifier-choices-for-a-single-symbol):

```python
from tesserocr import PyTessBaseAPI, RIL, iterate_level

api = PyTessBaseAPI()
api.SetImageFile('/path/to/image')
api.Recognize()

iterator = api.GetIterator()
for w in iterate_level(iterator, RIL.WORD):
    print w.GetUTF8Text(RIL.WORD)
```
