### ISSUE TITLE
Publish Wheels

### ISSUE THREAD

**Issue by cancan101** [sirfz/tesserocr#54]
Ideally with static libraries included so that all that is required for installation in `pip`.

**Comment by sirfz** [comment]
I'd need to include tesseract and leptonica binaries in the wheels for this to work properly but I'm not sure what the best way to do this is to be honest. I'll need to look into it, any pointers are appreciated of course.

**Comment by cancan101** [comment]
This project does something similar: https://github.com/skvark/opencv-python/

**Comment by simonflueckiger** [comment]
@cancan101 what version of Python are you using? See if the wheels I added [here](https://github.com/sirfz/tesserocr/issues/19#issuecomment-335875716) work for you.

**Comment by cancan101** [comment]
@simonflueckiger Sorry it took me a while to looking the wheels. Unfortunately I am using Python 3.5 on linux (and those looks like windows wheels).

**Comment by simonflueckiger** [comment]
I see... not really sure how to package the libraries up in linux. As an alternative, you can use `conda install -c mcs07 tesserocr` if you have the conda package manager installed (i recommend [Miniconda](https://conda.io/miniconda.html)). For Python 3.5 you can download the Miniconda Python 3.6 installer (or even 2.7, doesn't really matter) and create a Python 3.5 environment with `conda create -n py35 python=3.5`, then switch to it with `source activate py35`. Finally install tesserocr with the command mentioned before.
Tell me if using conda is not an option for you. I know that this is not a solution to this issue, but maybe it can still be of help to you or someone else stumbling upon this.

[![Anaconda-Server Badge](https://anaconda.org/mcs07/tesserocr/badges/installer/conda.svg)](https://conda.anaconda.org/mcs07)

**Comment by mcs07** [comment]
@simonflueckiger I don't think my conda recipe for tesserocr is working properly on Windows yet, it's still a work in progress...

**Comment by simonflueckiger** [comment]
@mcs07 yes, for windows he can use my recipe `conda install -c simonflueckiger tesserocr`
But as I understand it, @cancan101 is workin with linux at the moment, so he should be fine with your recipe, right?

**Comment by mcs07** [comment]
Ah oops yes, I skimmed over the thread too quickly!

**Comment by stefan6419846** [comment]
Has there been any progress on getting static wheels to work on Linux?
