### ISSUE TITLE
'str' object has no attribute 'fromat'

### ISSUE THREAD

**Issue by VasLem** [sirfz/tesserocr#56]
Misspelling error, from the lines below:
```
import tesserocr
tesserocr.PSM()
```

**Comment by sirfz** [comment]
PSM is an enum and cannot be initialized. You can only use its values as `tesserocr.PSM.PSD_ONLY` for example. However, you did find a bug as it's supposed to raise a different error which has now been fixed in the master branch.

**Comment by VasLem** [comment]
I was searching how I can use the command line page segmentation modes by duck typing :P. Thanks for the quick response.
