### ISSUE TITLE
image_to_text recognizes more text than using the PyTessBaseAPI

### ISSUE THREAD

**Issue by VasLem** [sirfz/tesserocr#57]
This is kind of weird .  The part of the document I am trying to ocr is the following:
![image](https://user-images.githubusercontent.com/18720200/27384387-574bddd0-5697-11e7-89f0-6b689edd0c67.png)

image_to_text produces the folowing:
```
Test Results

Latest Result

 

, SINGAPORE

Parameter Unit Outcome

08-Jun-2017

17-021396-01
Viscosity @ 50°C cSt 367.8
Density @ 15°C kg/m® 989.0
Sulphur % (m/m) 2.69
Flash Point °C >67.0
Acid Number mg KOH /g 0.09
Total Sediment Ace. % (m/m) 0.05
Micro Carbon Residue % (m/m) 15.34
Pour Point °C <21
Water content % (V/V) 0.39
Ash % (m/m) 0.039
Vanadium mg/kg 112
Sodium mg/kg 21
Calcium mg/kg 9
Zinc mg/kg <1
Phosphorus mg/kg <1
Iron mg/kg 31
Nickel mg/kg 35
Magnesium mg/kg <1
Potassium mg/kg <1
Silicon mg/kg 11
Aluminium mg/kg 7
Aluminium + Silicon mg/kg 18
Quantity MT
Quantity loss/gain MT
CCAl 850
Net Specific Energy MJ/kg 40.18
```
When I perform the same operation using the PyTessBaseAPI , Iget the following bounding boxes:
![image](https://user-images.githubusercontent.com/18720200/27384613-31903b76-5698-11e7-9bc2-564fccf6cd37.png)

The problem is that I need the relative position of the values, so that to extract a key to value inference, whle performing the same action for multiple documents, so i can not (and dont want to) manually interfere. I can not understand why 7 and 9 are not recognized. To add to this, I got a lot fewer results when I set the segmentation mode to AUTO (this result is given using SPARSE_TEXT).  Is there a solution to this absurd problem or is it a matter of luck?

**Comment by sirfz** [comment]
Can you share your code please? How are you mapping the text to their respective blocks? Check my answer in #59 it seems that using `GetIterator` is better for getting the text and image at a given level than using `GetComponentImages` (in case that's what you're using).
