### ISSUE TITLE
Failed to recognize text  of boxes returned by GetComponentImages()

### ISSUE THREAD

**Issue by czchao** [sirfz/tesserocr#59]
<img width="112" alt="sample10" src="https://user-images.githubusercontent.com/4580068/27822861-bb187f34-60d9-11e7-8269-1e65e27715c7.png">
I want to recognize every word in the image above. When I run the code 

```
from PIL import Image
from tesserocr import PyTessBaseAPI, RIL

image = Image.open('sample10.png')
with PyTessBaseAPI() as api:
    api.SetImage(image)
    boxes = api.GetComponentImages(RIL.WORD, True)
    for i, (im, box, _, _) in enumerate(boxes):
        # im is a PIL image object
        # box is a dict with x, y, w and h keys
        api.SetRectangle(box['x'], box['y'], box['w'], 120)
        print api.GetUTF8Text()
```
It outputs nothing. But following code works. Why?

```
from PIL import Image
from tesserocr import PyTessBaseAPI, RIL

image = Image.open('sample10.png')
with PyTessBaseAPI() as api:
   api.SetImage(image)
   print api.GetUTF8Text()
```

**Comment by zmwang-GitHub** [comment]
I have the same issue with more complicated documents. When I OCR the whole text, it can generate the correct text results. 

When I try RIL.WORD, RIL.TEXTLINE, RIL.PARA, RIL.BLOCK, the text output is sparse and quite similar to each other.

**Comment by sirfz** [comment]
Hello,

Indeed, in your example `GetUTF8Text()` is yielding an empty string although `GetThresholdedImage().show()`  shows the correct crop for each word.

However, this [example](https://github.com/sirfz/tesserocr#iterator-over-the-classifier-choices-for-a-single-symbol) gives you what you want:

```python
from PIL import Image
from tesserocr import PyTessBaseAPI, RIL, iterate_level

image = Image.open('sample10.png')

with PyTessBaseAPI() as api:
    api.SetImage(image)
    api.Recognize()
    ri = api.GetIterator()
    for r in iterate_level(ri, RIL.WORD):
        # rectangle
        print r.BoundingBox(RIL.WORD)
        # text
        print r.GetUTF8Text(RIL.WORD)
```
