### ISSUE TITLE
tesserocr fails to detect Tesseract 4

### ISSUE THREAD

**Issue by Belval** [sirfz/tesserocr#60]
I compiled Tesseract 4 from source and tried it from the command line (it works). Executable is in /usr/local/bin, library is in /usr/local/lib.

    export LD_LIBRARY_PATH=/usr/local/lib

tesserocr will still load Tesseract 3 which shouldn't be on my system anymore according to apt-get.

**Comment by Kankroc** [comment]
Digging a bit deeper: the Tesseract version is set during setup.py execution. Therefore reinstalling was necessary. Unfortunately it only popped another error:

    /tesserocr.cpython-35m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num

**Comment by Kankroc** [comment]
I found the solution, I'll create a PR tonight.

In case someone experiences the same issues, the problem lies with tesserocr being compiled without the OpenMP flag for gcc.

Adding those two lines in the `setup.py` file solves the problem

    build_args['extra_compile_args'] = ['-std=c++11', '-fopenmp'] (line 132)
    build_args['extra_link_args']=['-fopenmp'] (line 133)

**Comment by Kankroc** [comment]
Okay so I did some troubleshooting and I think I figured *some* stuff.

The `path` parameter or the PyTessBaseAPI seems to be overriden by the environnement variable TESSDATA_PREFIX, even if said var is an empty string.

For example, both
    api = PyTessBaseAPI()

and

    api = PyTessBaseAPI(path='/usr/local/') 

will return `RuntimeError: Failed to init API, possibly an invalid tessdata path?`

While setting the environnement variable to `/usr/local/` will make it work (if that's where you tessdata/ folder is).

I'll try to make a Pull Request that fixes this tonight.

**Comment by Kankroc** [comment]
Here's what I did:

1. Clean Archlinux installation (the problem was spotted on an Ubuntu machine, hopefully that won't have any effects on the issue)
2. Git clone & build the very last version of Leptonica
3. Git clone & build the very last version of Tesseract
4. Git clone & `python3 setup.py install` tesserocr
5. Editing setup.py to make it use Tesseract v4
6 `python3 setup.py install`

Observations:
- If tessdata is in the default folder, everything works
- If tessdata is in another folder, and TESSDATA_PREFIX is set to said folder, it works
- If tessdata is in another folder, TESSDATA_PREFIX is empty, and no `path` parameter is given it doesn't work (obviously)
- If tessdata is in another folder, TESSDATA_PREFIX is empty, but the `path` parameter is 
 given it doesn't work (the problem)

Unfortunately, working with the Cython code seems to indicate a problem on Tesseract's end and not Tesserocr. The passed path argument is right in the 

    cdef int ret = self._baseapi.Init(path, lang, oem, configs, configs_size, vars_vec, vars_vals, set_only_non_debug_params)

call.

**Comment by eromoe** [comment]
Similar error on ubuntu 14.04.

apt-get version not match `Requires libtesseract (>=3.04) and libleptonica (>=1.71)`, so I build the lastest version of Leptonica and Tesseract.

**Comment by Kankroc** [comment]
@eromoe You have to

1. Uninstall all previous Tesseract and Leptonica version
2. Build Leptonica 1.73
3. Build Tesseract 4
4. `pip uninstall tesserocr` If it was already installed
5. `pip install tesserocr` <- This is the important bit (and the one I didn't understand) you have to reinstall tesserocr for it to use Tesseract 4.
6. Make sure you have a tessdata folder and declare an environnement variable for it for me it was `export TESSDATA_PREFIX=/usr/share` but the path could be different for you.

Hopefully that helps

**Comment by eromoe** [comment]
@Kankroc  My problem is `eng.traineddata` missing, there is nothing under `/usr/local/share/tessdata/` after building `Tesseract`.  Tesseract 's building guide include a command `make install-langs`, which not work. 

`tesserocr` did not give the right error message to me , but `pytesseract` did. So I manually downloaded `eng.traineddata`  and moved to `/usr/local/share/tessdata/`,  then `tesserocr` and `pytesseract` both became fine .

**Comment by Kankroc** [comment]
@eromoe  Yeah I had that problem too, probably worth looking into it (`make install-langs` not working) or adding a specific exception in `tesserocr`.

**Comment by sirfz** [comment]
Note that installing tesseract from source does not include tessdata which should be downloaded separately from https://github.com/tesseract-ocr/tessdata. I've pushed a change to show the current tessdata path in the runtime exception to make it easier to debug.

**Comment by redstoneleo** [comment]
From my experience , 
one has to specify the `path `and `lang ` parameters in order to use  `PyTessBaseAPI`
It is said that the default value of  `lang ` is `eng`, but one cannot omit the parameter either .

```
from tesserocr import PyTessBaseAPI

images = [r'C:\Users\i\AppData\Local\Programs\Python\115.jpg']
with PyTessBaseAPI(path='.', lang='eng') as api:
	for img in images:

		api.SetImageFile(img)
		
		print (api.GetBoxText(0))
```

**Comment by Adblu** [comment]
got the same problem. WHen i updated and upgraded ubuntu (sudo apt-get upgrade/update) This error appeard: RuntimeError: Failed to init API, possibly an invalid tessdata path: /usr/share/tesseract-ocr/

**Comment by vivekav-96** [comment]
> Switching to the right branch (my bad) solved that problem, now I get:
> 
> ```
> ('/usr/local/', ['fra', 'osd', 'eng'])
> Traceback (most recent call last):
>     File "test.py", line 11, in <module>
>       with PyTessBaseAPI() as api:
>     File "tesserocr.pyx", line 1144, in tesserocr.PyTessBaseAPI.__cinit__ (tesserocr.cpp:9953)
>     File "tesserocr.pyx", line 1157, in tesserocr.PyTessBaseAPI._init_api (tesserocr.cpp:10129)
>  RuntimeError: Failed to init API, possibly an invalid tessdata path?
> ```
> 
> As the first line shows, I do have fra, eng, osd in my tessdata path...

Can you please explain how you solved the error - **undefined symbol: omp_get_thread_num**
