### ISSUE TITLE
Any Example for Document Segmentation with hOCR output?

### ISSUE THREAD

**Issue by zmwang-GitHub** [sirfz/tesserocr#62]
It seems a bit quite hard to get an example regarding the document layout analysis with tesseract-ocr python binding. 

I want to analyse the pdf document and separate the regions into text and images. But I cannot find the relevant pages/threads regarding this. 

Thanks a lot.

**Comment by sirfz** [comment]
Have you tried the [Iterator over the classifier choices for a single symbol:](https://github.com/sirfz/tesserocr#iterator-over-the-classifier-choices-for-a-single-symbol) example?

You can get both the text and image at the level you want (e.g. `RIL.WORD` for words), the [PyResultIterator](https://github.com/sirfz/tesserocr/blob/v2.2.2/tesserocr.pyx#L964) class offers access to many components at any level.

If you have examples for the C++ APIs, they should be very easily replicated using tesserocr (all examples in the README are from the C++ API examples ported to tesserocr).
