### ISSUE TITLE
Recent commit in Tesseract 4 breaks Tesserocr installation

### ISSUE THREAD

**Issue by Belval** [sirfz/tesserocr#63]
**This only applies to Tesseract 4**

This is an easy problem to solve but people might hit a wall if they aren't aware.

Commit [da03e4e](https://github.com/tesseract-ocr/tesseract/commit/da03e4e9105b6262706d40ef2b4436eae4ebe19f#diff-4376fff11de6717e265623d40f1b0820) added the use of string in the unichar.h header file that is used during compilation by `tesserocr`. Unfortunately (and I'm not sure why, explanations are welcome) the standard library (std) is **not** included. This caused the compiler to throw an error

    In file included from tesserocr.cpp:484:0:
    /usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
    static string UTF32ToUTF8(const std::vector<char32>& str32);
              ^

**Changing**  `static string UTF32ToUTF8(const std::vector<char32>& str32);` **to** `static std::string UTF32ToUTF8(const std::vector<char32>& str32);` **in** `/usr/local/include/tesseract/unichar.h:164` **fixes the problem for me.**

According to a comment that can be seen [here if you scroll a bit](https://github.com/tesseract-ocr/tesseract/commit/aee910a7bfcbe0366806b68dc7f20535764c06d4) Google seems to have a problem with **std::string** vs **string** so while I will open an issue on their repo, I feel it is unlikely that someone will fix it. Therefore I recommend using my "dirty hack".

Anyone with more knowledge than me is very welcome to clarify / propose something else.

**Comment by Belval** [comment]
It was fixed yesterday: https://github.com/tesseract-ocr/tesseract/issues/1045

**Comment by czchao** [comment]
Hi, when I install tesserocr for tesseract4 with command `CPPFLAGS=-DUSING_STD_NAMESPACE pip install tesserocr`, I meet the same problem. The error information is below
```
    In file included from tesserocr.cpp:530:
    /usr/local/include/tesseract/unichar.h:164:10: error: unknown type name 'string'; did you mean 'std::string'?
      static string UTF32ToUTF8(const std::vector<char32>& str32);
             ^
    /usr/include/c++/4.2.1/bits/stringfwd.h:60:33: note: 'std::string' declared here
      typedef basic_string<char>    string;
```
Is my installation command wrong?
