### ISSUE TITLE
2.2.2 release

### ISSUE THREAD

**Issue by darkwinternight** [sirfz/tesserocr#65]
Do you have a schedule for the 2.2.2 release?

**Comment by sirfz** [comment]
I'm mainly waiting for the fix to be amended in #61 but if it's not done by the end of the week I'll apply it and release.

**Comment by darkwinternight** [comment]
Very nice :) Thank you! 

I'm using `2.2.2-rc1` successfully (the `timeout` parameter is great!) and would like to publish the code without a github link in the `requirements.txt`.

**Comment by sirfz** [comment]
[tesserocr v2.2.2](https://pypi.python.org/pypi/tesserocr/2.2.2) released.
