### ISSUE TITLE
tesserocr (tesseract4 branch) failed installation on Python 3.6.2 using untrusted ppa

### ISSUE THREAD

**Issue by fjcamillo** [sirfz/tesserocr#67]
Tried installing the tesseract4 branch on an anaconda environment with python 3.6.2 using an untrusted ppa of tesseract and leptonica from https://launchpad.net/~alex-p/+archive/ubuntu/tesseract-ocr. Unfortunately got this error

(py3) fjcamillo@fjcamillo:~/Documents/OCR/tesserocr$ pip install .
Processing /home/fjcamillo/Documents/OCR/tesserocr
Installing collected packages: tesserocr
  Running setup.py install for tesserocr ... error
    Complete output from command /home/fjcamillo/anaconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-fjdgibp8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u6_oqbfi-record/install-record.txt --single-version-externally-managed --compile:
    Supporting tesseract v4.00.00dev
    Configs from pkg-config: {'include_dirs': ['/usr/include', '/usr/local/include'], 'libraries': ['lept', 'tesseract'], 'library_dirs': ['/usr/local/lib'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}}
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/usr/local/include -I/home/fjcamillo/anaconda2/envs/py3/include/python3.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from tesserocr.cpp:529:0:
    /usr/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
       static string UTF32ToUTF8(const std::vector<char32>& str32);
              ^
    In file included from /usr/include/tesseract/osdetect.h:24:0,
                     from tesserocr.cpp:541:
    /usr/include/tesseract/unicharset.h:241:10: error: ‘string’ does not name a type
       static string CleanupString(const char* utf8_str) {
              ^
    /usr/include/tesseract/unicharset.h:244:10: error: ‘string’ does not name a type
       static string CleanupString(const char* utf8_str, int length);
              ^
    /usr/include/tesseract/unicharset.h: In member function ‘void UNICHARSET::unichar_insert_backwards_compatible(const char*)’:
    /usr/include/tesseract/unicharset.h:265:5: error: ‘string’ was not declared in this scope
         string cleaned = CleanupString(unichar_repr);
         ^
    /usr/include/tesseract/unicharset.h:265:5: note: suggested alternatives:
    In file included from /usr/include/c++/5/string:39:0,
                     from /usr/include/tesseract/unichar.h:25,
                     from tesserocr.cpp:529:
    /usr/include/c++/5/bits/stringfwd.h:74:30: note:   ‘std::__cxx11::string’
       typedef basic_string<char>    string;
                                  ^
    /usr/include/c++/5/bits/stringfwd.h:74:30: note:   ‘std::__cxx11::string’
    In file included from /usr/include/tesseract/osdetect.h:24:0,
                     from tesserocr.cpp:541:
    /usr/include/tesseract/unicharset.h:266:9: error: ‘cleaned’ was not declared in this scope
         if (cleaned != unichar_repr) {
             ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/fjcamillo/anaconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-fjdgibp8-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u6_oqbfi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-fjdgibp8-build/

**Comment by Belval** [comment]
1. Clone `tesserocr` to a directory
2. Edit `setup.py` to add `-DUSING_STD_NAMESPACE` to the build flags
    Line 132, add `-DUSING_STD_NAMESPACE` to the `extra_compile_args`. It should look like this.
     
    `build_args['extra_compile_args'] = ['-std=c++11', '-DUSING_STD_NAMESPACE']`

3. Run `python setup.py install`

I'd advise agains't using this PPA though, I tried it myself and had nothing but problems. In addition, building Tesseract really isn't that hard and save you some file editing.

**Comment by fjcamillo** [comment]
Tried adding '-DUSING_STD_NAMESPACE' but the error persists. Thanks by the way for the fast response.
------------
Also tried, building Tesseract and Leptonica, locally. Was able to install  tesserocr to my python2 environment and it works correctly, using `pip install tesserocr` but the tesseract4 branch on python2 produced the same error and on the hand on the python3 environment the same error shows up, whether its `pip install tesserocr` or `python setup.py install` on the directory.

**Comment by Belval** [comment]
@sirfz might correct me on this, but you shouldn't use the Tesseract 4 branch (I know this is misleading) but master is the right one. Also don't forget to uninstall any previous installation including the one built from source with `sudo make uninstall`.

**Comment by sirfz** [comment]
@Belval that's correct. I'll make sure to delete the tesseract4 branch as it was just there when I implemented support for tesseract 4 before it was pushed to stable.

Note that tesseract 4 support may break at any moment since tesseract 4 is still an alpha version and in active development.

**Comment by fjcamillo** [comment]
Got it installed and working. I think the culprit was an installed libtesseract-dev from the same ppa which was not removed the first time I tried.

Completely removed libs related to tesseract and leptonica and the ppa repo from my machine and rebuilt everything. After that it finally worked. Many thanks for the help!
