### ISSUE TITLE
Build on EC2 fails

### ISSUE THREAD

**Issue by Chanonry** [sirfz/tesserocr#69]
Trying to build a deployment package for Tesser with tesserocr for AWS Lambda on an EC2 instance. Works until I pip install tesserocr - fails to find libraries and tesseract.pc. 

Probably the issue you highlight in the read.me but not my core competence I am afraid.

Brief excerpt of trace:

Collecting tesserocr
  Using cached tesserocr-2.2.2.tar.gz
    pkg-config failed to find tesseract/lept libraries: Package tesseract was not found in the pkg-config search path.
    Perhaps you should add the directory containing `tesseract.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'tesseract' found
    Supporting tesseract v4.00.00
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}}
    Compiling tesserocr.pyx because it changed.
    [1/1] Cythonizing tesserocr.pyx

**Comment by sirfz** [comment]
How did you install tesseract and leptonica? pkg-config should be able to find them if they're properly installed (either with apt/packager manager or compiled from source).

If it helps, the `before_install` section of the project's [`.travis.yml`](https://github.com/sirfz/tesserocr/blob/master/.travis.yml#L13) automates leptonica and tesseract's installation from source (you may want to update the versions tho).

**Comment by Chanonry** [comment]
Compiled from source as per link <https://gist.github.com/barbolo/e59aa45ec8e425a26ec4da1086acfbc7>...

The tesser and leptonica compilation worked fine. Looks like a directory reference is different somewhere? 

Keen to use tesserocr, I have been running tesser as a subprocess but some of the functionality in your api is exactly what I neey

Appreciate the prompt reply !

Andy

**Comment by sirfz** [comment]
try `LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" pip install tesserocr`

**Comment by Chanonry** [comment]
Thanks

**Comment by Chanonry** [comment]
Ok, ran that. Same error, full trace below. 

/usr/local/lib contains 

liblept.so
liblept.so.5
libtesseract.so
libtesseract.so.4
pkgconfig
python2.7
liblept.a
liblept.la
liblept.so.5.0.1
libtesseract.a
libtesseract.la
libtesseract.so.4.0.0

/usr/local/include contains two folders  leptonica and tesseract  each with numerous .h files


the tesseract. pc file as identified by the trace is in "/home/ec2-user/tesseract”

the full trace is ...

(tfenv)[ec2-user@ip-172-31-29-19 tesseract]$ LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" pip install tesserocr
You are using pip version 6.0.8, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting tesserocr
  Using cached tesserocr-2.2.2.tar.gz
    pkg-config failed to find tesseract/lept libraries: Package tesseract was not found in the pkg-config search path.
    Perhaps you should add the directory containing `tesseract.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'tesseract' found
    Supporting tesseract v4.00.00
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}}
    Compiling tesserocr.pyx because it changed.
    [1/1] Cythonizing tesserocr.pyx
Installing collected packages: tesserocr
  Running setup.py install for tesserocr
    pkg-config failed to find tesseract/lept libraries: Package tesseract was not found in the pkg-config search path.
    Perhaps you should add the directory containing `tesseract.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'tesseract' found
    Supporting tesseract v4.00.00
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}}
    building 'tesserocr' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/usr/local/include -fPIC -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-x86_64-2.7/tesserocr.o -std=c++11
    tesserocr.cpp: In function ‘tesseract::TessResultRenderer* __pyx_f_9tesserocr_13PyTessBaseAPI__get_renderer(__pyx_obj_9tesserocr_PyTessBaseAPI*, __pyx_t_9tesseract_cchar_t*)’:
    tesserocr.cpp:21023:124: error: no matching function for call to ‘tesseract::TessPDFRenderer::TessPDFRenderer(__pyx_t_9tesseract_cchar_t*&, const char*, bool&)’
           __pyx_t_7 = new tesseract::TessPDFRenderer(__pyx_v_outputbase, __pyx_v_self->_baseapi.GetDatapath(), __pyx_v_textonly);
                                                                                                                                ^
    tesserocr.cpp:21023:124: note: candidates are:
    In file included from tesserocr.cpp:520:0:
    /usr/local/include/tesseract/renderer.h:189:3: note: tesseract::TessPDFRenderer::TessPDFRenderer(const char*, const char*)
       TessPDFRenderer(const char *outputbase, const char *datadir);
       ^
    /usr/local/include/tesseract/renderer.h:189:3: note:   candidate expects 2 arguments, 3 provided
    /usr/local/include/tesseract/renderer.h:185:16: note: tesseract::TessPDFRenderer::TessPDFRenderer(const tesseract::TessPDFRenderer&)
     class TESS_API TessPDFRenderer : public TessResultRenderer {
                    ^
    /usr/local/include/tesseract/renderer.h:185:16: note:   candidate expects 1 argument, 3 provided
    /usr/local/include/tesseract/renderer.h:185:16: note: tesseract::TessPDFRenderer::TessPDFRenderer(tesseract::TessPDFRenderer&&)
    /usr/local/include/tesseract/renderer.h:185:16: note:   candidate expects 1 argument, 3 provided
    tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_13PyTessBaseAPI_96DetectOrientationScript(__pyx_obj_9tesserocr_PyTessBaseAPI*)’:
    tesserocr.cpp:23326:39: error: ‘class tesseract::TessBaseAPI’ has no member named ‘DetectOrientationScript’
       __pyx_t_1 = (__pyx_v_self->_baseapi.DetectOrientationScript((&__pyx_v_orient_deg), (&__pyx_v_orient_conf), (&__pyx_v_script_name), (&__pyx_v_script_conf)) != 0);
                                           ^
    tesserocr.cpp: In function ‘void inittesserocr()’:
    tesserocr.cpp:34509:69: error: ‘OEM_TESSERACT_LSTM_COMBINED’ is not a member of ‘tesseract’
       __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_LSTM_COMBINED); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 83, __pyx_L1_error)
                                                                         ^
    error: command 'gcc' failed with exit status 1
    Complete output from command /home/ec2-user/tfenv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-wDx4p6/tesserocr/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1I03JV-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/tfenv/include/site/python2.7:
    pkg-config failed to find tesseract/lept libraries: Package tesseract was not found in the pkg-config search path.
    
    Perhaps you should add the directory containing `tesseract.pc'
    
    to the PKG_CONFIG_PATH environment variable
    
    No package 'tesseract' found
    
    
    
    Supporting tesseract v4.00.00
    
    Building with configs: {'libraries': ['tesseract', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}}
    
    running install
    
    running build
    
    running build_ext
    
    building 'tesserocr' extension
    
    creating build
    
    creating build/temp.linux-x86_64-2.7
    
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/usr/local/include -fPIC -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-x86_64-2.7/tesserocr.o -std=c++11
    
    tesserocr.cpp: In function ‘tesseract::TessResultRenderer* __pyx_f_9tesserocr_13PyTessBaseAPI__get_renderer(__pyx_obj_9tesserocr_PyTessBaseAPI*, __pyx_t_9tesseract_cchar_t*)’:
    
    tesserocr.cpp:21023:124: error: no matching function for call to ‘tesseract::TessPDFRenderer::TessPDFRenderer(__pyx_t_9tesseract_cchar_t*&, const char*, bool&)’
    
           __pyx_t_7 = new tesseract::TessPDFRenderer(__pyx_v_outputbase, __pyx_v_self->_baseapi.GetDatapath(), __pyx_v_textonly);
    
                                                                                                                                ^
    
    tesserocr.cpp:21023:124: note: candidates are:
    
    In file included from tesserocr.cpp:520:0:
    
    /usr/local/include/tesseract/renderer.h:189:3: note: tesseract::TessPDFRenderer::TessPDFRenderer(const char*, const char*)
    
       TessPDFRenderer(const char *outputbase, const char *datadir);
    
       ^
    
    /usr/local/include/tesseract/renderer.h:189:3: note:   candidate expects 2 arguments, 3 provided
    
    /usr/local/include/tesseract/renderer.h:185:16: note: tesseract::TessPDFRenderer::TessPDFRenderer(const tesseract::TessPDFRenderer&)
    
     class TESS_API TessPDFRenderer : public TessResultRenderer {
    
                    ^
    
    /usr/local/include/tesseract/renderer.h:185:16: note:   candidate expects 1 argument, 3 provided
    
    /usr/local/include/tesseract/renderer.h:185:16: note: tesseract::TessPDFRenderer::TessPDFRenderer(tesseract::TessPDFRenderer&&)
    
    /usr/local/include/tesseract/renderer.h:185:16: note:   candidate expects 1 argument, 3 provided
    
    tesserocr.cpp: In function ‘PyObject* __pyx_pf_9tesserocr_13PyTessBaseAPI_96DetectOrientationScript(__pyx_obj_9tesserocr_PyTessBaseAPI*)’:
    
    tesserocr.cpp:23326:39: error: ‘class tesseract::TessBaseAPI’ has no member named ‘DetectOrientationScript’
    
       __pyx_t_1 = (__pyx_v_self->_baseapi.DetectOrientationScript((&__pyx_v_orient_deg), (&__pyx_v_orient_conf), (&__pyx_v_script_name), (&__pyx_v_script_conf)) != 0);
    
                                           ^
    
    tesserocr.cpp: In function ‘void inittesserocr()’:
    
    tesserocr.cpp:34509:69: error: ‘OEM_TESSERACT_LSTM_COMBINED’ is not a member of ‘tesseract’
    
       __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_LSTM_COMBINED); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 83, __pyx_L1_error)
    
                                                                         ^
    
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/home/ec2-user/tfenv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-wDx4p6/tesserocr/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1I03JV-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ec2-user/tfenv/include/site/python2.7" failed with error code 1 in /tmp/pip-build-wDx4p6/tesserocr
(tfenv)[ec2-user@ip-172-31-29-19 tesseract]$

**Comment by sirfz** [comment]
This looks like a conflict between multiple tesseract versions (it's trying to compile against tesseract v4.0 but the header files are for an older version). Make sure to remove existing installations before compiling from source.

**Comment by Chanonry** [comment]
I am creating a new EC2 instance before I try each build. So Leptonica and Tesser are just buildt before I pip install tesserocr

A

**Comment by sirfz** [comment]
I did a little digging and it seems that 4.00.00alpha and 4.00.00dev won't work with tesserocr due to a change introduced to support a newer version. You're gonna need to checkout a newer revision of tesseract and install it to use v4. I suggest installing tesseract-ocr/tesseract@f5c18f78c09ab028791c28c638d5cc2f96c6d6fb (before a later commit breaks tesseract API compilation), just make the following changes to you script:

```bash
# clone master
git clone https://github.com/tesseract-ocr/tesseract.git
cd tesseract
# checkout newer revision
git checkout f5c18f78c09ab028791c28c638d5cc2f96c6d6fb
./autogen
...
```

**Comment by Chanonry** [comment]
Thanks, will give it a run

A

**Comment by Chanonry** [comment]
will tesserocr work with version 3.05 ? 

May be easier to install an older stable version ?

Enough for one day.

Cheers

Andy

**Comment by sirfz** [comment]
Yes of course and it's definitely the right way to go (use latest stable version) in production.

**Comment by Chanonry** [comment]
Hey, how’s it going ?

I was back on the case today and between your .yml script, the original script and a bit of tweaking I got tesser 3.05.01 compiled and tesserocr installed.  Not entirely convinced the configuration is 100% but that’s next

Thanks for your help.

Cheers

Andy
