### ISSUE TITLE
build fails on freeBSD

### ISSUE THREAD

**Issue by sansculotte** [sirfz/tesserocr#7]
appearently it does not find the leptonica headers which are in /usr/local/include for BSD systems. so i guess this might be a problem on OSX too.

with pip the issue can be worked around with setting CPPFLAGS:
```
CPPFLAGS=-I/usr/local/include pip install git+https://github.com/sirfz/tesserocr.git
```

setup.py takes an -I paramater:
```
 python setup.py build build_ext -I/usr/local/include
```

with pip:
```
Collecting git+https://github.com/sirfz/tesserocr.git
  Cloning https://github.com/sirfz/tesserocr.git to /tmp/pip-uq2glx-build
Installing collected packages: tesserocr
  Running setup.py install for tesserocr ... error
    Complete output from command /usr/home/[...]/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-uq2glx-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Z6nb_e-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/home[...]/venv/include/site/python2.7/tesserocr:
    /usr/home/ub/work/artfacts-scanner/venv/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '2.0.2-beta' to '2.0.2b0'
      normalized_version,
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.freebsd-10.3-RELEASE-p3-amd64-2.7
    cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -I/usr/local/include/python2.7 -c tesserocr.cpp -o build/temp.freebsd-10.3-RELEASE-p3-amd64-2.7/tesserocr.o
    tesserocr.cpp:248:10: fatal error: 'leptonica/allheaders.h' file not found
    #include "leptonica/allheaders.h"
             ^
    1 error generated.
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/home/[...]/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-uq2glx-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-Z6nb_e-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/home/ub/[...]/venv/include/site/python2.7/tesserocr" failed with error code 1 in /tmp/pip-uq2glx-build
```

**Comment by reubano** [comment]
well it's working for me on macosx, but I'm using macports so the headers are in 'opt/local'.

**Comment by sirfz** [comment]
I've only tested this on GNU Linux (Ubuntu to be specific) but it's certainly worth it to support other platforms as well.

Perhaps I need to search for the location of the headers explicitly before building. Gonna have to look into how this can be done (any input is welcome).

**Comment by sansculotte** [comment]
being no expert on python packaging, ich checked pyzmq, which i know builds on all sorts of systems, for alternative include paths. found them in [setup.cfg.template](https://github.com/zeromq/pyzmq/blob/master/setup.cfg.template) which in turn is included from MANIFEST.in

**Comment by sirfz** [comment]
hey @sansculotte I've updated the setup file to use `pkg-config` (if available) to find library dirs before building (inspired by pyzmq, thanks for that). Otherwise, I'd rather not enforce specific directories to avoid conflict (keep that for the environment to handle).

I'll add your workaround into the README in setup fails to find the directories automatically and the user wants to manually provide them.
