### ISSUE TITLE
Passing binarized image to Tesseract

### ISSUE THREAD

**Issue by uzair08inator** [sirfz/tesserocr#71]
Hello

I am doing binarization using separate algorithm and saving result as PNG and passing it to Tesseract. Since i have binarized it already i want Tesseract to stop applying its binarization (Otsu's) on my binarized image. What is the correct way to pass a binarized image to Tesseract so that it doesnt apply binarization on it?

Thanks
Uzair

**Comment by sirfz** [comment]
This is a tesseract-related question, it's better to ask on Stackoverflow how to do it in tesseract or on tesseract's Github if you don't get an answer on SO.

If this is possible and the required API is not supported by tesserocr then we'll work on it.
