### ISSUE TITLE
Hi, how to save a binary image?

### ISSUE THREAD

**Issue by terminats17** [sirfz/tesserocr#75]
I want tesseract help me change the image to binary, so I can do some deeplearning things to accomplish the ocr work. How can I use this wrapper to get an binary Image?

**Comment by sirfz** [comment]
You can try [`PyPageIterator.GetBinaryImage`](https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx#L612). For example (untested):

```python
from tesserocr import PyTessBaseAPI, RIL

with PyTessBaseAPI() as api:
    api.SetImageFile('path/to/image')
    api.Recognize()
    it = api.AnalyseLayout()
    bin_img = it.GetBinaryImage(RIL.BLOCK)
```
