### ISSUE TITLE
cinttypes not found

### ISSUE THREAD

**Issue by j20120307** [sirfz/tesserocr#76]
python3 setup.py build_ext -I/usr/local/include
Supporting tesseract v4.00.00dev
Configs from pkg-config: {'include_dirs': ['/usr/local/Cellar/leptonica/1.74.4_1/include', '/usr/local/include'], 'library_dirs': ['/usr/local/Cellar/leptonica/1.74.4_1/lib', '/usr/local/lib'], 'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}}
running build_ext
building 'tesserocr' extension
g++ -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -I/usr/local/Cellar/leptonica/1.74.4_1/include -I/usr/local/include -I/usr/local/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c tesserocr.cpp -o build/temp.macosx-10.6-intel-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
In file included from tesserocr.cpp:575:
In file included from /usr/local/include/tesseract/genericvector.h:27:
In file included from /usr/local/include/tesseract/tesscallback.h:22:
/usr/local/include/tesseract/host.h:30:10: fatal error: 'cinttypes' file
      not found
#include <cinttypes>  // PRId32, ...
         ^~~~~~~~~~~
1 error generated.
error: command 'g++' failed with exit status 1

tesseract --version
tesseract 4.00.00alpha
 leptonica-1.74.4
  libjpeg 9b : libpng 1.6.32 : libtiff 4.0.8 : zlib 1.2.8

 Found AVX2
 Found AVX
 Found SSE

g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by sirfz** [comment]
Which tesseract git version is this? I currently have tesseract-ocr/tesseract@3847b7dd742c70b437c806ba5fe712b88132d110 installed successfully.

**Comment by NozomiIto** [comment]
I encoutered the same error `'cinttypes' file not found`, when I use clang like the following on Mac OS X, despite I use https://github.com/tesseract-ocr/tesseract/commit/3847b7dd742c70b437c806ba5fe712b88132d110:
` CC=clang XCC=clang++ CPPFLAGS=-DUSE_STD_NAMESPACE pip install tesserocr`

If I use gcc instead of clang like the following, the error is resolved:
` CC=gcc-6 XCC=g++-6 CPPFLAGS=-DUSE_STD_NAMESPACE pip install tesserocr`

Should I use not clang but gcc on Mac OS X? I still encounter runtime tesserocr.so load error with gcc even after the compilation success, so I wonder if I should use gcc or clang.

**Comment by NozomiIto** [comment]
Finally I succeeded to resolve the `'cinttypes' file not found` error by the following command with Mac and tesseract4:

`CC=clang XCC=clang++ CPPFLAGS="-stdlib=libc++ -DUSE_STD_NAMESPACE -mmacosx-version-min=10.8" pip install tesserocr`

- On my Mac, gcc was used to compile for pip and then caused the runtime .so file open error. So I forcibly use the clang by CC and XCC environment variable.
- But clang still used the gcc standard library header, so I pass `-stdlib=libc++` flag. `-mmacosx-version-min=10.8` is also required to restrict `invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)` error.
- `-DUSE_STD_NAMESPACE` is currently also required to avoid the problem described in https://github.com/sirfz/tesserocr/issues/66.

**Comment by Bolboa** [comment]
@NozomiIto I followed your steps and continue to receive the same error

**Comment by NozomiIto** [comment]
Strange. What I tried this is more than 1 year ago, and I don't remember the detail anymore..
