### ISSUE TITLE
Cannot build on Debian Jessie and below

### ISSUE THREAD

**Issue by domenicrosati** [sirfz/tesserocr#77]
- No tesseract.pc is installed by any tesseract packages on Debian Jessie and below
- Setup.py should be robust enough against missing `.pc` files and provide alternative ways of installing with PIP
- Alternatively, README should be updated with a warning

**Comment by domenicrosati** [comment]
Edit:

I am understanding your README differently now - when you say you may need to manually make on recent versions perhaps you meant ubuntu/debian rather than tesseract.

Perhaps if you jsut made this clearer?

**Comment by sirfz** [comment]
The [requirements](https://github.com/sirfz/tesserocr#requirements) section states the minimum tesseract version required which might not be available in your system's package manager. In this case, you'll have to manually install a newer version of tesseract (instructions link available in the same section as well).

The installer would use your system's environment for finding tesseract but with pkg-config it would be more precise. You can also pass your own environment variables as suggested in the [installation](https://github.com/sirfz/tesserocr#installation) section.
