### ISSUE TITLE
tesserocr links to old tesseract

### ISSUE THREAD

**Issue by macnewby** [sirfz/tesserocr#78]
I used tesseract 3.05 with tesserocr in my python project, but updated it on my mac after deleting the old version with brew install tesseract --HEAD to get the new version tesseract 4.0.
I used pip uninstall tesserocr and reinstalled it, but when I try to use it in python it still seems to link to the old tesseract lib.
Even after reinstalling both tesserocr and tesseract again. What am I missing here?

**Comment by sirfz** [comment]
If it links to 3.05 it means 3.05 is installed. Usually uninstalling all tesseract versions (verify that they're completely removed) and reinstalling the one you need fixes this.

**Comment by sirfz** [comment]
If it links to 3.05 it means 3.05 is installed. Usually uninstalling all tesseract versions (verify that they're completely removed) and reinstalling the one you need fixes this.
