### ISSUE TITLE
RuntimeError: No text returned

### ISSUE THREAD

**Issue by jorgeflorez** [sirfz/tesserocr#80]
Hello,
using the following code, I print the coordinates and text of each word:
* tesseract 3.04.01 leptonica-1.71  libjpeg 8d : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8)
* tesserocr 2.2.1

```
from tesserocr import PyTessBaseAPI
from tesserocr import RIL
from tesserocr import iterate_level
from PIL import Image

DEFAULT_LANGUAGE = "spa"
filePath = "/home/repository/f5a77ee10b8415286347db3324b221.png"

if __name__ == '__main__':
    img = Image.open(filePath)
    tesseract = PyTessBaseAPI(lang=DEFAULT_LANGUAGE)
    tesseract.SetImage(img)
    tesseract.Recognize()
    iterator = tesseract.GetIterator()            
    text = tesseract.GetUTF8Text()
    if ((not text is None) and (text.strip() != "")):
        level = RIL.WORD
        
        for r in iterate_level(iterator, level):
            rect = r.BoundingBox(level)
            wordText = r.GetUTF8Text(level)
            print str(rect) + "-->" + wordText
            
    tesseract.End() 
```
I am getting this error:
```
 File "/home/jorge/workspace/prueba-tes/src/test3.py", line 22, in <module>
    wordText = r.GetUTF8Text(level)
  File "tesserocr.pyx", line 801, in tesserocr.PyLTRResultIterator.GetUTF8Text (tesserocr.cpp:6435)
RuntimeError: No text returned
```
It fails just at the beginning. I checked and r.BoundingBox(level) returns None before r.GetUTF8Text(level) fails.

I would like to know if the way I am doing it is correct. If it is, should I call r.GetUTF8Text(level) only when r.BoundingBox(level) is not None?

This is the image:
![9f5a77ee10b8415286347db3324b221f pdf_3](https://user-images.githubusercontent.com/23032523/33147571-45c8c06e-cf96-11e7-8e2c-83fba3d8272e.png)

Best Regards.

Jorge Flórez

**Comment by sirfz** [comment]
I think it's safe to say that if there's no bounding box, it means there's no text so my answer is yes.
