### ISSUE TITLE
Segmentation Fault(core dumped) when running WordFontAttribute with oem=0

### ISSUE THREAD

**Issue by vatsal28** [sirfz/tesserocr#81]
I have the following piece of code which runs for all the images in a loop and gets the word font attributes for each. It's working fine for some set of images, but it crashes after sometime and gives the error:
```
Segmentation Fault(core dumped)
```

But if I run the code on just the image on which the loop crashed, it works and gives the output for some images, but again gives the same error for some.
The code is : 

```
for image in image_list:
	with PyTessBaseAPI(oem=0) as api:
		image1= PIL.Image.open(path+image)
		api.SetImage(image1)
		api.Recognize()
		iterator = api.GetIterator()
		if iterator.WordFontAttributes() is None:
			print "None"	
```

I'm running this on Ubuntu 14.04, with Python 2.7 and Tesseract 4.00

**Comment by sirfz** [comment]
Please provide an example image in order to reproduce.

**Comment by vatsal28** [comment]
It works fine with one single image, but when running on multiple images (scanning a folder with images to get the list and then running it) , it gives the error, so you can use any image you want, but it will work for a single image.

**Comment by sirfz** [comment]
Since the code fails at some point in the loop, it's likely that the image at that specific step was the culprit so it would be good to identify this image and debug the problem with it.

**Comment by vatsal28** [comment]
I thought so too, but then I removed that image and tried it again, still got the same error after some time.
I've repeated this exercise multiple times, each time deleting the image where the crash happened. But there's not specific pattern in the images.
Also, if I run this on just that image, it works. Is there anything I need to change in the code?

**Comment by sirfz** [comment]
Try re-using the same API instead of re-initializing for each image:

```python
with PyTessBaseAPI(oem=0) as api:
    for image in image_list:
	image1= PIL.Image.open(path+image)
	api.SetImage(image1)
	api.Recognize()
	iterator = api.GetIterator()
	if iterator.WordFontAttributes() is None:
		print "None"
```

**Comment by vatsal28** [comment]
Same error again :(

**Comment by vatsal28** [comment]
Bump

**Comment by sirfz** [comment]
I can't debug this as I have no way to reproduce it. I personally suspect it's specific images but according to you that's not the case which makes this a possible problem with tesseract itself or maybe your environment but I can't help with that.

**Comment by s-alexey** [comment]
@vatsal28 try to use `api.SetImageFile` instead of using `PIL.Image.open`.
