### ISSUE TITLE
Tesserocr doesn't return correct text with bounding boxes

### ISSUE THREAD

**Issue by AzkaGilani** [sirfz/tesserocr#83]
I am trying to use tesserocr in my project, api.GetUTF8Text() normally works fine but if i try to return bounding boxes of these words along with their text, then it gives some weird results as string.
The example that i am trying to run is as follows:
```
from PIL import Image
from tesserocr import PyTessBaseAPI, RIL

image = Image.open('/usr/src/tesseract/testing/phototest.tif')
with PyTessBaseAPI() as api:
    api.SetImage(image)
    boxes = api.GetComponentImages(RIL.TEXTLINE, True)
    print 'Found {} textline image components.'.format(len(boxes))
    for i, (im, box, _, _) in enumerate(boxes):
        # im is a PIL image object
        # box is a dict with x, y, w and h keys
        api.SetRectangle(box['x'], box['y'], box['w'], box['h'])
        ocrResult = api.GetUTF8Text()
        conf = api.MeanTextConf()
        print (u"Box[{0}]: x={x}, y={y}, w={w}, h={h}, "
               "confidence: {1}, text: {2}").format(i, conf, ocrResult, **box)
```
Python 3.5, Tesseract 4.0

**Comment by mfarooq-dcube** [comment]
try to use iterator level output as we can do in c++. Tesserocr has the same capability as it have in c++. so, i got bounding boxes and text by iterating the word level. Here is my code:

def performTessOCR(img): #cvmat object
    image = Image.fromarray(img)
    dictOCR = {}
    if img is not None:
        with PyTessBaseAPI(oem=0) as api:
            api.SetImage(image)
            api.Recognize()
            ri = api.GetIterator()
            level = RIL.WORD
            index = 0
            for r in iterate_level(ri, level):
                text = r.GetUTF8Text(level)  # r == ri
                conf = r.Confidence(level)
                left, top, right, bottom = r.BoundingBox(level)
                dictOCR[index] = left, top, right, bottom, text
                index += 1

    return dictOCR

**Comment by Ashargin** [comment]
You should be able to return the boxes boundaries as well using tesserocr in Python.
Here is what I suggest (Python 3.6, Tesseract 4.0):

`from PIL import Image
from tesserocr import PyTessBaseAPI, RIL

texts = []
image = Image.open('/usr/src/tesseract/testing/phototest.tif')
with PyTessBaseAPI() as api:
    api.SetImage(image)
    boxes = api.GetComponentImages(ril, True)
    print('Found {} image components.'.format(len(boxes)))
    for i, (im, box, _, _) in enumerate(boxes):
        # im is a PIL image object
        # box is a dict with x, y, w and h keys
            api.SetRectangle(box['x'], box['y'], box['w'], box['h'])
            ocrResult = api.GetUTF8Text()
            texts.append(ocrResult)`

You can then see the boxes on the image and access their coordinates with:

`import matplotlib.pyplot as plt
import numpy as np
import cv2

image_array = np.array(image)
# image_array = cv2.cvtColor(image_array, cv2.COLOR_GRAY2RGB) # if the image is in grayscale
for box in boxes:
    box = box[1]
    x, y, w, h = box['x'], box['y'], box['w'], box['h']
    cv2.line(image_array, (x, y), (x + w, y), (255, 0, 0), 5)
    cv2.line(image_array, (x, y), (x, y + h), (255, 0, 0), 5)
    cv2.line(image_array, (x + w, y), (x + w, y + h), (255, 0, 0), 5)
    cv2.line(image_array, (x, y + h), (x + w, y + h), (255, 0, 0), 5)
plt.imshow(image_array) # use cmap='gray' is the image is in grayscale
plt.show()`

I hope it helps, I'm not exactly sure why you're having trouble accessing the box boundaries.
