### ISSUE TITLE
Utf-8 error "invalid continuation byte"

### ISSUE THREAD

**Issue by jonzlin95** [sirfz/tesserocr#85]
https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx - Line 51

Firstly thanks for all your work on this library. One of the computers that I installed this on has very weird characters in the directory path (due to a username in hungarian). I've tracked the error to the line above, and the error is 

```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 13: invalid contnuation byte```

The code fails on C:\Török ván\

The system in question is running Windows 10, 64bit Hungarian. Tesseract version 3.05

Thanks
Jonathan

**Comment by sirfz** [comment]
All strings returned by the tesseract API are [encoded as UTF-8 in tesserocr](https://github.com/sirfz/tesserocr/blob/master/tesserocr.pyx#L2), in your case it seems that the string returned by `GetDataPath` is not UTF-8 coded. I'm not sure if it's wrong to assume the encoding for `GetDataPath` and other functions that return string other than `GetUTF8Text`, might need to look into that.

In the mean time, is there some kind of environment variable on Windows that specifies the system's default encoding? Maybe you can try changing that and see if it fixes your problem.

**Comment by jonzlin95** [comment]
Thanks for the super quick response. We're actually bundling this library as part of a larger application that's installed onto users' computers directly, so I ended up getting around this issue by using a hard-coded installation path.

I believe this is actually a [NTFS level thing](https://stackoverflow.com/questions/2050973/what-encoding-are-filenames-in-ntfs-stored-as), so it might be possible to just do a windows check and default to UTF-16, though it won't be perfect because of [filename limitations](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations)

**Comment by GulevskiyDaniil** [comment]
I've got the same problem.

By using Python3.6.4 and `PyTessBaseAPI(lang='rus')` this error occurred in `api.GetUTF8Text()`: 

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 4: invalid continuation byte`

But this error does not occurred by using Python3.6.4 and `PyTessBaseAPI()` [default lang='eng'].
Also, this error does not occur in Python2.7.11 in both cases (lang='rus' & default').

---------
My system: macOS High sierra, tesseract-3.05.01.high_sierra

**Comment by sirfz** [comment]
Can you provide a full example @GulevskiyDaniil with your tesseract, tessdata and Cython versions please? Supplying the image would be helpful as well.

**Comment by GulevskiyDaniil** [comment]
@sirfz 
The same behaviour for rus1 and frus2.
There are images of code and outputs:

<img width="715" alt="python3" src="https://user-images.githubusercontent.com/28872924/36371589-a643585a-1573-11e8-9bb4-4c1c1b611dcd.png">
<img width="719" alt="python2" src="https://user-images.githubusercontent.com/28872924/36371590-a65e5420-1573-11e8-9a68-0ed4b5f076d6.png">
