### ISSUE TITLE
Error: ‘OEM_CUBE_ONLY’ is not a member of ‘tesseract’

### ISSUE THREAD

**Issue by miqayel-manvelyan** [sirfz/tesserocr#87]
Install
`CPPFLAGS=-I/usr/local/include pip install tesserocr==2.2.1`

Collecting tesserocr==2.2.1
  Using cached tesserocr-2.2.1.tar.gz
Building wheels for collected packages: tesserocr
  Running setup.py bdist_wheel for tesserocr ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-acn9d92s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp6uldqosopip-wheel- --python-tag cp35:
  Supporting tesseract v4.00.00dev
  Configs from pkg-config: {'include_dirs': ['/usr/local/include'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'libraries': ['tesseract', 'lept']}
  running bdist_wheel
  running build
  running build_ext
  building 'tesserocr' extension
  creating build
  creating build/temp.linux-x86_64-3.5
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -I/usr/local/include -fPIC -I/usr/local/include -I/usr/include/python3.5m -c tesserocr.cpp -o build/temp.linux-x86_64-3.5/tesserocr.o -std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  tesserocr.cpp: In function ‘PyObject* PyInit_tesserocr()’:
  tesserocr.cpp:34380:69: error: ‘OEM_CUBE_ONLY’ is not a member of ‘tesseract’
     __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_CUBE_ONLY); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 84, __pyx_L1_error)
                                                                       ^
  tesserocr.cpp:34393:69: error: ‘OEM_TESSERACT_CUBE_COMBINED’ is not a member of ‘tesseract’
     __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_CUBE_COMBINED); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 85, __pyx_L1_error)
                                                                       ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for tesserocr
  Running setup.py clean for tesserocr
Failed to build tesserocr
Installing collected packages: tesserocr
  Running setup.py install for tesserocr ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-acn9d92s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9vppbp43-record/install-record.txt --single-version-externally-managed --compile:
    Supporting tesseract v4.00.00dev
    Configs from pkg-config: {'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'include_dirs': ['/usr/local/include'], 'library_dirs': ['/usr/local/lib'], 'libraries': ['tesseract', 'lept']}
    running install
    running build
    running build_ext
    building 'tesserocr' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -I/usr/local/include -fPIC -I/usr/local/include -I/usr/include/python3.5m -c tesserocr.cpp -o build/temp.linux-x86_64-3.5/tesserocr.o -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    tesserocr.cpp: In function ‘PyObject* PyInit_tesserocr()’:
    tesserocr.cpp:34380:69: error: ‘OEM_CUBE_ONLY’ is not a member of ‘tesseract’
       __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_CUBE_ONLY); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 84, __pyx_L1_error)
                                                                         ^
    tesserocr.cpp:34393:69: error: ‘OEM_TESSERACT_CUBE_COMBINED’ is not a member of ‘tesseract’
       __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_CUBE_COMBINED); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 85, __pyx_L1_error)
                                                                         ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------

Pls HELP! :(

**Comment by Belval** [comment]
This is a known issue, addressed by PR #86 that is not merged yet.

**Comment by sirfz** [comment]
The PR has been merged, please try install tesserocr from master.

**Comment by miqayel-manvelyan** [comment]
Thank you for your answer. It's worked :)
