### ISSUE TITLE
fatal error C1083: Cannot open include file: 'leptonica/allheaders.h'

### ISSUE THREAD

**Issue by zhuzhengwen1983** [sirfz/tesserocr#89]
Windows 10;
Python 3.6;
run: pip install tesserocr
the Error Message:
![image](https://user-images.githubusercontent.com/846381/35960806-1ae71692-0ce6-11e8-8d3c-2c5a6d3414b8.png)

**Comment by zhuzhengwen1983** [comment]
I find the site : https://github.com/sirfz/tesserocr/issues/19
but I don't know why.

**Comment by dgvogol** [comment]
@zhuzhengwen1983, I don't get it. In my environment, the build script will collect the "leptonica/allheaders.h" and other header files, put them under "build/tesseract_build" directory. Which repository are you using? Can you try this repository https://github.com/dgvogol/tesserocr.git, the windows_build branch, and let me know the result

**Comment by zhuzhengwen1983** [comment]
Thanks for @dgvogol.  I try your repository.it has the issue too. I don't know. In my environment, the build script will not collect the leptonica and other tesseract files for build. I use repository : https://pypi.python.org/pypi/tesserocr
I thinks the problem is my environment issue.
I don't know why my environment can't collect the 'leptonica' and 'tesseract' files for build

**Comment by zhuzhengwen1983** [comment]
@dgvogol in my windows 10 environment install your repository. it has the error message.
![image](https://user-images.githubusercontent.com/846381/36459962-340b0d4e-16f1-11e8-8e61-d59597b753a4.png)

**Comment by Pfed-prog** [comment]
Struggle with installing tesseract-ocr on macos and gives the same error message. Could you tell me how have you dealt with this error?

**Comment by JoelOnGithub** [comment]
Probably a bit late, but you need to install tesseract on mac.

`brew install tesseract` solves this.

**Comment by dickreuter** [comment]
i have installed tesseract, but still getting the error tesserocr.cpp:796:10: fatal error: 'leptonica/allheaders.h' file not found when I try to install tesserocr. Any suggestions would be appreciated.

**Comment by zdenop** [comment]
@dickreuter : install leptonica with header/development files

**Comment by dickreuter** [comment]
Any guidance how to do that? Thanks
