### ISSUE TITLE
Missing CPPFLAGS=-DUSE_STD_NAMESPACE

### ISSUE THREAD

**Issue by wrznr** [sirfz/tesserocr#90]
When trying to install via pip using the master from https://github.com/tesseract-ocr/tesseract, I got a number of `string`-related compilation errors:
```
In file included from tesserocr.cpp:579:0:
    /usr/local/include/tesseract/unichar.h:164:10: error: ‘string’ does not name a type
       static string UTF32ToUTF8(const std::vector<char32>& str32);
```
Using `CPPFLAGS=-DUSE_STD_NAMESPACE pip install tesserocr` helps. It would be great if this define could be added to the standard installation procedure since I do not see a way to pass `CPPFLAGS` via `requirements.txt` in my `tesserocr`-dependent project.

**Comment by sirfz** [comment]
already fixed in master branch (see #66)
