### ISSUE TITLE
tesserocr.cpp:34393:69: error: 'OEM_TESSERACT_CUBE_COMBINED' is not a member of 'tesseract'

### ISSUE THREAD

**Issue by KarteekGIT** [sirfz/tesserocr#91]
Hi, Please help me, I got the following error while installing tesserocr from master branch as well as using pip install. 
python 3.6
raspberry pi debian jessie
tesseract 4.0.0dev
leptonica 1.74.4

**Downloading/unpacking tesserocr
  Downloading tesserocr-2.2.2.tar.gz (53kB): 53kB downloaded
  Running setup.py (path:/tmp/pip-build-p3fm1H/tesserocr/setup.py) egg_info for package tesserocr
    Supporting tesseract v4.00.00dev
    Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/include']}
    Compiling tesserocr.pyx because it changed.
    [1/1] Cythonizing tesserocr.pyx
    warning: no previously-included files found matching '*.so'
Installing collected packages: tesserocr
  Running setup.py install for tesserocr
    Supporting tesseract v4.00.00dev
    Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/include']}
    building 'tesserocr' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -DUSE_STD_NAMESPACE -fPIC -I/usr/local/include -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-armv7l-2.7/tesserocr.o -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    tesserocr.cpp: In function 'void inittesserocr()':
    tesserocr.cpp:34976:69: error: 'OEM_CUBE_ONLY' is not a member of 'tesseract'
       __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_CUBE_ONLY); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 84, __pyx_L1_error)
                                                                         ^
    tesserocr.cpp:34989:69: error: 'OEM_TESSERACT_CUBE_COMBINED' is not a member of 'tesseract'
       __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_CUBE_COMBINED); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 85, __pyx_L1_error)
                                                                         ^
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-p3fm1H/tesserocr/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6myMwD-record/install-record.txt --single-version-externally-managed --compile:
    Supporting tesseract v4.00.00dev

Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'cython_compile_time_env': {'TESSERACT_VERSION': 262144}, 'library_dirs': ['/usr/local/lib'], 'include_dirs': ['/usr/local/include']}

running install

running build

running build_ext

building 'tesserocr' extension

creating build

creating build/temp.linux-armv7l-2.7

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -DUSE_STD_NAMESPACE -fPIC -I/usr/local/include -I/usr/include/python2.7 -c tesserocr.cpp -o build/temp.linux-armv7l-2.7/tesserocr.o -std=c++11

cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++

tesserocr.cpp: In function 'void inittesserocr()':

tesserocr.cpp:34976:69: error: 'OEM_CUBE_ONLY' is not a member of 'tesseract'

   __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_CUBE_ONLY); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 84, __pyx_L1_error)

                                                                     ^

tesserocr.cpp:34989:69: error: 'OEM_TESSERACT_CUBE_COMBINED' is not a member of 'tesseract'

   __pyx_t_1 = __Pyx_PyInt_From_enum__tesseract_3a__3a_OcrEngineMode(tesseract::OEM_TESSERACT_CUBE_COMBINED); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 85, __pyx_L1_error)

                                                                     ^

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-p3fm1H/tesserocr/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-6myMwD-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-p3fm1H/tesserocr
Storing debug log for failure in /home/pi/.pip/pip.log**

**Comment by Belval** [comment]
See https://github.com/sirfz/tesserocr/issues/87

**Comment by KarteekGIT** [comment]
Thanks a lot. It’s worked.
