### ISSUE TITLE
Different result using tesserocr and command line version

### ISSUE THREAD

**Issue by TheSithPadawan** [sirfz/tesserocr#96]
Hi,

I'm getting different results for the same document using tesserocr and the command line version of Tesseract. It seems like tesserocr is not getting some of the words. What could be wrong? Thanks!

I'm using this function to get all the words from an image:
```python
def get_word_data(img):
    image = Image.open(img, mode='r')
    pdf = pdfpage.PDFPage('folder location', 1)
    level = RIL.WORD
    with PyTessBaseAPI() as api:
        api.SetImage(image)
        boxes = api.GetComponentImages(RIL.WORD, True)
        for i, (im, box, _, _)in enumerate(boxes):
            api.SetRectangle(box['x'], box['y'], box['w'], box['h'])
            ocrResult = api.GetUTF8Text()
            ocrResult = ocrResult.strip()
            if len(ocrResult) != 0:
                conf = api.MeanTextConf()
                if (ocrResult[-1] in punct):
                    ocrResult = ocrResult[:-1]
                doc_word = word.Word(
                    i,
                    box['x'],
                    box['y'],
                    box['w'],
                    box['h'],
                    conf,
                    ocrResult)
                pdf.add_word(doc_word)
    image.close()
    return pdf
```

**Comment by sirfz** [comment]
Try using `api.SetImageFile` instead of `api.SetImage` to make sure it's not `PIL.Image` altering the image somehow.

**Comment by TheSithPadawan** [comment]
Nope.. SetImageFile seems to give even worse result.

I have uploaded the file and you can try to reproduce the issue....
![kic image 0001](https://user-images.githubusercontent.com/16431283/37669031-366f1048-2c3c-11e8-86f8-45f65c251d0b.png)

**Comment by sirfz** [comment]
What's the command you're running via the cli? It could be calling a different API so you can't compare with that.

Try running an example similar to [Iterator over the classifier choices for a single symbol](https://github.com/sirfz/tesserocr#iterator-over-the-classifier-choices-for-a-single-symbol).

**Comment by TheSithPadawan** [comment]
I'm using tesseract filname outputname on the command line, basically all the default settings.
My issue is that in my code, I'm not getting some words like: PAGE, RUN TIME, RUN USER, etc..
My goal is not to get the recognition result on a single symbol or a box, but to get all the words on a document. Thanks!

**Comment by amitdo** [comment]
The default psm when using the comman line is 6 (Auto layout analysis).

The default psm when using the C++ API is 3 (Single Block).
